const lines = [
  "Geo Publisher CLI Help",
  "",
  "Recommended flow:",
  "  1) Validate target space and schema",
  "     - bun run api:check",
  "     - bun run api:schema:check",
  "",
  "  2) Generate mapping proposals from CSV + live schema",
  "     - bun run map:propose -- --target-space <SPACE_ID>",
  "",
  "  3) Review approvals",
  "     - bun run map:decide -- --action list",
  "     - bun run map:decide -- --action accept --type course --field \"Topics\"",
  "     - bun run map:decide -- --action reject --type lesson --field \"Stages\"",
  "",
  "  4) Configure relation behavior (optional but recommended)",
  "     - bun run map:decide -- --action set-relation --type course --field \"Providers\" --mode by_name --creation create_if_missing --target-type-id 484a18c5030a499cb0f2ef588ff16d50",
  "     - bun run map:decide -- --action set-relation --type lesson --field \"Courses\" --mode by_source_id --creation must_exist --cross-target-set course --cross-target-key course_id",
  "",
  "     Relation modes:",
  "     - by_name: match target entity by name",
  "     - by_slug: match by normalized slug",
  "     - by_source_id: match via source IDs (cross-file links)",
  "     - manual_map: use --manual-map-json for explicit source->target mapping",
  "",
  "     Target creation policy:",
  "     - must_exist: fail/skip unresolved target",
  "     - create_if_missing: create relation target entity if missing (requires --target-type-id)",
  "",
  "  5) Dry run publish ops",
  "     - bun run publish:courses-lessons",
  "     - (includes content-policy + URL + taxonomy overlap checks)",
  "     - add --strict-policy-warnings to fail on warnings",
  "     - add --allow-broken-urls to bypass URL gate",
  "     - add --allow-taxonomy-similar to bypass taxonomy-similar gate",
  "",
  "  6) Publish on-chain",
  "     - bun run publish:courses-lessons -- --publish",
  "     - Note: DAO target spaces submit proposals; data may not appear until DAO applies the edit.",
  "",
  "  7) Undo last publish set (uses data_to_delete/courses_lessons_publish_ops.txt)",
  "     - bun run undo:courses-lessons -- --publish",
  "  8) Hard reset current target-space entities (keeps space page)",
  "     - bun run zero:target-space -- --publish",
  "  9) Add AI-style Learn tab with course collection",
  "     - bun run ui:learn-tab -- --publish",
  "",
  "Useful commands:",
  "  - bun run policy:check      # validate content policy against generated JSON",
  "  - bun run check:urls        # verify Web URL reachability across publish CSVs",
  "  - bun run check:taxonomy    # compare taxonomy terms against canonical AI space",
  "  - bun run check:prepublish  # run policy + URL + taxonomy checks together",
  "  - bun run api:demo          # query examples",
  "  - bun run api:crawl         # explore type graphs",
  "  - bun run geo:help          # show this help",
  "  - bun run undo:courses-lessons  # generate undo ops",
  "  - bun run zero:target-space  # generate full zero-space ops",
  "  - bun run ui:learn-tab  # create Learn heading/tab linked to courses",
  "",
  "Environment:",
  "  - TARGET_SPACE_ID: publish/query target space",
  "  - CANONICAL_TAXONOMY_SPACE_ID: canonical taxonomy source (defaults to AI space)",
  "  - PK_SW: signer wallet private key",
];

console.log(lines.join("\n"));
