import {existsSync,readFileSync,writeFileSync} from 'node:fs';
import {createHash,randomUUID} from 'node:crypto';
import {Ops,Position,SystemIds,type Op} from '@geoprotocol/geo-sdk';
import {geoGraphqlRequest as gql} from '../src/geo-api-client';
import {EDUCATION_PUBLICATION as target} from '../src/education-bounty';
const root='data/education',registryPath=`${root}/ewims-registry.json`,registry:Record<string,string>=existsSync(registryPath)?JSON.parse(readFileSync(registryPath,'utf8')):{};
const id=(key:string)=>registry[key]??(registry[key]=randomUUID().replaceAll('-',''));
const p={article:'a2a5ed0cacef46b1835de457956ce915',initiative:'d272f19cef87485fb83e26fb68957395',claim:'96f859efa1ca4b229372c86ad58b694b',factual:'da4a6c1f9d4446f9832ff3b49a4400ef',url:'412ff593e9154012a43d4c27ec5c68b6',source:'49c5d5e1679a4dbdbfd33f618f227c94',related:'dfa6aebe1ca94bf29faccc4cc7afb24c',estimate:'e500e2585a964d2c9df4a47b199616c3',unit:'8405509cc7354655a348591349a5f025'};
const checks:string[]=[],ops:Op[]=[],edges:any[]=[];const check=(ok:unknown,label:string)=>{if(!ok)throw Error(label);checks.push(label)};
const rel=(key:string,from:string,type:string,to:string)=>{const position=registry[`position/${key}`]??(registry[`position/${key}`]=Position.generate());ops.push(...Ops.relations.create({id:id(`edge/${key}`),entityId:id(`edge-entity/${key}`),fromEntity:from,type,toEntity:to,position}).ops);edges.push({from,type,to});};
const decimal=(property:string,value:string)=>{const [whole,fraction='']=value.split('.');const negative=whole.startsWith('-');const digits=`${negative?whole.slice(1):whole}${fraction}`;return{property,type:'decimal' as const,exponent:-fraction.length,mantissa:{type:'i64' as const,value:BigInt(`${negative?'-':''}${digits}`)}};};
const articleName='Getting Students on Track for Graduation: Impacts of the Early Warning Intervention and Monitoring System after One Year',initiativeName='Early Warning Intervention and Monitoring System (EWIMS)';
for(const [filename,label] of [[`${root}/discovery/getting-students-on-track-for-graduation-impacts-of-the-early-warning-intervention-and-monitoring-system-after-one-year.json`,'Article'],[`${root}/discovery/early-warning-intervention-and-monitoring-system.json`,'Initiative'],[`${root}/discovery/contains-early-warning-intervention.json`,'semantic family']]){const d=JSON.parse(readFileSync(filename,'utf8'));check(d.complete&&d.nodes.length===0,`Complete all-space ${label} discovery found no candidate`);}
for(const [property,type] of [[SystemIds.TYPES_PROPERTY,'Relation'],[p.source,'Relation'],[p.related,'Relation'],[p.factual,'Checkbox'],[p.url,'Text'],[p.estimate,'Decimal'],[p.unit,'Text']]){const d:any=await gql('query($id:UUID!){property(id:$id){dataTypeName}}',{variables:{id:property}});check(d.property?.dataTypeName===type,`Live property type ${property}`);}
const article=id('article'),initiative=id('initiative');const findings=[
 {key:'design',name:'The EWIMS evaluation randomly assigned 73 high schools in three Midwestern states for the 2014/15 school year.',description:'Thirty-seven schools implemented EWIMS and 36 continued usual practice; the report studied first- and second-year high-school students after one year. This is a school-level randomized evaluation, not a claim about every early-warning system.',value:null,unit:null},
 {key:'chronic-absence',name:'After one year, EWIMS schools had a 4-percentage-point lower chronic-absence rate than control schools (10% versus 14%).',description:'Chronic absence means missing 10% or more of instructional time. The source reports this model-adjusted difference as statistically significant after one year of adoption.',value:'-4',unit:'Percentage-point difference in chronic-absence risk: EWIMS minus control, after one year.'},
 {key:'course-failure',name:'After one year, EWIMS schools had a 5-percentage-point lower rate of failing one or more courses than control schools (21% versus 26%).',description:'The source reports this model-adjusted difference as statistically significant after one year of adoption. It is a course-failure risk result, not a graduation-rate estimate.',value:'-5',unit:'Percentage-point difference in one-or-more-course-failure risk: EWIMS minus control, after one year.'},
 {key:'credits',name:'After one year, EWIMS showed no statistically significant effect on insufficient credits for on-time graduation (14% in each group).',description:'This is the report’s first-year null result for progress in school. It does not establish that the exact effect was zero or rule out later changes in graduation.',value:'0',unit:'Percentage-point difference in insufficient-credits risk: EWIMS minus control, after one year; reported 14% in both groups.'},
 {key:'implementation',name:'The EWIMS report found that implementation of its seven-step process was generally low and challenging in the first year.',description:'Schools more often reported using an early-warning system and dedicated team, but the report found no detectable school-data-culture effect and did not identify the staff actions causing the attendance and course-failure changes.',value:null,unit:null}
];
for(const entityId of [article,initiative,...findings.map(x=>id(`claim/${x.key}`))]){const d:any=await gql('query($id:UUID!){entity(id:$id){spaceIds}}',{variables:{id:entityId}});check(!d.entity?.spaceIds?.length,`Persistent ID is unoccupied: ${entityId}`);}
ops.push(...Ops.entities.update({id:article,name:articleName,description:'A 2017 IES/REL Midwest report on the first-year randomized evaluation of EWIMS in high schools.',values:[{property:p.url,type:'text',value:'https://ies.ed.gov/use-work/resource-library/report/impact-study/getting-students-track-graduation-impacts-early-warning-intervention-and-monitoring-system-after-one'}]}).ops);rel('article/type',article,SystemIds.TYPES_PROPERTY,p.article);
ops.push(...Ops.entities.update({id:initiative,name:initiativeName,description:'A seven-step early-warning process that uses attendance, behavior and course-performance data to identify students, assign supports and monitor progress. The linked trial evaluates one first-year implementation, not every local data tool.',values:[{property:p.url,type:'text',value:'https://ies.ed.gov/use-work/resource-library/report/impact-study/getting-students-track-graduation-impacts-early-warning-intervention-and-monitoring-system-after-one'}]}).ops);rel('initiative/type',initiative,SystemIds.TYPES_PROPERTY,p.initiative);rel('initiative/source',initiative,p.source,article);rel('initiative/article',initiative,p.related,article);
for(const row of findings){const claim=id(`claim/${row.key}`),values:any[]=[{property:p.factual,type:'boolean',value:true}];if(row.value!==null)values.push(decimal(p.estimate,row.value),{property:p.unit,type:'text',value:row.unit});ops.push(...Ops.entities.update({id:claim,name:row.name,description:row.description,values}).ops);rel(`claim/${row.key}/type`,claim,SystemIds.TYPES_PROPERTY,p.claim);rel(`claim/${row.key}/source`,claim,p.source,article);rel(`claim/${row.key}/initiative`,claim,p.related,initiative);}
const bytes=JSON.stringify(ops,(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('hex')}:typeof v==='bigint'?{$bigint:v.toString()}:v,2)+'\n',sha256=createHash('sha256').update(bytes).digest('hex');
const batch={name:'Add EWIMS randomized evaluation and first-year outcomes',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/ewims-ops.json`,sha256,journalPath:`${root}/ewims-publication.json`,validationPath:`${root}/ewims-validation.json`,entities:{article,initiative,findings:Object.fromEntries(findings.map(x=>[x.key,id(`claim/${x.key}`)]))},operationCount:ops.length};
writeFileSync(registryPath,JSON.stringify(registry,null,2)+'\n');writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/ewims-batch.json`,JSON.stringify(batch,null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),opsHash:sha256,checks,edges,source:{title:articleName,publisher:'IES / REL Midwest',year:2017,design:'73-school randomized evaluation in three Midwestern states; first-year results',limit:'Risk indicators are not on-time graduation. Preserve outcome-specific nulls and implementation limitations.'}},null,2)+'\n');console.log(JSON.stringify(batch,null,2));
