import {existsSync,readFileSync,writeFileSync} from 'node:fs';
import {createHash,randomUUID} from 'node:crypto';
import {Ops,Position,SystemIds,type Op} from '@geoprotocol/geo-sdk';
import {geoGraphqlRequest as gql} from '../src/geo-api-client';
import {EDUCATION_PUBLICATION as target} from '../src/education-bounty';
const root='data/education',registryPath=`${root}/head-start-registry.json`,registry:Record<string,string>=existsSync(registryPath)?JSON.parse(readFileSync(registryPath,'utf8')):{};
const id=(key:string)=>registry[key]??(registry[key]=randomUUID().replaceAll('-',''));
const p={dataset:'0c4babfb43893486af827341bbf32e09',article:'a2a5ed0cacef46b1835de457956ce915',claim:'96f859efa1ca4b229372c86ad58b694b',factual:'da4a6c1f9d4446f9832ff3b49a4400ef',url:'412ff593e9154012a43d4c27ec5c68b6',doi:'7cb59354e30c48119e99ff62fcf61646',source:'49c5d5e1679a4dbdbfd33f618f227c94',related:'dfa6aebe1ca94bf29faccc4cc7afb24c',topics:'806d52bc27e94c9193c057978b093351',topic:'0df9fad9098d4b11bacb9af0f7a79182'};
const checks:string[]=[],ops:Op[]=[],edges:any[]=[];const check=(ok:unknown,label:string)=>{if(!ok)throw Error(label);checks.push(label)};
const rel=(key:string,from:string,type:string,to:string)=>{const position=registry[`position/${key}`]??(registry[`position/${key}`]=Position.generate());ops.push(...Ops.relations.create({id:id(`edge/${key}`),entityId:id(`edge-entity/${key}`),fromEntity:from,type,toEntity:to,position}).ops);edges.push({from,type,to});};
const name='Third Grade Follow-up to the Head Start Impact Study (HSIS), United States, 2007-2008';
const discovery=JSON.parse(readFileSync(`${root}/discovery/third-grade-follow-up-to-the-head-start-impact-study-hsis-united-states-2007-2008.json`,'utf8'));
check(discovery.complete&&discovery.nodes.length===0,'Complete all-space exact Dataset-name discovery found no candidate');
for(const [property,type] of [[SystemIds.TYPES_PROPERTY,'Relation'],[p.source,'Relation'],[p.related,'Relation'],[p.factual,'Checkbox'],[p.url,'Text'],[p.doi,'Text'],[p.topics,'Relation']]){const d:any=await gql('query($id:UUID!){property(id:$id){dataTypeName}}',{variables:{id:property}});check(d.property?.dataTypeName===type,`Live property type ${property}`);}
const article=registry['article/third-grade-followup'],initiative=registry.initiative,dataset=id('dataset/third-grade-followup-icpsr'),claim=id('claim/third-grade/data-access');check(!!article&&!!initiative,'Existing Head Start follow-up endpoints are stable');
for(const entityId of [dataset,claim]){const found:any=await gql('query($id:UUID!){entity(id:$id){spaceIds}}',{variables:{id:entityId}});check(!found.entity?.spaceIds?.length,`Persistent ID is unoccupied: ${entityId}`);}
ops.push(...Ops.entities.update({id:dataset,name,description:'ICPSR’s archive for the Head Start third-grade follow-up. Documentation is public; some analytic data files require a restricted-data agreement to protect respondent privacy.',values:[{property:p.doi,type:'text',value:'10.3886/ICPSR35003.v2'},{property:p.url,type:'text',value:'https://www.childandfamilydataarchive.org/cfda/archives/cfda/studies/35003'}]}).ops);rel('third-grade/dataset/type',dataset,SystemIds.TYPES_PROPERTY,p.dataset);rel('third-grade/dataset/source',dataset,p.source,article);rel('third-grade/dataset/initiative',dataset,p.related,initiative);rel('third-grade/dataset/topic',dataset,p.topics,p.topic);
ops.push(...Ops.entities.update({id:claim,name:'The ICPSR Head Start third-grade archive provides public documentation, while some data files require a restricted-data agreement.',description:'The archive separates public-use documentation from protected files. This is a data-access statement, not permission to republish microdata or a claim that every file is openly downloadable.',values:[{property:p.factual,type:'boolean',value:true}]}).ops);rel('third-grade/data-access/type',claim,SystemIds.TYPES_PROPERTY,p.claim);rel('third-grade/data-access/source',claim,p.source,article);rel('third-grade/data-access/dataset',claim,p.related,dataset);rel('third-grade/data-access/initiative',claim,p.related,initiative);rel('third-grade/data-access/topic',claim,p.topics,p.topic);
const bytes=JSON.stringify(ops,(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('hex')}:typeof v==='bigint'?{$bigint:v.toString()}:v,2)+'\n',sha256=createHash('sha256').update(bytes).digest('hex');
const batch={name:'Add Head Start third-grade data access resource',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/head-start-data-resource-ops.json`,sha256,journalPath:`${root}/head-start-data-resource-publication.json`,validationPath:`${root}/head-start-data-resource-validation.json`,entities:{dataset,claim},operationCount:ops.length};
writeFileSync(registryPath,JSON.stringify(registry,null,2)+'\n');writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/head-start-data-resource-batch.json`,JSON.stringify(batch,null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),opsHash:sha256,checks,edges,source:{archive:'ICPSR 35003',doi:'10.3886/ICPSR35003.v2',url:'https://www.childandfamilydataarchive.org/cfda/archives/cfda/studies/35003',access:'Documentation public; protected files require ICPSR restricted-data agreement.'}},null,2)+'\n');console.log(JSON.stringify(batch,null,2));
