import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash, randomUUID } from 'node:crypto';
import { Ops, Position, SystemIds, type Op } from '@geoprotocol/geo-sdk';
import { geoGraphqlRequest as gql } from '../src/geo-api-client';
import { EDUCATION_PUBLICATION as target } from '../src/education-bounty';

const root = 'data/education', prefix = 'pace-2019';
if (existsSync(`${root}/${prefix}-publication.json`)) throw new Error('Preserve submitted payload.');
const registryPath = `${root}/${prefix}-registry.json`;
const registry: Record<string, string> = existsSync(registryPath) ? JSON.parse(readFileSync(registryPath, 'utf8')) : {};
const id = (key: string) => registry[key] ?? (registry[key] = randomUUID().replaceAll('-', ''));
const p = { article: 'a2a5ed0cacef46b1835de457956ce915', initiative: 'd272f19cef87485fb83e26fb68957395', claim: '96f859efa1ca4b229372c86ad58b694b', factual: 'da4a6c1f9d4446f9832ff3b49a4400ef', url: '412ff593e9154012a43d4c27ec5c68b6', source: '49c5d5e1679a4dbdbfd33f618f227c94', related: 'dfa6aebe1ca94bf29faccc4cc7afb24c', estimate: 'e500e2585a964d2c9df4a47b199616c3', cost: '6ba2ce00db064687b108aa8449672886', sample: '210e9b352b454d6eb7a32906d24d3c8d', unit: '8405509cc7354655a348591349a5f025', locator: '84dacbddca6a44079edb5e11a4c66b40', pValue: 'ba5f8fe9d1cd9a6094338d2f37b74a5e', year: '97e14050fc49467bb3aaf4d7eccbbb69', currency: '6e7371ca96cb44348f16932f77f55e75', denominator: '3a558d71454745a992c035040f648729' };
const url = 'https://www.mdrc.org/work/publications/focusing-girls-futures/file-full';
const articleName = 'Focusing on Girls’ Futures: Results from the Evaluation of PACE Center for Girls';
const initiativeName = 'PACE Center for Girls evaluated Florida program model';
const rows = [
  ['design', 'PACE randomly assigned 1,125 eligible Florida applicants across 14 centers.', 'The 2013–2015 evaluation assigned 673 girls to an offer of PACE and 452 to referrals for alternative community services. It evaluates a voluntary, nonresidential, year-round academic and social-service package.', null, 1125, 'Randomized controlled trial; 673 program group and 452 control group.', null, 'Overview, p. iii; Executive Summary pp. ES-3–ES-4.'],
  ['net-cost', 'PACE’s net societal service cost was about $10,400 per program-group girl (May 2017 dollars).', 'The 12-month cost difference compares PACE and other services with control services. It adjusts PACE to a 7.9-month average stay, excludes participant opportunity costs, and is not a benefit-cost ratio.', 10400, 1125, 'May 2017 USD net societal service cost per program-group girl over the 12-month cost-analysis window.', null, 'Table 4.3, p. 53; cost-method discussion pp. 50–53.'],
  ['days-present', 'PACE increased days present in school by 9.8 in the first follow-up year (119.6 versus 109.8).', 'This regression-adjusted Florida public-school administrative-record result covers the calendar year after study enrollment. It is an attendance outcome, not a graduation effect.', 9.8, 1040, 'Difference in number of school days present over the first follow-up calendar year, PACE minus control.', '0.013', 'Table ES.1, p. ES-8; Table 3.1, p. 33.'],
  ['on-track', 'PACE increased the high-school on-track composite by 13.4 percentage points (27.6% versus 14.2%).', 'The composite requires absence below 10% of enrolled days, no expulsion or suspension, and no core-course failure. It applies only to high-school students and is not observed graduation.', 13.4, 1040, 'Percentage-point difference in high-school on-track composite during first follow-up year, PACE minus control.', '< .001', 'Table ES.1, p. ES-8; Table 3.1, p. 33.'],
  ['credit-success', 'PACE increased credits earned as a share of credits attempted by 10.6 percentage points (77.5% versus 66.9%).', 'This regression-adjusted academic-year measure applies only to high-school students in Florida public-school records. The report found no statistically significant difference in total credits earned.', 10.6, 1040, 'Percentage-point difference in academic-year credits earned as a share of credits attempted, PACE minus control.', '0.001', 'Table 3.1, p. 33.'],
  ['suspension', 'PACE reduced ever-suspended status by 16.7 percentage points in the first follow-up year (29.6% versus 46.4%).', 'This Florida public-school administrative-record measure covers the calendar year after study enrollment. It is a short-term disciplinary outcome, not a later justice-system effect.', -16.7, 1040, 'Percentage-point difference in ever being suspended during first follow-up calendar year, PACE minus control.', '< .001', 'Table 3.1, p. 33.'],
  ['charge', 'PACE showed no statistically significant 18-month difference in girls incurring a juvenile-justice charge (+0.8 points; 22.0% versus 21.2%).', 'The full-sample Florida juvenile-justice administrative-record difference was not statistically significant. A charge is the report’s juvenile-justice term and should not be relabeled as an adult arrest.', 0.8, 1125, 'Percentage-point difference in incurring one or more juvenile-justice charges during 18 months after random assignment, PACE minus control.', '0.739', 'Table ES.1, p. ES-8; juvenile-justice discussion pp. ES-9–ES-10.'],
] as const;
const decimal = (property: string, value: number) => { const [whole, fraction = ''] = String(value).split('.'); return { property, type: 'decimal' as const, exponent: -fraction.length, mantissa: { type: 'i64' as const, value: BigInt(`${whole}${fraction}`) } }; };
const checks: string[] = []; const check = (ok: unknown, label: string) => { if (!ok) throw new Error(label); checks.push(label); };
for (const [property, type] of [[SystemIds.TYPES_PROPERTY, 'Relation'], [p.factual, 'Checkbox'], [p.url, 'Text'], [p.source, 'Relation'], [p.related, 'Relation'], [p.estimate, 'Decimal'], [p.cost, 'Decimal'], [p.sample, 'Integer'], [p.unit, 'Text'], [p.locator, 'Text'], [p.pValue, 'Text'], [p.year, 'Integer'], [p.currency, 'Text'], [p.denominator, 'Text']] as const) { const result: any = await gql('query($id:UUID!){property(id:$id){dataTypeName}}', { variables: { id: property } }); check(result.property?.dataTypeName === type, `Live ${type}: ${property}`); }
for (const [key, name] of [['article', articleName], ['initiative', initiativeName], ...rows.map(row => [`claim/${row[0]}`, row[1]])] as [string, string][]) { const result: any = await gql('query($id:UUID!,$name:String!){entity(id:$id){spaceIds}entitiesConnection(first:10,filter:{name:{isInsensitive:$name}}){nodes{id}pageInfo{hasNextPage}}}', { variables: { id: id(key), name } }); check(!result.entity?.spaceIds?.length, `Allocated identity unused: ${key}`); check(!result.entitiesConnection.pageInfo.hasNextPage && result.entitiesConnection.nodes.length === 0, `Complete all-space exact-title discovery has no candidate: ${key}`); }
const article = id('article'), initiative = id('initiative'), ops: Op[] = [];
const edge = (key: string, from: string, type: string, to: string) => { registry[`position/${key}`] ??= Position.generate(); ops.push(...Ops.relations.create({ id: id(`edge/${key}`), entityId: id(`relation/${key}`), fromEntity: from, type, toEntity: to, position: registry[`position/${key}`] }).ops); };
ops.push(...Ops.entities.update({ id: article, name: articleName, description: 'MDRC’s 2019 randomized impact and cost evaluation of the PACE Center for Girls program model in Florida.', values: [{ property: p.url, type: 'text', value: url }] }).ops); edge('article/type', article, SystemIds.TYPES_PROPERTY, p.article);
ops.push(...Ops.entities.update({ id: initiative, name: initiativeName, description: 'A voluntary, nonresidential, year-round Florida program combining academic instruction, counseling, case management, life-skills programming, and transition support for girls at risk of juvenile-justice involvement.', values: [{ property: p.url, type: 'text', value: url }] }).ops); edge('initiative/type', initiative, SystemIds.TYPES_PROPERTY, p.initiative); edge('initiative/source', initiative, p.source, article); edge('initiative/article', initiative, p.related, article);
for (const [key, name, description, value, sample, unit, pValue, locator] of rows) { const claim = id(`claim/${key}`), monetary = key === 'net-cost'; const values: any[] = [{ property: p.factual, type: 'boolean', value: true }, { property: p.sample, type: 'integer', value: BigInt(sample) }, { property: p.unit, type: 'text', value: unit }, { property: p.locator, type: 'text', value: locator }]; if (value !== null) values.push(decimal(monetary ? p.cost : p.estimate, value)); if (pValue) values.push({ property: p.pValue, type: 'text', value: `p = ${pValue}` }); if (monetary) values.push({ property: p.year, type: 'integer', value: 2017n }, { property: p.currency, type: 'text', value: 'USD' }, { property: p.denominator, type: 'text', value: 'Net societal service cost per program-group girl versus control services; 12-month window; PACE annual cost adjusted to 7.9-month average stay.' }); ops.push(...Ops.entities.update({ id: claim, name, description, values }).ops); edge(`${key}/type`, claim, SystemIds.TYPES_PROPERTY, p.claim); edge(`${key}/source`, claim, p.source, article); edge(`${key}/initiative`, claim, p.related, initiative); }
const bytes = JSON.stringify(ops, (_key, value) => value instanceof Uint8Array ? { $bytes: Buffer.from(value).toString('hex') } : typeof value === 'bigint' ? { $bigint: value.toString() } : value, 2) + '\n'; const sha256 = createHash('sha256').update(bytes).digest('hex'); const batch = { name: 'Add PACE Center for Girls randomized outcomes and cost analysis', spaceId: target.spaceId, bounty: target.bountyId, opsPath: `${root}/${prefix}-ops.json`, sha256, journalPath: `${root}/${prefix}-publication.json`, validationPath: `${root}/${prefix}-validation.json`, entities: { article, initiative, claims: Object.fromEntries(rows.map(row => [row[0], id(`claim/${row[0]}`)])) }, operationCount: ops.length };
writeFileSync(registryPath, JSON.stringify(registry, null, 2) + '\n'); writeFileSync(batch.opsPath, bytes); writeFileSync(`${root}/${prefix}-batch.json`, JSON.stringify(batch, null, 2) + '\n'); writeFileSync(batch.validationPath, JSON.stringify({ ready: true, checkedAt: new Date().toISOString(), opsHash: sha256, checks, source: { url, scope: '2019 MDRC randomized PACE impact and cost analysis.', limits: 'Short-term Florida outcomes; no full benefit-cost analysis or established long-term graduation/justice effect.' } }, null, 2) + '\n'); console.log(JSON.stringify(batch, null, 2));
