import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {createHash,randomUUID} from 'node:crypto';
import {Ops,Position,type Op} from '@geoprotocol/geo-sdk';
import {geoGraphqlRequest as gql} from '../src/geo-api-client';
import {EDUCATION_PUBLICATION as target} from '../src/education-bounty';
const root='data/education',prefix='coaching-bibliography-method',article='6a85813ac8734141b55affa06793661c',method='fd48f57b65f44436b393d448eca5d5bd',design='b1fdc75afb6841a18d8286427099ea44',doi='7cb59354e30c48119e99ff62fcf61646',sources='49c5d5e1679a4dbdbfd33f618f227c94';
if(existsSync(`${root}/${prefix}-publication.json`))throw Error('Preserve submitted payload');
const rp=`${root}/${prefix}-registry.json`,r:Record<string,string>=existsSync(rp)?JSON.parse(readFileSync(rp,'utf8')):{},id=(k:string)=>r[k]??(r[k]=randomUUID().replaceAll('-',''));
const discovery=JSON.parse(readFileSync(`${root}/bibliography-method-inspection.json`,'utf8'));if(discovery.searches.some((s:any)=>!s.complete)||Date.now()-Date.parse(discovery.checkedAt)>3600000)throw Error('Refresh discovery');
for(const [property,type] of [[design,'Relation'],[doi,'Text'],[sources,'Relation']]){const d:any=await gql('query($id:UUID!){property(id:$id){dataTypeName}}',{variables:{id:property}});if(d.property?.dataTypeName!==type)throw Error('Schema mismatch');}
const candidate:any=await gql('query($id:UUID!){entity(id:$id){id name spaceIds types{id name}}}',{variables:{id:method}});if(candidate.entity?.name!=='Meta-analysis'||!candidate.entity.spaceIds.includes('52c7ae149838b6d47ce0f3b2a5974546')||!candidate.entity.types.some((t:any)=>t.id==='07d23153ead146268af89189abe0b6f3'))throw Error('Method identity changed');
const current:any=await gql('query($id:UUID!,$space:UUID!){entity(id:$id){values(first:20,filter:{spaceId:{is:$space}}){nodes{propertyId text}pageInfo{hasNextPage}}relations(first:20,filter:{spaceId:{is:$space}}){nodes{typeId toEntityId}pageInfo{hasNextPage}}}}',{variables:{id:article,space:target.spaceId}});
if(!current.entity||current.entity.values.pageInfo.hasNextPage||current.entity.relations.pageInfo.hasNextPage)throw Error('Incomplete Article');
if(!current.entity.values.nodes.some((v:any)=>v.propertyId==='412ff593e9154012a43d4c27ec5c68b6'&&v.text==='https://doi.org/10.3102/0034654318759268')||current.entity.values.nodes.some((v:any)=>v.propertyId===doi)||current.entity.relations.nodes.some((e:any)=>e.typeId===design))throw Error('Article needs renewed review');
const relEntity=id('method-relation'),ops:Op[]=[...Ops.entities.update({id:article,values:[{property:doi,type:'text',value:'https://doi.org/10.3102/0034654318759268'}]}).ops,
 ...Ops.relations.create({id:id('method-edge'),entityId:relEntity,fromEntity:article,type:design,toEntity:method,position:r.position??(r.position=Position.generate())}).ops,
 ...Ops.entities.update({id:relEntity,description:'The paper synthesizes 60 studies using causal designs; it is not a single randomized trial. Its pooled and subgroup estimates summarize overlapping sets of coaching programs.'}).ops,
 ...Ops.relations.create({id:id('source-edge'),entityId:id('source-relation'),fromEntity:relEntity,type:sources,toEntity:article,position:r.sourcePosition??(r.sourcePosition=Position.generate())}).ops];
const bytes=JSON.stringify(ops,(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('hex')}:v,2)+'\n',sha256=createHash('sha256').update(bytes).digest('hex');
const batch={name:'Add verified teacher-coaching synthesis method and DOI',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/${prefix}-ops.json`,sha256,journalPath:`${root}/${prefix}-publication.json`,validationPath:`${root}/${prefix}-validation.json`,operationCount:ops.length};
writeFileSync(rp,JSON.stringify(r,null,2)+'\n');writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/${prefix}-batch.json`,JSON.stringify(batch,null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),opsHash:sha256,source:'https://annenberg.brown.edu/publications/effect-teacher-coaching-instruction-and-achievement-meta-analysis-causal-evidence',review:'Reuse Health Study category Meta-analysis; alternate same-name Evidence entity is a weaker category match. Article describes synthesis method, not delivery technique. Preserve Article, program, authors and all findings. Original src-023 RCT label rejected.'},null,2)+'\n');console.log(JSON.stringify({operations:ops.length,article,method}));
