import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash, randomUUID } from 'node:crypto';
import { Ops, Position, SystemIds, type Op } from '@geoprotocol/geo-sdk';
import { geoGraphqlRequest as gql } from '../src/geo-api-client';
import { EDUCATION_PUBLICATION as target } from '../src/education-bounty';

const root='data/education',prefix='community-eligibility-provision';
if(existsSync(`${root}/${prefix}-publication.json`))throw Error('Preserve submitted payload.');
const rp=`${root}/${prefix}-registry.json`,r:Record<string,string>=existsSync(rp)?JSON.parse(readFileSync(rp,'utf8')):{},id=(k:string)=>r[k]??(r[k]=randomUUID().replaceAll('-',''));
const p={article:'a2a5ed0cacef46b1835de457956ce915',initiative:'d272f19cef87485fb83e26fb68957395',claim:'96f859efa1ca4b229372c86ad58b694b',factual:'da4a6c1f9d4446f9832ff3b49a4400ef',url:'412ff593e9154012a43d4c27ec5c68b6',source:'49c5d5e1679a4dbdbfd33f618f227c94',related:'dfa6aebe1ca94bf29faccc4cc7afb24c',topics:'806d52bc27e94c9193c057978b093351',topic:'0df9fad9098d4b11bacb9af0f7a79182',estimate:'e500e2585a964d2c9df4a47b199616c3',se:'cc28953bd89e406096c9627021f4713d',unit:'8405509cc7354655a348591349a5f025',entries:'210e9b352b454d6eb7a32906d24d3c8d',locator:'84dacbddca6a44079edb5e11a4c66b40'};
const articleName='The Effect of Free School Meals on Household Food Purchases: Evidence from the Community Eligibility Provision',initiativeName='Community Eligibility Provision',url='https://michellemmarcus.com/wp-content/uploads/2022/06/jhe_final_manuscript.pdf';
const rows=[
 ['any-food-spending','CEP exposure reduced monthly household all-food purchases by $10.65 for households with children.','The post-exposure difference-in-differences estimate is -$10.65 (SE $1.457; N=4,498,537; p<.01). It is a household grocery-purchase result, not a student achievement effect or a program cost.','-10.65','1.457',4498537,'USD difference in monthly all-food purchases for households with children after any CEP exposure.','Table 3 Panel A, column 1.'],
 ['full-exposure-food-spending','A zero-to-100% CEP exposure contrast reduced monthly household all-food purchases by $38.76.','The continuous-exposure estimate is -$38.76 (SE $11.54; N=4,369,278; p<.01). It is an alternate exposure specification from the same study, not an independent replication of the any-exposure result.','-38.76','11.54',4369278,'USD difference in monthly all-food purchases for households with children, zero-to-100% overall CEP exposure contrast.','Table 3 Panel B, column 1.'],
 ['food-insecurity','CEP exposure reduced the study food-insecure-household indicator by 2.11 percentage points.','The state-level post-exposure estimate is -2.11 percentage points (SE 0.581; N=569,293; p<.01), from a 45% reference mean. It is a household food-security outcome, not a claim about academic attainment.','-2.11','0.581',569293,'Percentage-point difference in USDA-defined food-insecure-household indicator for households with children after CEP exposure.','Table 8 Panel A, column 2.'],
] as const;
const checks:string[]=[],ops:Op[]=[];const check=(v:unknown,s:string)=>{if(!v)throw Error(s);checks.push(s)};const decimal=(property:string,value:string)=>{const[whole,fraction='']=value.split('.'),negative=whole.startsWith('-'),digits=`${negative?whole.slice(1):whole}${fraction}`;return{property,type:'decimal' as const,exponent:-fraction.length,mantissa:{type:'i64' as const,value:BigInt(`${negative?'-':''}${digits}`)}}};
for(const [q,t] of [[SystemIds.TYPES_PROPERTY,'Relation'],[p.factual,'Checkbox'],[p.url,'Text'],[p.source,'Relation'],[p.related,'Relation'],[p.topics,'Relation'],[p.estimate,'Decimal'],[p.se,'Decimal'],[p.unit,'Text'],[p.entries,'Integer'],[p.locator,'Text']] as const){const d:any=await gql('query($id:UUID!){property(id:$id){dataTypeName}}',{variables:{id:q}});check(d.property?.dataTypeName===t,`Live ${t}: ${q}`)}
for(const[key,name]of[['article',articleName],['initiative',initiativeName],...rows.map(x=>[`claim/${x[0]}`,x[1]])]as const){const entity=id(key),d:any=await gql('query($id:UUID!,$name:String!){entity(id:$id){spaceIds}entitiesConnection(first:10,filter:{name:{isInsensitive:$name}}){nodes{id}pageInfo{hasNextPage}}}',{variables:{id:entity,name}});check(!d.entity?.spaceIds?.length,`Allocated ID unused: ${key}`);check(!d.entitiesConnection.pageInfo.hasNextPage&&!d.entitiesConnection.nodes.length,`Complete all-space identity discovery: ${key}`)}
const article=id('article'),initiative=id('initiative'),edge=(k:string,f:string,t:string,to:string)=>ops.push(...Ops.relations.create({id:id(`edge/${k}`),entityId:id(`relation/${k}`),fromEntity:f,type:t,toEntity:to,position:r[`position/${k}`]??(r[`position/${k}`]=Position.generate())}).ops);
ops.push(...Ops.entities.update({id:article,name:articleName,description:'A quasi-experimental study of Community Eligibility Provision exposure and household grocery-purchase and food-security outcomes.',values:[{property:p.url,type:'text',value:url}]}).ops);edge('article/type',article,SystemIds.TYPES_PROPERTY,p.article);ops.push(...Ops.entities.update({id:initiative,name:initiativeName,description:'A federal option allowing eligible schools or groups of schools to offer meals at no charge to all students. The linked study evaluates variation in CEP exposure, not an academic-outcome intervention.',values:[{property:p.url,type:'text',value:url}]}).ops);edge('initiative/type',initiative,SystemIds.TYPES_PROPERTY,p.initiative);edge('initiative/source',initiative,p.source,article);edge('initiative/article',initiative,p.related,article);
for(const row of rows){const claim=id(`claim/${row[0]}`);ops.push(...Ops.entities.update({id:claim,name:row[1],description:row[2],values:[{property:p.factual,type:'boolean',value:true},decimal(p.estimate,row[3]),decimal(p.se,row[4]),{property:p.entries,type:'integer',value:BigInt(row[5])},{property:p.unit,type:'text',value:row[6]},{property:p.locator,type:'text',value:row[7]}]}).ops);edge(`${row[0]}/type`,claim,SystemIds.TYPES_PROPERTY,p.claim);edge(`${row[0]}/source`,claim,p.source,article);edge(`${row[0]}/initiative`,claim,p.related,initiative);}
const bytes=JSON.stringify(ops,(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('hex')}:typeof v==='bigint'?{$bigint:v.toString()}:v,2)+'\n',sha256=createHash('sha256').update(bytes).digest('hex'),batch={name:'Add Community Eligibility Provision household-resource evidence',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/${prefix}-ops.json`,sha256,journalPath:`${root}/${prefix}-publication.json`,validationPath:`${root}/${prefix}-validation.json`,entities:{article,initiative,claims:Object.fromEntries(rows.map(row=>[row[0],id(`claim/${row[0]}`)]))},operationCount:ops.length};writeFileSync(rp,JSON.stringify(r,null,2)+'\n');writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/${prefix}-batch.json`,JSON.stringify(batch,null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),opsHash:sha256,checks,source:'Marcus and Yewell, author-hosted final manuscript; Tables 3 and 8.',transcription:'Reported coefficients, standard errors, sample sizes, and table locators transcribed from the manuscript; no values are locally calculated.',scope:'Household grocery-purchase and food-security evidence only. Alternate CEP exposure specifications are distinct estimates from one study, not independent studies.'},null,2)+'\n');console.log(JSON.stringify(batch,null,2));
