import {existsSync,readFileSync,writeFileSync} from 'node:fs';
import {createHash,randomUUID} from 'node:crypto';
import {Ops,Position,SystemIds,type Op} from '@geoprotocol/geo-sdk';
import {geoGraphqlRequest as gql} from '../src/geo-api-client';
import {EDUCATION_PUBLICATION as target} from '../src/education-bounty';

const root='data/education',registryPath=`${root}/head-start-registry.json`,registry:Record<string,string>=existsSync(registryPath)?JSON.parse(readFileSync(registryPath,'utf8')):{};
const id=(key:string)=>registry[key]??(registry[key]=randomUUID().replaceAll('-',''));
const p={article:'a2a5ed0cacef46b1835de457956ce915',claim:'96f859efa1ca4b229372c86ad58b694b',factual:'da4a6c1f9d4446f9832ff3b49a4400ef',url:'412ff593e9154012a43d4c27ec5c68b6',source:'49c5d5e1679a4dbdbfd33f618f227c94',related:'dfa6aebe1ca94bf29faccc4cc7afb24c',supports:'1dc6a843458848198e7a6e672268f811',opposes:'4e6ec5d14292498a84e5f607ca1a08ce',topics:'806d52bc27e94c9193c057978b093351',topic:'0df9fad9098d4b11bacb9af0f7a79182'};
const check=(ok:unknown,label:string,checks:string[])=>{if(!ok)throw Error(label);checks.push(label)};
const ops:Op[]=[],checks:string[]=[],edges:any[]=[];
const rel=(key:string,from:string,type:string,to:string)=>{const position=registry[`position/${key}`]??(registry[`position/${key}`]=Position.generate());ops.push(...Ops.relations.create({id:id(`edge/${key}`),entityId:id(`edge-entity/${key}`),fromEntity:from,type,toEntity:to,position}).ops);edges.push({from,type,to});};
const reportName='Third Grade Follow-up to the Head Start Impact Study: Final Report';
const discovery=JSON.parse(readFileSync(`${root}/discovery/third-grade-follow-up-to-the-head-start-impact-study-final-report.json`,'utf8'));
const contains=JSON.parse(readFileSync(`${root}/discovery/contains-third-grade-follow-up-to-the-head-start-impact-study.json`,'utf8'));
check(discovery.complete&&discovery.nodes.length===0,'Complete all-space exact follow-up report discovery found no candidate',checks);check(contains.complete&&contains.nodes.length===0,'Complete all-space substring follow-up report discovery found no candidate',checks);
for(const [property,type] of [[SystemIds.TYPES_PROPERTY,'Relation'],[p.source,'Relation'],[p.related,'Relation'],[p.supports,'Relation'],[p.opposes,'Relation'],[p.topics,'Relation'],[p.factual,'Checkbox'],[p.url,'Text']]){const d:any=await gql('query($id:UUID!){property(id:$id){dataTypeName}}',{variables:{id:property}});check(d.property?.dataTypeName===type,`Live property type ${property}`,checks);}
const original=registry.article,initiative=registry.initiative,debate=registry['claim/expansion-debate'],article=id('article/third-grade-followup');
check(!!original&&!!initiative&&!!debate,'Published Head Start source, initiative and debate IDs are available',checks);
for(const entityId of [article,...['preschool-and-elementary','language-literacy-third-grade','social-emotional-qualification'].map(k=>id(`claim/third-grade/${k}`))]){const found:any=await gql('query($id:UUID!){entity(id:$id){spaceIds}}',{variables:{id:entityId}});check(!found.entity?.spaceIds?.length,`Persistent ID is unoccupied: ${entityId}`,checks);}
ops.push(...Ops.entities.update({id:article,name:reportName,description:'The 2012 federal follow-up of the Head Start randomized study, reporting outcomes through the end of third grade.',values:[{property:p.url,type:'text',value:'https://acf.gov/sites/default/files/documents/opre/head_start_report_0.pdf'}]}).ops);rel('third-grade/article/type',article,SystemIds.TYPES_PROPERTY,p.article);rel('third-grade/article/prior-report',article,p.related,original);
const findings=[
 {key:'preschool-and-elementary',name:'The third-grade Head Start follow-up found improved preschool outcomes across developmental domains but few impacts from kindergarten through third grade.',description:'The report summarizes the randomized access comparison over the full study period. “Few impacts” does not mean every outcome or subgroup was unchanged, and the comparison group had access to other care arrangements.',role:'opposes'},
 {key:'language-literacy-third-grade',name:'The third-grade Head Start follow-up reports that modest early language and literacy effects left one impact in each age cohort by the end of third grade.',description:'This source-specific follow-up statement preserves the report’s cohort structure and its distinction between early effects and third-grade measurement. It is not a claim about unmeasured later-life outcomes.',role:'opposes'},
 {key:'social-emotional-qualification',name:'The third-grade Head Start follow-up found that social-emotional results differed by age cohort and by whether parents, teachers or children reported them.',description:'The report describes favorable and unfavorable findings for different reporters and cohorts. Do not aggregate these into one universal social-emotional effect or treat reporter differences as a contradiction without outcome-level review.',role:'related'}
];
for(const row of findings){const claim=id(`claim/third-grade/${row.key}`);ops.push(...Ops.entities.update({id:claim,name:row.name,description:row.description,values:[{property:p.factual,type:'boolean',value:true}]}).ops);rel(`third-grade/${row.key}/type`,claim,SystemIds.TYPES_PROPERTY,p.claim);rel(`third-grade/${row.key}/source`,claim,p.source,article);rel(`third-grade/${row.key}/initiative`,claim,p.related,initiative);rel(`third-grade/${row.key}/topic`,claim,p.topics,p.topic);if(row.role==='opposes')rel(`third-grade/${row.key}/opposes`,claim,p.opposes,debate);else rel(`third-grade/${row.key}/debate`,claim,p.related,debate);}
const bytes=JSON.stringify(ops,(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('hex')}:typeof v==='bigint'?{$bigint:v.toString()}:v,2)+'\n',sha256=createHash('sha256').update(bytes).digest('hex');
const batch={name:'Add Head Start third-grade follow-up evidence',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/head-start-third-grade-ops.json`,sha256,journalPath:`${root}/head-start-third-grade-publication.json`,validationPath:`${root}/head-start-third-grade-validation.json`,entities:{article,findings:Object.fromEntries(findings.map(x=>[x.key,id(`claim/third-grade/${x.key}`)]))},operationCount:ops.length};
writeFileSync(registryPath,JSON.stringify(registry,null,2)+'\n');writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/head-start-third-grade-batch.json`,JSON.stringify(batch,null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),opsHash:sha256,checks,edges,source:{title:reportName,publisher:'Administration for Children and Families / OPRE',year:2012,url:'https://acf.gov/sites/default/files/documents/opre/head_start_report_0.pdf',design:'Follow-up of the national Head Start randomized access study through third grade',limits:'Claims preserve cohort and reporter differences; this report does not establish all later-life impacts or provide a no-service counterfactual.'}},null,2)+'\n');console.log(JSON.stringify(batch,null,2));
