import {existsSync,readFileSync,writeFileSync} from 'node:fs';
import {createHash,randomUUID} from 'node:crypto';
import {Ops,SystemIds,type Op} from '@geoprotocol/geo-sdk';
import {geoGraphqlRequest as gql} from '../src/geo-api-client';
import {EDUCATION_PUBLICATION as target} from '../src/education-bounty';
const root='data/education',prefix='star-return-claim-copy';
if(existsSync(`${root}/${prefix}-publication.json`))throw Error('Preserve submitted payload.');
const registry=JSON.parse(readFileSync(`${root}/star-returns-registry.json`,'utf8')) as Record<string,string>;
const source=JSON.parse(readFileSync(`${root}/star-economic-extraction.json`,'utf8'));
const economic=JSON.parse(readFileSync(`${root}/star-economic-registry.json`,'utf8')) as Record<string,string>;
const p={claim:'96f859efa1ca4b229372c86ad58b694b',factual:'da4a6c1f9d4446f9832ff3b49a4400ef',source:'49c5d5e1679a4dbdbfd33f618f227c94',irr:economic['property/irr'],growth:economic['property/growth']};
const repairs=source.internalRatesOfReturn.map((row:any)=>{const pct=row.realAnnualIRR*100,growth=row.annualWageGrowth*100,id=registry[`return/${row.annualWageGrowth}`];return {id,old:`STAR modeled real return: ${growth}% annual wage growth`,name:`STAR's modeled real annual internal return is ${pct}% when assumed real wage growth is ${growth}%.`,description:`This author-modeled class-size calculation projects earnings over ages ${source.context.earningsAgeStart}–${source.context.earningsAgeEnd}; it is not an observed investment return or a confidence bound.`,irr:row.realAnnualIRR,growth:row.annualWageGrowth};});
const checks:string[]=[],ops:Op[]=[];const check=(ok:unknown,label:string)=>{if(!ok)throw Error(label);checks.push(label);};
for(const [property,type] of [[p.factual,'Checkbox'],[p.irr,'Decimal'],[p.growth,'Decimal'],[p.source,'Relation'],[SystemIds.TYPES_PROPERTY,'Relation']] as const){const d:any=await gql('query($id:UUID!){property(id:$id){dataTypeName}}',{variables:{id:property}});check(d.property?.dataTypeName===type,`Live ${type} property ${property}`);}
for(const row of repairs){const d:any=await gql('query($id:UUID!,$space:UUID!){entity(id:$id){types{id}values(first:30,filter:{spaceId:{is:$space}}){nodes{propertyId text decimal boolean}pageInfo{hasNextPage}}relations(first:30,filter:{spaceId:{is:$space}}){nodes{typeId toEntityId}pageInfo{hasNextPage}}}}',{variables:{id:row.id,space:target.spaceId}});check(d.entity?.types.some((t:any)=>t.id===p.claim),`Claim type ${row.id}`);check(!d.entity.values.pageInfo.hasNextPage&&!d.entity.relations.pageInfo.hasNextPage,`Complete read ${row.id}`);check(d.entity.values.nodes.some((v:any)=>v.propertyId===SystemIds.NAME_PROPERTY&&v.text===row.old),`Reviewed current title ${row.id}`);check(d.entity.values.nodes.some((v:any)=>v.propertyId===p.irr&&Number(v.decimal)===row.irr),`IRR preserved ${row.id}`);check(d.entity.values.nodes.some((v:any)=>v.propertyId===p.growth&&Number(v.decimal)===row.growth),`Growth preserved ${row.id}`);check(d.entity.relations.nodes.some((x:any)=>x.typeId===p.source),`Source preserved ${row.id}`);ops.push(...Ops.entities.update({id:row.id,name:row.name,description:row.description,values:[{property:p.factual,type:'boolean',value:true}]}).ops);}
const bytes=JSON.stringify(ops,(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('hex')}:typeof v==='bigint'?{$bigint:v.toString()}:v,2)+'\n';const sha256=createHash('sha256').update(bytes).digest('hex');const batch={name:'Repair STAR modeled-return Claims with actual estimates',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/${prefix}-ops.json`,sha256,journalPath:`${root}/${prefix}-publication.json`,validationPath:`${root}/${prefix}-validation.json`,repairs,operationCount:ops.length};writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/${prefix}-batch.json`,JSON.stringify(batch,null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),checks,opsHash:sha256,repairs},null,2)+'\n');console.log(JSON.stringify(batch,null,2));
