import {readFileSync,writeFileSync} from 'node:fs';
import {geoGraphqlRequest as gql} from '../src/geo-api-client';
const root='data/education',read=(n:string)=>JSON.parse(readFileSync(`${root}/${n}.json`,'utf8'));
const batchArg=process.argv.indexOf('--batch'),batchPath=batchArg>=0?process.argv[batchArg+1]:undefined;
if(batchArg>=0&&(!batchPath||!/^data\/education\/[a-z0-9-]+-batch\.json$/.test(batchPath)))throw Error('Expected --batch data/education/<key>-batch.json');
const prefix=batchPath?batchPath.slice(root.length+1,-'-batch.json'.length):process.argv.includes('--head-start')?'head-start-collection':'coaching-collection',batch=read(`${prefix}-batch`),before=prefix==='head-start-collection'?read('head-start-collection-review').claims:read(`${prefix}-before`),checks:string[]=[],space=batch.spaceId;
const check=(ok:unknown,message:string)=>{if(!ok)throw Error(message);checks.push(message);};let pages=0;
for(const g of batch.groups){const members:any[]=[];let after:string|null=null;const seen=new Set<string>();do{const d:any=await gql('query($id:UUID!,$space:UUID!,$after:Cursor){entity(id:$id){relations(first:2,after:$after,filter:{spaceId:{is:$space},typeId:{is:"a99f9ce12ffa4dac8c61f6310d46064a"}}){nodes{toEntityId position}pageInfo{hasNextPage endCursor}}}}',{variables:{id:g.blockId,space,after}});const p=d.entity.relations;pages++;members.push(...p.nodes);if(!p.pageInfo.hasNextPage)break;check(p.pageInfo.endCursor&&!seen.has(p.pageInfo.endCursor),'Member cursor advances');after=p.pageInfo.endCursor;seen.add(after!);}while(true);members.sort((a,b)=>a.position<b.position?-1:1);check(JSON.stringify(members.map(m=>m.toEntityId))===JSON.stringify(g.memberIds),`${g.key} exact member order`);}
const norm=(rows:any[])=>JSON.stringify(rows.map(r=>JSON.stringify(r)).sort());
for(const b of before){const d:any=await gql('query($id:UUID!,$space:UUID!){entity(id:$id){values(first:25,filter:{spaceId:{is:$space}}){nodes{propertyId text decimal integer boolean}pageInfo{hasNextPage}}relations(first:30,filter:{spaceId:{is:$space}}){nodes{id entityId typeId toEntityId position}pageInfo{hasNextPage}}}}',{variables:{id:b.id,space}});check(d.entity&&!d.entity.values.pageInfo.hasNextPage&&!d.entity.relations.pageInfo.hasNextPage,'Reused Claim complete');const expected=structuredClone(b.values.nodes);if(batch.estimandAdditions?.includes(b.id))expected.push({propertyId:'ba643714da274c37a340a7f8396198dc',text:'Intention to treat (ITT)',decimal:null,integer:null,boolean:null});const unit=batch.unitCorrections?.find((c:any)=>c.id===b.id);if(unit)expected.find((v:any)=>v.propertyId==='8405509cc7354655a348591349a5f025').text=unit.unit;check(norm(d.entity.values.nodes)===norm(expected),`Existing scalar facts preserved except enumerated metadata ${b.id}`);check(norm(d.entity.relations.nodes)===norm(b.relations.nodes),`All existing outgoing relationships unchanged ${b.id}`);}
const catalog:any=await gql('query($space:UUID!,$id:UUID!,$catalog:UUID!){relationsConnection(first:10,filter:{spaceId:{is:$space},fromEntityId:{is:$catalog},typeId:{is:"a99f9ce12ffa4dac8c61f6310d46064a"},toEntityId:{is:$id}}){nodes{id position}pageInfo{hasNextPage}}}',{variables:{space,id:batch.datasetId,catalog:batch.catalogId??'2279edef1bbe479c872caeb72ee90022'}});check(!catalog.relationsConnection.pageInfo.hasNextPage&&catalog.relationsConnection.nodes.length===1,'Exactly one catalog membership');
writeFileSync(`${root}/${prefix}-query-verification.json`,JSON.stringify({checkedAt:new Date().toISOString(),passed:true,pages,inspectedClaims:before.length,checks,scope:'Ordered tables, original scalar/outgoing facts preserved except explicitly enumerated metadata changes, unique catalog membership; source accuracy reviewed separately'},null,2)+'\n');console.log(JSON.stringify({passed:true,pages,inspectedClaims:before.length,checks:checks.length}));
