import {writeFileSync} from 'node:fs';
import {geoGraphqlRequest as gql} from '../src/geo-api-client';
const space='dac259bad48a11adf97fe36857d85206',datasetType='0c4babfb43893486af827341bbf32e09',report:any={checkedAt:new Date().toISOString(),space,complete:false,datasets:[],parents:[],blocks:[]};
async function pages(query:string,variables:any,key:string){const nodes:any[]=[];let after:string|null=null;const seen=new Set<string>();do{const d:any=await gql(query,{variables:{...variables,after}}),p=key==='relations'?d.entity?.relations:d[key];if(!p)throw Error('Missing inventory connection');nodes.push(...p.nodes);if(!p.pageInfo.hasNextPage)break;if(!p.pageInfo.endCursor||seen.has(p.pageInfo.endCursor))throw Error('Incomplete inventory');after=p.pageInfo.endCursor;seen.add(after!);}while(true);return nodes;}
report.datasets=await pages('query($space:UUID!,$after:Cursor){relationsConnection(first:20,after:$after,filter:{spaceId:{is:$space},typeId:{is:"8f151ba4de204e3c9cb499ddf96f48f1"},toEntityId:{is:"0c4babfb43893486af827341bbf32e09"}}){nodes{fromEntity{id name description}}pageInfo{hasNextPage endCursor}}}',{space},'relationsConnection');
const parents=[...new Set(['16a032fb91794444859a6c1a44a32955',...report.datasets.map((d:any)=>d.fromEntity.id)])];
const blocks=new Set<string>();
for(const id of parents){const nodes=await pages('query($id:UUID!,$space:UUID!,$after:Cursor){entity(id:$id){relations(first:20,after:$after,filter:{spaceId:{is:$space},typeId:{is:"beaba5cba67741a8b35377030613fc70"}}){nodes{id entityId toEntityId position toEntity{id name types{id name}}}pageInfo{hasNextPage endCursor}}}}',{id,space},'relations');report.parents.push({id,blocks:nodes});for(const b of nodes)if(b.toEntity.types.some((t:any)=>t.id==='b8803a8665de412bbb357e0c84adf473'))blocks.add(b.toEntityId);}
for(const id of blocks){const relations=await pages('query($id:UUID!,$space:UUID!,$after:Cursor){entity(id:$id){relations(first:20,after:$after,filter:{spaceId:{is:$space}}){nodes{id entityId typeId toEntityId position toEntity{name types{id name}}}pageInfo{hasNextPage endCursor}}}}',{id,space},'relations');report.blocks.push({id,relations});}
report.incomingMembership=[];
for(const d of report.datasets){const memberships=await pages('query($id:UUID!,$after:Cursor){relationsConnection(first:20,after:$after,filter:{typeId:{is:"a99f9ce12ffa4dac8c61f6310d46064a"},toEntityId:{is:$id}}){nodes{id fromEntityId spaceId fromEntity{name}}pageInfo{hasNextPage endCursor}}}',{id:d.fromEntity.id},'relationsConnection');if(memberships.length)report.incomingMembership.push({datasetId:d.fromEntity.id,memberships});}
report.complete=true;writeFileSync('data/education/catalog-collection-inventory.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({datasets:report.datasets.length,parents:report.parents.length,blocks:report.blocks.length,spacePage:report.parents[0],incomingMembership:report.incomingMembership,catalogCandidates:report.blocks.filter((b:any)=>b.relations.some((r:any)=>r.typeId==='a99f9ce12ffa4dac8c61f6310d46064a'&&r.toEntity.types.some((t:any)=>t.id===datasetType))).map((b:any)=>({id:b.id,datasetMembers:b.relations.filter((r:any)=>r.typeId==='a99f9ce12ffa4dac8c61f6310d46064a'&&r.toEntity.types.some((t:any)=>t.id===datasetType))}))},null,2));
