import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash, randomUUID } from 'node:crypto';
import { Ops, Position, SystemIds, type Op } from '@geoprotocol/geo-sdk';
import { geoGraphqlRequest as gql } from '../src/geo-api-client';
import { EDUCATION_PUBLICATION as target } from '../src/education-bounty';
const root='data/education',prefix='abecedarian-age30-expanded'; if(existsSync(`${root}/${prefix}-publication.json`))throw Error('Preserve submitted payload.');
const rp=`${root}/${prefix}-registry.json`,r:Record<string,string>=existsSync(rp)?JSON.parse(readFileSync(rp,'utf8')):{},id=(k:string)=>r[k]??(r[k]=randomUUID().replaceAll('-',''));
const p={claim:'96f859efa1ca4b229372c86ad58b694b',factual:'da4a6c1f9d4446f9832ff3b49a4400ef',source:'49c5d5e1679a4dbdbfd33f618f227c94',related:'dfa6aebe1ca94bf29faccc4cc7afb24c',support:'1dc6a843458848198e7a6e672268f811',oppose:'4e6ec5d14292498a84e5f607ca1a08ce',estimate:'e500e2585a964d2c9df4a47b199616c3',unit:'8405509cc7354655a348591349a5f025'};
const article='a72a792642aa46b497587313102bfe39',study='66657d9776214aec9cf816b8d50b644a',parent='58caa8fd523742978fa07d54722d918a',checks:string[]=[],ops:Op[]=[]; const check=(v:unknown,s:string)=>{if(!v)throw Error(s);checks.push(s)};
const dec=(v:string)=>{const [w,f='']=v.split('.'),n=w.startsWith('-'),d=`${n?w.slice(1):w}${f}`;return {property:p.estimate,type:'decimal' as const,exponent:-f.length,mantissa:{type:'i64' as const,value:BigInt(`${n?'-':''}${d}`)}}};
const rows=[
 ['hs-credential','At age 30, 88.46% of ABC-treated participants versus 81.63% of controls had a high-school diploma or GED.','The difference was not statistically significant (OR 1.73; 95% CI 0.57–5.27; p=.34) in the 52-treated/49-control ABC follow-up. This is a secondary education outcome, not a separate trial or evidence of a degree effect.','1.73','Odds ratio for high-school diploma or GED at age 30, ABC treatment versus control; source-reported.','Table 3; HS grad/GED; p. 1038.','oppose'],
 ['public-aid','At age 30, 3.85% of ABC-treated participants versus 20.41% of controls used public aid at least 10% of the observed window.','The source reports OR 0.16 (95% CI 0.03–0.75; p=.02) for this ABC randomized-treatment comparison. It is a threshold for administrative welfare use, not a measured income or lifetime benefit.','0.16','Odds ratio for public-aid use at least 10% of the observed window at age 30, ABC treatment versus control; source-reported.','Table 4; Used public aid ≥10% time frame; p. 1039.','support'],
 ['first-parity','At age 30, ABC-treated participants had their first parity 1.83 years later on average than controls (21.78 versus 19.95 years).','The source reports d=0.52 (95% CI 0.19–3.45; p=.03) in the 52-treated/49-control follow-up. This is a secondary family-demographic outcome, not a measure of educational attainment or employment.','0.52','Cohen’s d for age at first parity at age 30, ABC treatment versus control; source-reported standardized effect.','Table 5; Age at first parity; p. 1040.','support'],
 ['criminal-conviction','At age 30, ABC treatment did not produce a statistically significant difference in criminal conviction (27.45% versus 28.57%).','The source reports OR 0.95 (95% CI 0.40–2.27; p=.90) in the 52-treated/49-control follow-up. This does not establish no crime effect; it is one self-reported age-30 outcome in a small historical trial.','0.95','Odds ratio for criminal conviction at age 30, ABC treatment versus control; source-reported.','Table 5; Criminal conviction; p. 1040.','oppose'],
] as const;
for(const [q,t] of [[SystemIds.TYPES_PROPERTY,'Relation'],[p.factual,'Checkbox'],[p.source,'Relation'],[p.related,'Relation'],[p.support,'Relation'],[p.oppose,'Relation'],[p.estimate,'Decimal'],[p.unit,'Text']] as const){const x:any=await gql('query($id:UUID!){property(id:$id){dataTypeName}}',{variables:{id:q}});check(x.property?.dataTypeName===t,`Live ${t}: ${q}`)}
for(const row of rows){const [key,name]=row,exist:any=await gql('query($name:String!){entitiesConnection(first:10,filter:{name:{isInsensitive:$name}}){nodes{id}pageInfo{hasNextPage}}}',{variables:{name}});check(!exist.entitiesConnection.nodes.length&&!exist.entitiesConnection.pageInfo.hasNextPage,`Complete all-space exact-name discovery: ${key}`);const claim=id(`claim/${key}`),occ:any=await gql('query($id:UUID!){entity(id:$id){spaceIds}}',{variables:{id:claim}});check(!occ.entity?.spaceIds?.length,`Persistent Claim ID unused: ${key}`)}
const edge=(k:string,f:string,t:string,to:string)=>ops.push(...Ops.relations.create({id:id(`edge/${k}`),entityId:id(`relation/${k}`),fromEntity:f,type:t,toEntity:to,position:r[`position/${k}`]??(r[`position/${k}`]=Position.generate())}).ops);
for(const [key,name,description,effect,unit,locator,direction] of rows){const claim=id(`claim/${key}`);ops.push(...Ops.entities.update({id:claim,name,description,values:[{property:p.factual,type:'boolean',value:true},dec(effect),{property:p.unit,type:'text',value:unit}]}).ops);edge(`${key}/type`,claim,SystemIds.TYPES_PROPERTY,p.claim);edge(`${key}/source`,claim,p.source,article);edge(`${key}/study`,claim,p.related,study);edge(`${key}/parent`,parent,p.related,claim);edge(`${key}/parent-reverse`,claim,p.related,parent);edge(`${key}/${direction}`,parent,direction==='support'?p.support:p.oppose,claim)}
const bytes=JSON.stringify(ops,(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('hex')}:typeof v==='bigint'?{$bigint:v.toString()}:v,2)+'\n',sha256=createHash('sha256').update(bytes).digest('hex'),batch={name:'Add four Abecedarian age-30 findings and debate links',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/${prefix}-ops.json`,sha256,journalPath:`${root}/${prefix}-publication.json`,validationPath:`${root}/${prefix}-validation.json`,entities:{article,study,parent,claims:Object.fromEntries(rows.map(x=>[x[0],id(`claim/${x[0]}`)]))},operationCount:ops.length};writeFileSync(rp,JSON.stringify(r,null,2)+'\n');writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/${prefix}-batch.json`,JSON.stringify(batch,null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),opsHash:sha256,checks,source:'Campbell et al. 2012, PMCID PMC3989926, Tables 3–5.',scope:'Four ABC-only age-30 source findings and linked policy evidence; no earnings price-year, raw data, benefit-cost ratio, or second-trial assertion.'},null,2)+'\n');console.log(JSON.stringify({batch,checks},null,2));
