import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash, randomUUID } from 'node:crypto';
import { Ops, Position, SystemIds, type Op } from '@geoprotocol/geo-sdk';
import { geoGraphqlRequest as gql } from '../src/geo-api-client';
import { EDUCATION_PUBLICATION as target } from '../src/education-bounty';
const root='data/education',prefix='youth-challenge-components';if(existsSync(`${root}/${prefix}-publication.json`))throw Error('Preserve submitted payload.');
const rp=`${root}/${prefix}-registry.json`,r:Record<string,string>=existsSync(rp)?JSON.parse(readFileSync(rp,'utf8')):{},id=(k:string)=>r[k]??(r[k]=randomUUID().replaceAll('-',''));
const p={claim:'96f859efa1ca4b229372c86ad58b694b',factual:'da4a6c1f9d4446f9832ff3b49a4400ef',source:'49c5d5e1679a4dbdbfd33f618f227c94',related:'dfa6aebe1ca94bf29faccc4cc7afb24c',cost:'6ba2ce00db064687b108aa8449672886',year:'97e14050fc49467bb3aaf4d7eccbbb69',currency:'6e7371ca96cb44348f16932f77f55e75',denom:'3a558d71454745a992c035040f648729'};const article='4abdb70198d949288df61d50f0b458cc',initiative='c52c01e8bab14e64b56b8ceb7c244da5';
const rows=[
 ['opportunity-cost','RAND modeled $2,058 in opportunity costs per Youth ChalleNGe admittee.','This Table 5.1 baseline cost values participant and mentor time net of in-kind benefits. It is a 2010-dollar modeled societal cost, not an operating invoice.','2058'],
 ['cost-tax-deadweight','RAND modeled $1,745 in tax-deadweight cost per Youth ChalleNGe admittee.','This baseline cost applies the report’s 15% tax-deadweight assumption. It is a modeled 2010-dollar societal cost, not a direct program payment.','1745'],
 ['lifetime-earnings','RAND modeled $43,514 in lifetime-earnings benefits per Youth ChalleNGe admittee.','This Table 5.1 component projects lifetime earnings under the baseline model and is not observed three-year earnings. It is expressed in 2010 dollars per admittee.','43514'],
 ['education-cost','RAND modeled a $4,860 education-cost offset per Youth ChalleNGe admittee.','Table 5.1 subtracts this 2010-dollar modeled education cost from benefits in the baseline societal model. It is not a program operating cost or a participant tuition bill.','-4860'],
 ['welfare-admin','RAND modeled $249 in social-welfare administrative benefits per Youth ChalleNGe admittee.','This is a baseline 2010-dollar modeled societal component, separate from cash transfers. It is not a directly observed three-year outcome.','249'],
 ['crime','RAND modeled $662 in criminal-activity benefits per Youth ChalleNGe admittee.','This is a baseline 2010-dollar modeled societal component informed by the report’s short-run criminal-activity evidence. It is not a lifetime observed crime outcome.','662'],
 ['service','RAND modeled $423 in service-to-the-community benefits per Youth ChalleNGe admittee.','This baseline 2010-dollar societal component values service during the residential phase. It is not an earnings or educational-attainment estimate.','423'],
 ['benefit-tax-deadweight','RAND modeled $997 in tax-deadweight benefit per Youth ChalleNGe admittee.','This baseline component reflects the report’s 15% tax-deadweight assumption on benefit-side fiscal effects. It is a modeled 2010-dollar societal amount, not a payment to an admittee.','997'],
] as const;const checks:string[]=[],ops:Op[]=[];const check=(v:unknown,s:string)=>{if(!v)throw Error(s);checks.push(s)};
for(const[q,t]of[[SystemIds.TYPES_PROPERTY,'Relation'],[p.factual,'Checkbox'],[p.source,'Relation'],[p.related,'Relation'],[p.cost,'Decimal'],[p.year,'Integer'],[p.currency,'Text'],[p.denom,'Text']]as const){const d:any=await gql('query($id:UUID!){property(id:$id){dataTypeName}}',{variables:{id:q}});check(d.property?.dataTypeName===t,`Live ${t}: ${q}`)}
for(const row of rows){const name=row[1],claim=id(`claim/${row[0]}`),d:any=await gql('query($id:UUID!,$name:String!){entity(id:$id){spaceIds}entitiesConnection(first:10,filter:{name:{isInsensitive:$name}}){nodes{id}pageInfo{hasNextPage}}}',{variables:{id:claim,name}});check(!d.entity?.spaceIds?.length,`Allocated ID unused: ${row[0]}`);check(!d.entitiesConnection.pageInfo.hasNextPage&&!d.entitiesConnection.nodes.length,`Complete all-space name discovery: ${row[0]}`)}
const source:any=await gql('query($article:UUID!,$initiative:UUID!){article:entity(id:$article){spaceIds}initiative:entity(id:$initiative){spaceIds}}',{variables:{article,initiative}});check(source.article?.spaceIds?.includes(target.spaceId),'RAND Article remains in destination');check(source.initiative?.spaceIds?.includes(target.spaceId),'Initiative remains in destination');
const edge=(k:string,f:string,t:string,to:string)=>ops.push(...Ops.relations.create({id:id(`edge/${k}`),entityId:id(`relation/${k}`),fromEntity:f,type:t,toEntity:to,position:r[`position/${k}`]??(r[`position/${k}`]=Position.generate())}).ops);
for(const row of rows){const claim=id(`claim/${row[0]}`),amount=BigInt(row[3]);ops.push(...Ops.entities.update({id:claim,name:row[1],description:row[2],values:[{property:p.factual,type:'boolean',value:true},{property:p.cost,type:'decimal',exponent:0,mantissa:{type:'i64',value:amount}},{property:p.year,type:'integer',value:2010n},{property:p.currency,type:'text',value:'USD'},{property:p.denom,type:'text',value:'Modeled baseline societal amount per admitted cadet across the ten evaluation sites.'}]}).ops);edge(`${row[0]}/type`,claim,SystemIds.TYPES_PROPERTY,p.claim);edge(`${row[0]}/source`,claim,p.source,article);edge(`${row[0]}/initiative`,claim,p.related,initiative)}
const bytes=JSON.stringify(ops,(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('hex')}:typeof v==='bigint'?{$bigint:v.toString()}:v,2)+'\n',sha256=createHash('sha256').update(bytes).digest('hex'),batch={name:'Add Youth ChalleNGe baseline modeled cost-benefit components',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/${prefix}-ops.json`,sha256,journalPath:`${root}/${prefix}-publication.json`,validationPath:`${root}/${prefix}-validation.json`,entities:{claims:Object.fromEntries(rows.map(row=>[row[0],id(`claim/${row[0]}`)])),article,initiative},operationCount:ops.length};writeFileSync(rp,JSON.stringify(r,null,2)+'\n');writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/${prefix}-batch.json`,JSON.stringify(batch,null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),opsHash:sha256,checks,source:'RAND TR-1193 Table 5.1, baseline cost-benefit comparison, p.32; ERIC ED529935.',scope:'Eight individually labeled modeled 2010-dollar baseline components. They reconcile to the report’s published totals but are not local recomputations or observed outcomes.'},null,2)+'\n');console.log(JSON.stringify(batch,null,2));
