import { createHash, randomUUID } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { Ops, Position, SystemIds, type Op } from '@geoprotocol/geo-sdk';
import { geoGraphqlRequest as gql } from '../src/geo-api-client';
import { EDUCATION_PUBLICATION as target } from '../src/education-bounty';
const root='data/education',prefix='head-start-third-grade-social-emotional';if(existsSync(`${root}/${prefix}-publication.json`))throw Error('Preserve submitted payload.');
const rp=`${root}/${prefix}-registry.json`,r:Record<string,string>=existsSync(rp)?JSON.parse(readFileSync(rp,'utf8')):{},id=(k:string)=>r[k]??(r[k]=randomUUID().replaceAll('-',''));
const p={claim:'96f859efa1ca4b229372c86ad58b694b',factual:'da4a6c1f9d4446f9832ff3b49a4400ef',source:'49c5d5e1679a4dbdbfd33f618f227c94',related:'dfa6aebe1ca94bf29faccc4cc7afb24c',estimate:'e500e2585a964d2c9df4a47b199616c3',unit:'8405509cc7354655a348591349a5f025',locator:'84dacbddca6a44079edb5e11a4c66b40',pvalue:'ba5f8fe9d1cd9a6094338d2f37b74a5e'};
const article='c183f28d3bc34439b797138e50d5c1f3',initiative=JSON.parse(readFileSync(`${root}/head-start-registry.json`,'utf8')).initiative;
const rows=[
 ['four-parent-aggression','For children entering Head Start at age four, parents reported a -0.23 third-grade aggressive-behavior ITT impact (p = .043).','Lower scores indicate fewer behavior problems on this parent-reported measure. The favorable result is one social-emotional finding and does not resolve the conflicting teacher and child reports.','-.23','Regression-adjusted parent-reported aggressive-behavior ITT difference at third grade, Head Start access minus control; 4-year-old cohort; lower is more favorable.','Exhibit 4.3, printed p. 81.','P = .043'],
 ['four-teacher-emotional','For children entering Head Start at age four, teachers reported a -0.06 impact on being in the normal category for emotional symptoms (p = .005).','Lower probability of the normal category is unfavorable on this teacher-reported measure. The result conflicts with the favorable parent-reported aggression finding and must remain reporter-specific.','-.06','Regression-adjusted teacher-reported probability difference (fraction scale), ITT, for the normal emotional-symptoms category at third grade; 4-year-old cohort; lower is less favorable.','Exhibit 4.3, printed p. 81.','P = .005'],
 ['four-child-peer','For children entering Head Start at age four, children self-reported a -0.14 peer-relations impact at third grade (p = .020).','Lower scores indicate worse peer relations on this child-reported standardized measure. It is not interchangeable with parent or teacher reports.','-.14','Regression-adjusted child-reported peer-relations ITT difference at third grade, Head Start access minus control; 4-year-old cohort; lower is less favorable.','Exhibit 4.3 continued, printed p. 82.','P = .020'],
 ['three-parent-social-skills','For children entering Head Start at age three, parents reported a +0.24 social-skills-and-positive-approaches impact at third grade (p = .025).','Higher scores are more favorable on this parent-reported measure. This is the only statistically significant social-emotional impact highlighted for the 3-year-old cohort.','.24','Regression-adjusted parent-reported social-skills-and-positive-approaches-to-learning ITT difference at third grade, Head Start access minus control; 3-year-old cohort; higher is more favorable.','Exhibit 4.4, printed p. 83.','P = .025']
] as const;
const dec=(value:string)=>{const[a,b='']=value.split('.'),neg=a.startsWith('-'),digits=`${neg?a.slice(1):a}${b}`;return{property:p.estimate,type:'decimal'as const,exponent:-b.length,mantissa:{type:'i64'as const,value:BigInt(`${neg?'-':''}${digits}`)}}};const checks:string[]=[],ops:Op[]=[];
for(const[q,t]of[[SystemIds.TYPES_PROPERTY,'Relation'],[p.factual,'Checkbox'],[p.source,'Relation'],[p.related,'Relation'],[p.estimate,'Decimal'],[p.unit,'Text'],[p.locator,'Text'],[p.pvalue,'Text']]as const){const d:any=await gql('query($id:UUID!){property(id:$id){dataTypeName}}',{variables:{id:q}});if(d.property?.dataTypeName!==t)throw Error(`Schema ${q}`);checks.push(`Live ${t}: ${q}`)}
for(const[key,name]of rows.map(x=>[`claim/${x[0]}`,x[1]]as const)){const d:any=await gql('query($id:UUID!,$name:String!){entity(id:$id){spaceIds}entitiesConnection(first:10,filter:{name:{isInsensitive:$name}}){nodes{id}pageInfo{hasNextPage}}}',{variables:{id:id(key),name}});if(d.entity?.spaceIds?.length||d.entitiesConnection.pageInfo.hasNextPage||d.entitiesConnection.nodes.length)throw Error(`Identity collision: ${key}`);checks.push(`Complete all-space identity discovery: ${key}`)}
const live:any=await gql('query($id:UUID!){entity(id:$id){name types{id}}}',{variables:{id:article}});if(live.entity?.name!=='Third Grade Follow-up to the Head Start Impact Study: Final Report'||!live.entity.types.some((x:any)=>x.id==='a2a5ed0cacef46b1835de457956ce915'))throw Error('Third-grade Article missing.');
const edge=(k:string,f:string,t:string,to:string)=>ops.push(...Ops.relations.create({id:id(`edge/${k}`),entityId:id(`relation/${k}`),fromEntity:f,type:t,toEntity:to,position:r[`position/${k}`]??(r[`position/${k}`]=Position.generate())}).ops);for(const[key,name,description,value,unit,locator,pvalue]of rows){const claim=id(`claim/${key}`);ops.push(...Ops.entities.update({id:claim,name,description,values:[{property:p.factual,type:'boolean',value:true},dec(value),{property:p.unit,type:'text',value:unit},{property:p.locator,type:'text',value:locator},{property:p.pvalue,type:'text',value:pvalue}]}).ops);edge(`${key}/type`,claim,SystemIds.TYPES_PROPERTY,p.claim);edge(`${key}/source`,claim,p.source,article);edge(`${key}/initiative`,claim,p.related,initiative)}
const bytes=JSON.stringify(ops,(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('hex')}:typeof v==='bigint'?{$bigint:v.toString()}:v,2)+'\n',sha256=createHash('sha256').update(bytes).digest('hex'),batch={name:'Add Head Start third-grade social-emotional ITT rows',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/${prefix}-ops.json`,sha256,journalPath:`${root}/${prefix}-publication.json`,validationPath:`${root}/${prefix}-validation.json`,entities:{article,initiative,claims:Object.fromEntries(rows.map(x=>[x[0],id(`claim/${x[0]}`)]))},operationCount:ops.length};writeFileSync(rp,JSON.stringify(r,null,2)+'\n');writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/${prefix}-batch.json`,JSON.stringify(batch,null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),opsHash:sha256,checks,source:'Puma et al. (2012), OPRE 2012-45, rendered primary-report Exhibits 4.3–4.4.',scope:'Four statistically significant third-grade social-emotional ITT rows chosen to preserve the report’s mixed reporter and cohort pattern. Regression-adjusted impacts and printed p values only; no SE, sample size, or unreported effect field is invented.'},null,2)+'\n');console.log(JSON.stringify(batch,null,2));
