import { createHash, randomUUID } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { Ops, Position, SystemIds, type Op } from '@geoprotocol/geo-sdk';
import { geoGraphqlRequest as gql } from '../src/geo-api-client';
import { EDUCATION_PUBLICATION as target } from '../src/education-bounty';

const root='data/education',prefix='head-start-third-grade-iot';
if(existsSync(`${root}/${prefix}-publication.json`)) throw Error('Preserve submitted payload.');
const input=JSON.parse(readFileSync(`${root}/${prefix}-extraction.json`,'utf8')) as {source:string;scope:string;rows:{key:string;name:string;description:string;value:string;pValue:string;unit:string;locator:string;itt:string}[]};
const registryPath=`${root}/${prefix}-registry.json`,registry:Record<string,string>=existsSync(registryPath)?JSON.parse(readFileSync(registryPath,'utf8')):{},id=(key:string)=>registry[key]??(registry[key]=randomUUID().replaceAll('-',''));
// Preserve the original extraction file; apply the reviewed fraction-scale label to future builds.
for (const row of input.rows) {
  if (row.key === 'four-teacher-emotional' && row.itt === 'c33e113e99dc4f6883a47d67d0842c35') {
    row.unit = 'Regression-adjusted teacher-reported probability difference (fraction scale), treatment on the treated (IOT), for the normal emotional-symptoms category at third grade; 4-year-old cohort; lower is less favorable.';
  }
}
const p={claim:'96f859efa1ca4b229372c86ad58b694b',factual:'da4a6c1f9d4446f9832ff3b49a4400ef',source:'49c5d5e1679a4dbdbfd33f618f227c94',related:'dfa6aebe1ca94bf29faccc4cc7afb24c',estimate:'e500e2585a964d2c9df4a47b199616c3',unit:'8405509cc7354655a348591349a5f025',locator:'84dacbddca6a44079edb5e11a4c66b40',pvalue:'ba5f8fe9d1cd9a6094338d2f37b74a5e',estimand:'ba643714da274c37a340a7f8396198dc'};
const article='c183f28d3bc34439b797138e50d5c1f3',initiative=JSON.parse(readFileSync(`${root}/head-start-registry.json`,'utf8')).initiative;
const checks:string[]=[],ops:Op[]=[];
const dec=(value:string)=>{const[a,b='']=value.split('.'),negative=a.startsWith('-'),digits=`${negative?a.slice(1):a}${b}`;return{property:p.estimate,type:'decimal' as const,exponent:-b.length,mantissa:{type:'i64' as const,value:BigInt(`${negative?'-':''}${digits}`)}}};
for(const[property,type]of [[SystemIds.TYPES_PROPERTY,'Relation'],[p.factual,'Checkbox'],[p.source,'Relation'],[p.related,'Relation'],[p.estimate,'Decimal'],[p.unit,'Text'],[p.locator,'Text'],[p.pvalue,'Text'],[p.estimand,'Text']] as const){const d:any=await gql('query($id:UUID!){property(id:$id){dataTypeName}}',{variables:{id:property}});if(d.property?.dataTypeName!==type)throw Error(`Schema mismatch: ${property}`);checks.push(`Live ${type}: ${property}`)}
for(const row of input.rows){const claim=id(`claim/${row.key}`),d:any=await gql('query($id:UUID!,$name:String!){entity(id:$id){spaceIds}entitiesConnection(first:10,filter:{name:{isInsensitive:$name}}){nodes{id}pageInfo{hasNextPage}}}',{variables:{id:claim,name:row.name}});if(d.entity?.spaceIds?.length||d.entitiesConnection.nodes.length||d.entitiesConnection.pageInfo.hasNextPage)throw Error(`Identity collision or incomplete discovery: ${row.key}`);checks.push(`Complete all-space identity discovery: ${row.key}`);const itt:any=await gql('query($id:UUID!,$space:UUID!){entity(id:$id){types{id}values(first:30,filter:{spaceId:{is:$space}}){nodes{propertyId boolean}pageInfo{hasNextPage}}}}',{variables:{id:row.itt,space:target.spaceId}});if(!itt.entity?.types.some((x:any)=>x.id===p.claim)||itt.entity.values.pageInfo.hasNextPage||!itt.entity.values.nodes.some((x:any)=>x.propertyId===p.factual&&x.boolean===true))throw Error(`Published factual ITT counterpart missing: ${row.key}`);checks.push(`Published factual ITT counterpart: ${row.key}`)}
const source:any=await gql('query($id:UUID!){entity(id:$id){name types{id}}}',{variables:{id:article}});if(source.entity?.name!=='Third Grade Follow-up to the Head Start Impact Study: Final Report'||!source.entity.types.some((x:any)=>x.id==='a2a5ed0cacef46b1835de457956ce915'))throw Error('Verified Head Start Article unavailable.');
const edge=(key:string,from:string,type:string,to:string)=>ops.push(...Ops.relations.create({id:id(`edge/${key}`),entityId:id(`relation/${key}`),fromEntity:from,type,toEntity:to,position:registry[`position/${key}`]??(registry[`position/${key}`]=Position.generate())}).ops);
for(const row of input.rows){const claim=id(`claim/${row.key}`);ops.push(...Ops.entities.update({id:claim,name:row.name,description:row.description,values:[{property:p.factual,type:'boolean',value:true},dec(row.value),{property:p.unit,type:'text',value:row.unit},{property:p.estimand,type:'text',value:'Treatment on the treated (IOT)'},{property:p.locator,type:'text',value:row.locator},{property:p.pvalue,type:'text',value:row.pValue}]}).ops);edge(`${row.key}/type`,claim,SystemIds.TYPES_PROPERTY,p.claim);edge(`${row.key}/source`,claim,p.source,article);edge(`${row.key}/initiative`,claim,p.related,initiative);edge(`${row.key}/itt`,claim,p.related,row.itt);edge(`${row.key}/itt-reverse`,row.itt,p.related,claim)}
const bytes=JSON.stringify(ops,(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('hex')}:typeof v==='bigint'?{$bigint:v.toString()}:v,2)+'\n',sha256=createHash('sha256').update(bytes).digest('hex'),batch={name:'Add Head Start third-grade treatment-on-the-treated estimates',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/${prefix}-ops.json`,sha256,journalPath:`${root}/${prefix}-publication.json`,validationPath:`${root}/${prefix}-validation.json`,entities:{article,initiative,claims:Object.fromEntries(input.rows.map(row=>[row.key,id(`claim/${row.key}`)]))},operationCount:ops.length};
writeFileSync(registryPath,JSON.stringify(registry,null,2)+'\n');writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/${prefix}-batch.json`,JSON.stringify(batch,null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),opsHash:sha256,checks,source:input.source,scope:input.scope},null,2)+'\n');console.log(JSON.stringify(batch,null,2));
