import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash, randomUUID } from 'node:crypto';
import { Ops, Position, SystemIds, type Op } from '@geoprotocol/geo-sdk';
import { geoGraphqlRequest as gql } from '../src/geo-api-client';
import { EDUCATION_PUBLICATION as target } from '../src/education-bounty';
const root='data/education',prefix='youth-challenge-roi';if(existsSync(`${root}/${prefix}-publication.json`))throw Error('Preserve submitted payload.');
const rp=`${root}/${prefix}-registry.json`,r:Record<string,string>=existsSync(rp)?JSON.parse(readFileSync(rp,'utf8')):{},id=(k:string)=>r[k]??(r[k]=randomUUID().replaceAll('-',''));
const p={claim:'96f859efa1ca4b229372c86ad58b694b',factual:'da4a6c1f9d4446f9832ff3b49a4400ef',source:'49c5d5e1679a4dbdbfd33f618f227c94',related:'dfa6aebe1ca94bf29faccc4cc7afb24c',ratio:'45ce8dc80a74432e9a2483cd1c8e86e1'};const article='4abdb70198d949288df61d50f0b458cc',initiative='c52c01e8bab14e64b56b8ceb7c244da5',name='RAND modeled a 2.66 benefit-cost ratio for Youth ChalleNGe, equivalent to a reported 166% ROI.';const description='Table 5.1 uses its baseline societal model: 2010 dollars, a 3% social discount rate, and a 15% tax-deadweight assumption. This lifetime projection combines observed evaluation impacts with modeled earnings, welfare, crime and service effects; it is not a three-year experimental outcome.';const checks:string[]=[],ops:Op[]=[];const check=(v:unknown,s:string)=>{if(!v)throw Error(s);checks.push(s)};
for(const[q,t]of[[SystemIds.TYPES_PROPERTY,'Relation'],[p.factual,'Checkbox'],[p.source,'Relation'],[p.related,'Relation'],[p.ratio,'Decimal']]as const){const d:any=await gql('query($id:UUID!){property(id:$id){dataTypeName}}',{variables:{id:q}});check(d.property?.dataTypeName===t,`Live ${t}: ${q}`)}
const claim=id('claim'),found:any=await gql('query($id:UUID!,$name:String!,$article:UUID!,$initiative:UUID!){entity(id:$id){spaceIds}entitiesConnection(first:10,filter:{name:{isInsensitive:$name}}){nodes{id}pageInfo{hasNextPage}}article:entity(id:$article){spaceIds}initiative:entity(id:$initiative){spaceIds}}',{variables:{id:claim,name,article,initiative}});check(!found.entity?.spaceIds?.length,'Allocated Claim ID unused');check(!found.entitiesConnection.pageInfo.hasNextPage&&!found.entitiesConnection.nodes.length,'Complete all-space exact-name discovery has no candidate');check(found.article?.spaceIds?.includes(target.spaceId),'RAND Article remains in destination');check(found.initiative?.spaceIds?.includes(target.spaceId),'Youth ChalleNGe initiative remains in destination');
const decimal={property:p.ratio,type:'decimal' as const,exponent:-2,mantissa:{type:'i64' as const,value:266n}};ops.push(...Ops.entities.update({id:claim,name,description,values:[{property:p.factual,type:'boolean',value:true},decimal]}).ops);const edge=(k:string,t:string,to:string)=>ops.push(...Ops.relations.create({id:id(`edge/${k}`),entityId:id(`relation/${k}`),fromEntity:claim,type:t,toEntity:to,position:r[`position/${k}`]??(r[`position/${k}`]=Position.generate())}).ops);edge('type',SystemIds.TYPES_PROPERTY,p.claim);edge('source',p.source,article);edge('initiative',p.related,initiative);
const bytes=JSON.stringify(ops,(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('hex')}:typeof v==='bigint'?{$bigint:v.toString()}:v,2)+'\n',sha256=createHash('sha256').update(bytes).digest('hex'),batch={name:'Add Youth ChalleNGe modeled benefit-cost ratio',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/${prefix}-ops.json`,sha256,journalPath:`${root}/${prefix}-publication.json`,validationPath:`${root}/${prefix}-validation.json`,entities:{claim,article,initiative},operationCount:ops.length};writeFileSync(rp,JSON.stringify(r,null,2)+'\n');writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/${prefix}-batch.json`,JSON.stringify(batch,null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),opsHash:sha256,checks,source:'RAND TR-1193 Table 5.1, baseline cost-benefit comparison, p.32; ERIC ED529935.',mapping:'The established Benefit-cost ratio Decimal stores 2.66. The title preserves the report’s equivalent 166% ROI; no new ROI property is invented.',limits:'This is a modeled societal lifetime ratio, not an observed experimental outcome or a cross-program ranking.'},null,2)+'\n');console.log(JSON.stringify(batch,null,2));
