import { createHash, randomUUID } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { Ops, Position, SystemIds, type Op } from '@geoprotocol/geo-sdk';
import { geoGraphqlRequest as gql } from '../src/geo-api-client';
import { EDUCATION_PUBLICATION as target } from '../src/education-bounty';

const root='data/education',prefix='head-start-third-grade-cognitive';
if(existsSync(`${root}/${prefix}-publication.json`))throw Error('Preserve submitted payload.');
const registryPath=`${root}/${prefix}-registry.json`,registry:Record<string,string>=existsSync(registryPath)?JSON.parse(readFileSync(registryPath,'utf8')):{},id=(key:string)=>registry[key]??(registry[key]=randomUUID().replaceAll('-',''));
const p={claim:'96f859efa1ca4b229372c86ad58b694b',factual:'da4a6c1f9d4446f9832ff3b49a4400ef',source:'49c5d5e1679a4dbdbfd33f618f227c94',related:'dfa6aebe1ca94bf29faccc4cc7afb24c',estimate:'e500e2585a964d2c9df4a47b199616c3',unit:'8405509cc7354655a348591349a5f025',locator:'84dacbddca6a44079edb5e11a4c66b40',pvalue:'ba5f8fe9d1cd9a6094338d2f37b74a5e'};
const article='c183f28d3bc34439b797138e50d5c1f3',initiative=JSON.parse(readFileSync(`${root}/head-start-registry.json`,'utf8')).initiative;
const rows=[
 ['four-reading','For children entering Head Start at age four, the third-grade ECLS-K Reading ITT impact was +2.23 points (p = .075).','The 4-year-old cohort estimate is regression-adjusted and statistically significant only at the report’s 10% threshold. It is one third-grade cognitive outcome from the national randomized access study.','2.23','ECLS-K Reading-score ITT difference at third grade, Head Start access minus control; 4-year-old cohort.','Exhibit 4.1, printed p. 77.','P = .075'],
 ['four-ppvt','For children entering Head Start at age four, the third-grade PPVT ITT impact was +2.17 points (p = .246).','This regression-adjusted vocabulary estimate is not statistically significant at conventional thresholds. It is not evidence of a separate trial or later-life outcome.','2.17','PPVT adapted-score ITT difference at third grade, Head Start access minus control; 4-year-old cohort.','Exhibit 4.1, printed p. 77.','P = .246'],
 ['four-letter-word','For children entering Head Start at age four, the third-grade WJ III Letter-Word Identification ITT impact was +2.11 points (p = .275).','This regression-adjusted literacy estimate is not statistically significant at conventional thresholds. The source reports it for the same randomized access cohort.','2.11','WJ III Letter-Word Identification-score ITT difference at third grade, Head Start access minus control; 4-year-old cohort.','Exhibit 4.1, printed p. 77.','P = .275'],
 ['four-applied-problems','For children entering Head Start at age four, the third-grade WJ III Applied Problems ITT impact was -0.43 points (p = .729).','This regression-adjusted math estimate is not statistically significant at conventional thresholds. It does not prove a zero effect.','-.43','WJ III Applied Problems-score ITT difference at third grade, Head Start access minus control; 4-year-old cohort.','Exhibit 4.1, printed p. 77.','P = .729'],
 ['four-calculation','For children entering Head Start at age four, the third-grade WJ III Calculation ITT impact was 0.00 points (p = .997).','This regression-adjusted math estimate is not statistically significant at conventional thresholds. A zero point estimate does not prove no effect.','0.00','WJ III Calculation-score ITT difference at third grade, Head Start access minus control; 4-year-old cohort.','Exhibit 4.1, printed p. 77.','P = .997'],
 ['three-reading','For children entering Head Start at age three, the third-grade ECLS-K Reading ITT impact was -0.18 points (p = .876).','This regression-adjusted literacy estimate is not statistically significant at conventional thresholds. It is for the distinct entry-age cohort within the same national randomized access study.','-.18','ECLS-K Reading-score ITT difference at third grade, Head Start access minus control; 3-year-old cohort.','Exhibit 4.2, printed p. 78.','P = .876'],
 ['three-ppvt','For children entering Head Start at age three, the third-grade PPVT ITT impact was +1.83 points (p = .146).','This regression-adjusted vocabulary estimate is not statistically significant at conventional thresholds. It is not a separate trial.','1.83','PPVT adapted-score ITT difference at third grade, Head Start access minus control; 3-year-old cohort.','Exhibit 4.2, printed p. 78.','P = .146'],
 ['three-letter-word','For children entering Head Start at age three, the third-grade WJ III Letter-Word Identification ITT impact was +0.44 points (p = .818).','This regression-adjusted literacy estimate is not statistically significant at conventional thresholds. It is one outcome from the same randomized access study.','.44','WJ III Letter-Word Identification-score ITT difference at third grade, Head Start access minus control; 3-year-old cohort.','Exhibit 4.2, printed p. 78.','P = .818'],
 ['three-applied-problems','For children entering Head Start at age three, the third-grade WJ III Applied Problems ITT impact was +0.03 points (p = .985).','This regression-adjusted math estimate is not statistically significant at conventional thresholds. A near-zero estimate does not prove no effect.','.03','WJ III Applied Problems-score ITT difference at third grade, Head Start access minus control; 3-year-old cohort.','Exhibit 4.2, printed p. 78.','P = .985'],
 ['three-calculation','For children entering Head Start at age three, the third-grade WJ III Calculation ITT impact was -0.05 points (p = .960).','This regression-adjusted math estimate is not statistically significant at conventional thresholds. It remains a measured third-grade outcome.','-.05','WJ III Calculation-score ITT difference at third grade, Head Start access minus control; 3-year-old cohort.','Exhibit 4.2, printed p. 78.','P = .960']
] as const;
const dec=(value:string)=>{const [a,b='']=value.split('.'),negative=a.startsWith('-'),digits=`${negative?a.slice(1):a}${b}`;return{property:p.estimate,type:'decimal' as const,exponent:-b.length,mantissa:{type:'i64' as const,value:BigInt(`${negative?'-':''}${digits}`)}}};
const checks:string[]=[],ops:Op[]=[];for(const[property,type]of[[SystemIds.TYPES_PROPERTY,'Relation'],[p.factual,'Checkbox'],[p.source,'Relation'],[p.related,'Relation'],[p.estimate,'Decimal'],[p.unit,'Text'],[p.locator,'Text'],[p.pvalue,'Text']]as const){const d:any=await gql('query($id:UUID!){property(id:$id){dataTypeName}}',{variables:{id:property}});if(d.property?.dataTypeName!==type)throw Error(`Schema mismatch ${property}`);checks.push(`Live ${type}: ${property}`)}
for(const [key,name]of rows.map(row=>[`claim/${row[0]}`,row[1]] as const)){const entityId=id(key),d:any=await gql('query($id:UUID!,$name:String!){entity(id:$id){spaceIds}entitiesConnection(first:10,filter:{name:{isInsensitive:$name}}){nodes{id}pageInfo{hasNextPage}}}',{variables:{id:entityId,name}});if(d.entity?.spaceIds?.length||d.entitiesConnection.pageInfo.hasNextPage||d.entitiesConnection.nodes.length)throw Error(`Identity collision or incomplete discovery: ${key}`);checks.push(`Complete all-space identity discovery: ${key}`)}
const source:any=await gql('query($id:UUID!){entity(id:$id){name types{id}}}',{variables:{id:article}});if(source.entity?.name!=='Third Grade Follow-up to the Head Start Impact Study: Final Report'||!source.entity.types.some((t:any)=>t.id==='a2a5ed0cacef46b1835de457956ce915'))throw Error('Verified third-grade Article unavailable.');
const edge=(key:string,from:string,type:string,to:string)=>ops.push(...Ops.relations.create({id:id(`edge/${key}`),entityId:id(`relation/${key}`),fromEntity:from,type,toEntity:to,position:registry[`position/${key}`]??(registry[`position/${key}`]=Position.generate())}).ops);
for(const [key,name,description,value,unit,locator,pvalue]of rows){const claim=id(`claim/${key}`);ops.push(...Ops.entities.update({id:claim,name,description,values:[{property:p.factual,type:'boolean',value:true},dec(value),{property:p.unit,type:'text',value:unit},{property:p.locator,type:'text',value:locator},{property:p.pvalue,type:'text',value:pvalue}]}).ops);edge(`${key}/type`,claim,SystemIds.TYPES_PROPERTY,p.claim);edge(`${key}/source`,claim,p.source,article);edge(`${key}/initiative`,claim,p.related,initiative)}
const bytes=JSON.stringify(ops,(_key,value)=>value instanceof Uint8Array?{$bytes:Buffer.from(value).toString('hex')}:typeof value==='bigint'?{$bigint:value.toString()}:value,2)+'\n',sha256=createHash('sha256').update(bytes).digest('hex');
const batch={name:'Add Head Start third-grade cognitive ITT table rows',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/${prefix}-ops.json`,sha256,journalPath:`${root}/${prefix}-publication.json`,validationPath:`${root}/${prefix}-validation.json`,entities:{article,initiative,claims:Object.fromEntries(rows.map(row=>[row[0],id(`claim/${row[0]}`)]))},operationCount:ops.length};
writeFileSync(registryPath,JSON.stringify(registry,null,2)+'\n');writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/${prefix}-batch.json`,JSON.stringify(batch,null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),opsHash:sha256,checks,source:'Puma et al. (2012), OPRE 2012-45, rendered primary-report Exhibits 4.1–4.2.',scope:'Ten third-grade cognitive ITT rows, five measures for each entry-age cohort. Values are regression-adjusted impacts in native score units; p values are printed in the report. No standard errors, sample sizes, effect sizes, or independent-study interpretation are invented.'},null,2)+'\n');console.log(JSON.stringify(batch,null,2));
