import{readFileSync,writeFileSync,existsSync}from'node:fs';
import{createHash,randomUUID}from'node:crypto';
import{Ops,SystemIds,type Op}from'@geoprotocol/geo-sdk';
import{geoGraphqlRequest as gql}from'../src/geo-api-client';
import{EDUCATION_PUBLICATION as target}from'../src/education-bounty';
const root='data/education',prefix='abecedarian-forecast-pilot',read=(n:string)=>JSON.parse(readFileSync(`${root}/${n}.json`,'utf8'));
if(existsSync(`${root}/${prefix}-publication.json`))throw Error('Preserve submitted payload');
const input=read('abecedarian-forecast-records'),r=input.records.find((r:any)=>r.key==='forecast/lifecycle-abc-all/authorsMethod'),registry:Record<string,string>=read('abecedarian-registry'),ops:Op[]=[],checks:string[]=[];
const check=(ok:any,label:string)=>{if(!ok)throw Error(label);checks.push(label);};
check(read('abecedarian-forecast-transcription-verification').passed,'Transcription verified');
check(createHash('sha256').update(readFileSync(`${root}/abecedarian-forecast-transcription.json`)).digest('hex')===input.transcriptionSha256,'Transcription unchanged');
check(r.value==='7.33'&&r.standardError==='1.84'&&r.studyIds.length===2,'Source pilot and two underlying trials');
const id=(k:string)=>{if(!registry[k]){registry[k]=randomUUID().replaceAll('-','');writeFileSync(`${root}/abecedarian-registry.json`,JSON.stringify(registry,null,2)+'\n');}return registry[k]!;};
const rel=(k:string,from:string,type:string,to:string,position?:string)=>{const entityId=id(`${k}/entity`);ops.push(...Ops.relations.create({id:id(`${k}/edge`),entityId,fromEntity:from,type,toEntity:to,...(position?{position}:{})}).ops);return entityId;};
const text=(property:string,value:string)=>({property,type:'text' as const,value});
const dec=(property:string,value:string)=>{const[a,b='']=value.split('.');return{property,type:'decimal' as const,exponent:-b.length,mantissa:{type:'i64' as const,value:BigInt(a+b)}};};
const p=input.mapping,entries='d66cd445e09a41809af46d86f083b41c',factual='da4a6c1f9d4446f9832ff3b49a4400ef';
for(const[property,type]of[[p.value,'Decimal'],[p.standardError,'Decimal'],[p.unit,'Text'],[p.locator,'Text'],[p.horizon,'Text'],[factual,'Checkbox'],[SystemIds.NAME_PROPERTY,'Text'],[SystemIds.DESCRIPTION_PROPERTY,'Text'],[SystemIds.MARKDOWN_CONTENT,'Text'],[p.source,'Relation'],[p.study,'Relation'],[entries,'Relation']]){const data:any=await gql('query($id:UUID!){property(id:$id){dataTypeName}}',{variables:{id:property}});check(data.property?.dataTypeName===type,`Datatype ${property}`);}
// Inspect all direct source references, not only exact prospective Claim titles.
let after:string|null=null;const seen=new Set<string>(),candidates:any[]=[];
do{const d:any=await gql('query($paper:UUID!,$after:Cursor){entitiesConnection(first:20,after:$after,filter:{relations:{some:{typeId:{is:"49c5d5e1679a4dbdbfd33f618f227c94"},toEntityId:{is:$paper}}}}){nodes{id name types{id}}pageInfo{hasNextPage endCursor}}}',{variables:{paper:r.sourceArticleId,after}});const page=d.entitiesConnection;candidates.push(...page.nodes);if(page.pageInfo.hasNextPage){check(page.pageInfo.endCursor&&!seen.has(page.pageInfo.endCursor),'Source discovery cursor');after=page.pageInfo.endCursor;seen.add(after!);}else after=null;}while(after);
check(!candidates.some(n=>n.types.some((t:any)=>['96f859efa1ca4b229372c86ad58b694b','0c4babfb43893486af827341bbf32e09'].includes(t.id))),'No existing source-linked Claim or Dataset to reconcile');
async function entity(key:string,name:string,type:string,description:string,values:any[]=[]){const e=id(key);const q:any=await gql('query($n:String!,$id:UUID!){entitiesConnection(first:10,filter:{name:{isInsensitive:$n}}){nodes{id}pageInfo{hasNextPage}}entity(id:$id){name types{id}}}',{variables:{n:name,id:e}});check(!q.entitiesConnection.pageInfo.hasNextPage&&!q.entitiesConnection.nodes.length,'No exact-name duplicate');check(!q.entity||(!q.entity.name&&!q.entity.types.length),'Unused persistent entity');ops.push(...Ops.entities.update({id:e,name,description,values}).ops);rel(`${key}/type`,e,SystemIds.TYPES_PROPERTY,type);return e;}
const dataset=await entity('dataset','ABC/CARE: early-childhood outcomes and modeled economic returns','0c4babfb43893486af827341bbf32e09','Evidence from the related ABC and CARE early-childhood experiments. Observed findings and modeled economic estimates retain their separate source versions and assumptions.');
const claim=await entity(r.key,r.name,'96f859efa1ca4b229372c86ad58b694b',r.description,[dec(p.value,r.value),dec(p.standardError,r.standardError),text(p.unit,r.unit),text(p.locator,r.locator),text(p.horizon,r.horizon),{property:factual,type:'boolean',value:true}]);
for(const[parent,key]of[[dataset,'dataset'],[claim,r.key]]){rel(`${key}/source`,parent,p.source,r.sourceArticleId);for(const study of r.studyIds)rel(`${key}/study/${study}`,parent,p.study,study);}
rel(`${r.key}/entry`,dataset,entries,claim);
const table=await entity('table/forecasts','Forecasting-method comparison',SystemIds.DATA_BLOCK,'Author-reported benefit/cost ratios and standard errors from the 2018 manuscript.');
rel('table/forecasts/source',table,SystemIds.DATA_SOURCE_TYPE_RELATION_TYPE,SystemIds.COLLECTION_DATA_SOURCE);
const attachment=rel('dataset/forecast-table',dataset,SystemIds.BLOCKS,table,'a1');rel('table/forecasts/view',attachment,SystemIds.VIEW_PROPERTY,SystemIds.TABLE_VIEW);
[p.value,p.standardError,p.horizon,p.unit,p.locator].forEach((column:string,i:number)=>rel(`table/forecasts/column/${i}`,attachment,SystemIds.PROPERTIES,column,`a${i}`));rel(`${r.key}/item`,table,SystemIds.COLLECTION_ITEM_RELATION_TYPE,claim,'a0');
const markdown=`## Coverage and interpretation\n\nThe current table contains the authors' pooled life-cycle, all-benefits model estimate: benefit/cost ratio 7.33, standard error 1.84. It is one specification from Table 6 of the August 2, 2018 author manuscript, not an independent third experiment. [Source manuscript](${r.sourceUrl}).\n\n## Comparison assumptions\n\nThe baseline discounts benefits and costs to birth at 3% and forecasts through age 79. The reported ratio averages bootstrap ratios; it is not necessarily the ratio of rounded aggregate means. Control childcare substitution costs enter the authors' benefits accounting. Forecasts combine experimental and nonexperimental data.\n\n## Cost caveat\n\nThe 2018 appendix's listed annual cost components do not reconcile to its reported total. Author-reported estimates are preserved; independently reconstructed cost-effectiveness rankings remain unresolved. The two underlying trials and alternate forecast specifications must not be counted as independent replications.`;
const block=id('dataset/context');ops.push(...Ops.entities.update({id:block,values:[text(SystemIds.MARKDOWN_CONTENT,markdown)]}).ops);rel('dataset/context/type',block,SystemIds.TYPES_PROPERTY,SystemIds.TEXT_BLOCK);rel('dataset/context',dataset,SystemIds.BLOCKS,block,'a0');
const bytes=JSON.stringify(ops,(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('hex')}:typeof v==='bigint'?{$bigint:String(v)}:v,2)+'\n',sha256=createHash('sha256').update(bytes).digest('hex');
const batch={name:'Publish ABC/CARE modeled benefit-cost pilot with study and source context',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/${prefix}-ops.json`,sha256,journalPath:`${root}/${prefix}-publication.json`,validationPath:`${root}/${prefix}-validation.json`};writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/${prefix}-batch.json`,JSON.stringify(batch,null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),opsHash:sha256,checks,candidates},null,2)+'\n');console.log(JSON.stringify({dataset,claim,operations:ops.length}));
