import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash, randomUUID } from 'node:crypto';
import { Ops, Position, SystemIds, type Op } from '@geoprotocol/geo-sdk';
import { geoGraphqlRequest as gql } from '../src/geo-api-client';
import { EDUCATION_PUBLICATION as target } from '../src/education-bounty';

const root = 'data/education', prefix = 'mssi-2023';
if (existsSync(`${root}/${prefix}-publication.json`)) throw new Error('Preserve submitted payload.');
const registryPath = `${root}/${prefix}-registry.json`;
const registry: Record<string, string> = existsSync(registryPath) ? JSON.parse(readFileSync(registryPath, 'utf8')) : {};
const id = (key: string) => registry[key] ?? (registry[key] = randomUUID().replaceAll('-', ''));
const p = { article: 'a2a5ed0cacef46b1835de457956ce915', initiative: 'd272f19cef87485fb83e26fb68957395', claim: '96f859efa1ca4b229372c86ad58b694b', factual: 'da4a6c1f9d4446f9832ff3b49a4400ef', url: '412ff593e9154012a43d4c27ec5c68b6', source: '49c5d5e1679a4dbdbfd33f618f227c94', related: 'dfa6aebe1ca94bf29faccc4cc7afb24c', estimate: 'e500e2585a964d2c9df4a47b199616c3', cost: '6ba2ce00db064687b108aa8449672886', sample: '210e9b352b454d6eb7a32906d24d3c8d', unit: '8405509cc7354655a348591349a5f025', locator: '84dacbddca6a44079edb5e11a4c66b40', pValue: 'ba5f8fe9d1cd9a6094338d2f37b74a5e', year: '97e14050fc49467bb3aaf4d7eccbbb69', currency: '6e7371ca96cb44348f16932f77f55e75', denominator: '3a558d71454745a992c035040f648729', location: '95d770021faf4f7cb7deb21a7d48cda0' };
const url = 'https://www.mdrc.org/work/publications/pathway-college-achievement/file-full';
const articleName = 'Pathway to College Achievement: A Mixed-Methods Evaluation of the Male Student Success Initiative for Men of Color';
const initiativeName = 'Male Student Success Initiative evaluated CCBC program model';
const maryland = '629b86b1f4074326a0f14227f87a9e88';
const rows = [
  ['design', 'MSSI randomly assigned 514 eligible CCBC male students of color to program or usual services.', 'The 2019–2022 evaluation assigned 304 students to MSSI and 210 to usual CCBC services. It evaluates a two-semester culturally contextualized course and support package; the control group retained campus services available to all students.', null, 514, 'Individual-level randomized controlled trial; 304 program group and 210 control group.', null, 'Overview, p. iii; Executive Summary pp. ES-2–ES-3.'],
  ['cost', 'MSSI cost $885 per intended program participant in real 2021 dollars.', 'The spring-2019-to-fall-2021 average is an intent-to-treat service cost based on intended students, including those who did not enroll. The report says early persistence and completion impacts did not permit a cost-effectiveness calculation.', 885, 304, 'Real 2021 USD average program cost per intended participant across six terms.', null, 'Table ES.2, p. ES-8; Table 4.5, p. 68.'],
  ['acdv-enrollment', 'MSSI increased first-semester ACDV-course enrollment by 10.3 percentage points (66.4% versus 56.1%).', 'This full-sample first-semester transcript outcome is course enrollment, not overall college persistence. The reported randomized difference has p = .012 and standard error 4.1 percentage points.', 10.3, 514, 'Percentage-point difference in first-semester enrollment in the Academic Development course, MSSI minus usual services.', '0.012', 'Table ES.1, p. ES-7; Table 4.1, p. 56.'],
  ['acdv-pass', 'MSSI increased first-semester ACDV-course passing by 15.2 percentage points (43.4% versus 28.1%).', 'This full-sample first-semester transcript outcome concerns passing the intervention-linked course. It does not establish a later degree or persistence effect.', 15.2, 514, 'Percentage-point difference in passing the Academic Development course in the first semester, MSSI minus usual services.', '< .001', 'Table ES.1, p. ES-7; Table 4.1, p. 56.'],
  ['credits', 'MSSI showed no statistically significant first-semester difference in credits earned (+0.3; 4.3 versus 3.9).', 'The full-sample first-semester transcript result has p = .446 and standard error 0.4 credits. The source also found no early persistence effect, so this result should not be presented as evidence of completion.', 0.3, 514, 'Difference in first-semester credits earned, MSSI minus usual services.', '0.446', 'Table ES.1, p. ES-7; Table 4.1, p. 56.'],
  ['later-grades', 'MSSI increased fourth-semester A/B/C grades in all courses by 7.3 percentage points (12.5% versus 5.2%).', 'This cohorts-1-to-3 follow-up result has p = .048 and standard error 3.6 percentage points (N = 256). It is later course-performance evidence, not a persistence or degree-completion effect.', 7.3, 256, 'Percentage-point difference in receiving A, B, or C in all courses in the fourth semester, MSSI minus usual services; cohorts 1–3 only.', '0.048', 'Table ES.2, p. ES-8; Table 4.3, p. 60.'],
] as const;
const decimal = (property: string, value: number) => { const [whole, fraction = ''] = String(value).split('.'); return { property, type: 'decimal' as const, exponent: -fraction.length, mantissa: { type: 'i64' as const, value: BigInt(`${whole}${fraction}`) } }; };
const checks: string[] = []; const check = (ok: unknown, label: string) => { if (!ok) throw new Error(label); checks.push(label); };
for (const [property, type] of [[SystemIds.TYPES_PROPERTY, 'Relation'], [p.factual, 'Checkbox'], [p.url, 'Text'], [p.source, 'Relation'], [p.related, 'Relation'], [p.estimate, 'Decimal'], [p.cost, 'Decimal'], [p.sample, 'Integer'], [p.unit, 'Text'], [p.locator, 'Text'], [p.pValue, 'Text'], [p.year, 'Integer'], [p.currency, 'Text'], [p.denominator, 'Text'], [p.location, 'Relation']] as const) { const result: any = await gql('query($id:UUID!){property(id:$id){dataTypeName}}', { variables: { id: property } }); check(result.property?.dataTypeName === type, `Live ${type}: ${property}`); }
for (const [key, name] of [['article', articleName], ['initiative', initiativeName], ...rows.map(row => [`claim/${row[0]}`, row[1]])] as [string, string][]) { const result: any = await gql('query($id:UUID!,$name:String!){entity(id:$id){spaceIds}entitiesConnection(first:10,filter:{name:{isInsensitive:$name}}){nodes{id}pageInfo{hasNextPage}}}', { variables: { id: id(key), name } }); check(!result.entity?.spaceIds?.length, `Allocated identity unused: ${key}`); check(!result.entitiesConnection.pageInfo.hasNextPage && result.entitiesConnection.nodes.length === 0, `Complete all-space exact-title discovery has no candidate: ${key}`); }
const md: any = await gql('query($id:UUID!){entity(id:$id){spaceIds types{id name}relations(first:30){nodes{type{id}toEntity{id}}}}}', { variables: { id: maryland } });
check(md.entity?.spaceIds?.includes('84a679ce188f061ac9a92380bac2bab5') && md.entity.types.some((t: any) => t.name === 'State') && md.entity.relations.nodes.some((r: any) => r.type.id === '6d8cd471f7af415f941118b1ef106434' && r.toEntity.id === '0093d90725d94cb08903515673538d40'), 'Canonical Maryland State with United States relation.');
const article = id('article'), initiative = id('initiative'), ops: Op[] = [];
const edge = (key: string, from: string, type: string, to: string) => { registry[`position/${key}`] ??= Position.generate(); ops.push(...Ops.relations.create({ id: id(`edge/${key}`), entityId: id(`relation/${key}`), fromEntity: from, type, toEntity: to, position: registry[`position/${key}`] }).ops); };
ops.push(...Ops.entities.update({ id: article, name: articleName, description: 'MDRC’s 2023 randomized impact, implementation, and cost evaluation of CCBC’s Male Student Success Initiative for men of color.', values: [{ property: p.url, type: 'text', value: url }] }).ops); edge('article/type', article, SystemIds.TYPES_PROPERTY, p.article); edge('article/location', article, p.location, maryland);
ops.push(...Ops.entities.update({ id: initiative, name: initiativeName, description: 'A two-semester CCBC program combining a culturally contextualized course, mentoring, student-support referrals, leadership and career activities, and community-building for eligible male students of color.', values: [{ property: p.url, type: 'text', value: url }] }).ops); edge('initiative/type', initiative, SystemIds.TYPES_PROPERTY, p.initiative); edge('initiative/source', initiative, p.source, article); edge('initiative/article', initiative, p.related, article); edge('initiative/location', initiative, p.location, maryland);
for (const [key, name, description, value, sample, unit, pValue, locator] of rows) { const claim = id(`claim/${key}`), monetary = key === 'cost'; const values: any[] = [{ property: p.factual, type: 'boolean', value: true }, { property: p.sample, type: 'integer', value: BigInt(sample) }, { property: p.unit, type: 'text', value: unit }, { property: p.locator, type: 'text', value: locator }]; if (value !== null) values.push(decimal(monetary ? p.cost : p.estimate, value)); if (pValue) values.push({ property: p.pValue, type: 'text', value: `p = ${pValue}` }); if (monetary) values.push({ property: p.year, type: 'integer', value: 2021n }, { property: p.currency, type: 'text', value: 'USD' }, { property: p.denominator, type: 'text', value: 'Average real 2021-dollar program cost per intended participant over six terms; intended students include recruited students and students in their second eligible term whether or not enrolled.' }); ops.push(...Ops.entities.update({ id: claim, name, description, values }).ops); edge(`${key}/type`, claim, SystemIds.TYPES_PROPERTY, p.claim); edge(`${key}/source`, claim, p.source, article); edge(`${key}/initiative`, claim, p.related, initiative); edge(`${key}/location`, claim, p.location, maryland); }
const bytes = JSON.stringify(ops, (_key, value) => value instanceof Uint8Array ? { $bytes: Buffer.from(value).toString('hex') } : typeof value === 'bigint' ? { $bigint: value.toString() } : value, 2) + '\n'; const sha256 = createHash('sha256').update(bytes).digest('hex'); const batch = { name: 'Add MSSI randomized outcomes and real-dollar cost analysis', spaceId: target.spaceId, bounty: target.bountyId, opsPath: `${root}/${prefix}-ops.json`, sha256, journalPath: `${root}/${prefix}-publication.json`, validationPath: `${root}/${prefix}-validation.json`, entities: { article, initiative, claims: Object.fromEntries(rows.map(row => [row[0], id(`claim/${row[0]}`)])) }, operationCount: ops.length };
writeFileSync(registryPath, JSON.stringify(registry, null, 2) + '\n'); writeFileSync(batch.opsPath, bytes); writeFileSync(`${root}/${prefix}-batch.json`, JSON.stringify(batch, null, 2) + '\n'); writeFileSync(batch.validationPath, JSON.stringify({ ready: true, checkedAt: new Date().toISOString(), opsHash: sha256, checks, source: { url, scope: '2023 MDRC MSSI randomized outcome and cost analysis.', limits: 'One community-college setting, substantial pandemic and implementation disruption, and no source-supported cost-effectiveness conclusion.' } }, null, 2) + '\n'); console.log(JSON.stringify(batch, null, 2));
