import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash, randomUUID } from 'node:crypto';
import { Ops, Position, type Op } from '@geoprotocol/geo-sdk';
import { geoGraphqlRequest as gql } from '../src/geo-api-client';
import { EDUCATION_PUBLICATION as target } from '../src/education-bounty';
const root='data/education',prefix='pace-geography',location='95d770021faf4f7cb7deb21a7d48cda0',florida='439e428f73a44766895c396bdea0e534',us='0093d90725d94cb08903515673538d40',geographySpace='84a679ce188f061ac9a92380bac2bab5';
if(existsSync(`${root}/${prefix}-publication.json`))throw Error('Preserve submitted payload.');
const rp=`${root}/${prefix}-registry.json`,r:Record<string,string>=existsSync(rp)?JSON.parse(readFileSync(rp,'utf8')):{},id=(k:string)=>r[k]??(r[k]=randomUUID().replaceAll('-','')),
study:Record<string,string>=JSON.parse(readFileSync(`${root}/pace-2019-registry.json`,'utf8')),
targets=[study.article,study.initiative,...['design','net-cost','days-present','on-track','credit-success','suspension','charge'].map(k=>study[`claim/${k}`])],checks:string[]=[],check=(ok:unknown,s:string)=>{if(!ok)throw Error(s);checks.push(s)};
const canonical:any=await gql('query($id:UUID!){entity(id:$id){name types{name} relations(first:50){nodes{typeId toEntityId}pageInfo{hasNextPage}}}}',{variables:{id:florida}});check(canonical.entity?.name==='Florida'&&!canonical.entity.relations.pageInfo.hasNextPage&&canonical.entity.types.some((t:any)=>t.name==='State')&&canonical.entity.relations.nodes.some((x:any)=>x.typeId==='6d8cd471f7af415f941118b1ef106434'&&x.toEntityId===us),'Canonical Geography-space Florida State identity');
const ops:Op[]=[];for(const from of targets){const d:any=await gql('query($from:UUID!,$space:UUID!,$type:UUID!,$to:UUID!){relationsConnection(first:2,filter:{fromEntityId:{is:$from},spaceId:{is:$space},typeId:{is:$type},toEntityId:{is:$to}}){nodes{id}pageInfo{hasNextPage}}}',{variables:{from,space:target.spaceId,type:location,to:florida}});check(!d.relationsConnection.pageInfo.hasNextPage&&!d.relationsConnection.nodes.length,`No duplicate Florida location: ${from}`);const k=`location/${from}`;r[`position/${k}`]??=Position.generate();ops.push(...Ops.relations.create({id:id(`edge/${k}`),entityId:id(`relation/${k}`),fromEntity:from,type:location,toEntity:florida,toSpace:geographySpace,position:r[`position/${k}`]}).ops)}
const bytes=JSON.stringify(ops,(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('hex')}:typeof v==='bigint'?{$bigint:v.toString()}:v,2)+'\n',sha256=createHash('sha256').update(bytes).digest('hex'),batch={name:'Link PACE evidence to canonical Florida geography',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/${prefix}-ops.json`,sha256,journalPath:`${root}/${prefix}-publication.json`,validationPath:`${root}/${prefix}-validation.json`,entities:{florida,targets},operationCount:ops.length};writeFileSync(rp,JSON.stringify(r,null,2)+'\n');writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/${prefix}-batch.json`,JSON.stringify(batch,null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),opsHash:sha256,checks,scope:'State-level Florida geography for the 14-center PACE evaluation. No individual center, coordinate, or public-stop location is inferred.'},null,2)+'\n');console.log(JSON.stringify(batch,null,2));
