import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash, randomUUID } from 'node:crypto';
import { Ops, Position, SystemIds, type Op } from '@geoprotocol/geo-sdk';
import { geoGraphqlRequest as gql } from '../src/geo-api-client';
import { EDUCATION_PUBLICATION as target } from '../src/education-bounty';
const root='data/education',prefix='tutoring-meta-debate'; if(existsSync(`${root}/${prefix}-publication.json`))throw Error('Preserve submitted payload.');
const rp=`${root}/${prefix}-registry.json`,r:Record<string,string>=existsSync(rp)?JSON.parse(readFileSync(rp,'utf8')):{},id=(k:string)=>r[k]??(r[k]=randomUUID().replaceAll('-',''));
const p={claim:'96f859efa1ca4b229372c86ad58b694b',factual:'da4a6c1f9d4446f9832ff3b49a4400ef',source:'49c5d5e1679a4dbdbfd33f618f227c94',related:'dfa6aebe1ca94bf29faccc4cc7afb24c',support:'1dc6a843458848198e7a6e672268f811'};
const article='76f18ade420143779ca3c67183dc1dd8',name='School systems should prioritize tutoring delivered during the school day.',description='This policy position gives weight to the meta-analysis finding that tutoring delivered during school had larger average impacts than after-school tutoring. It does not establish cost, feasibility, staffing, or the effect of every in-school program.',support=['9b94180ac02b464a9bd1a2c873d75e97','051b0b0f782d469a84520218e49bc4ec'],related=['25f0ec3189e4427cbdb294d2016b692d'],checks:string[]=[],ops:Op[]=[];
const check=(v:unknown,s:string)=>{if(!v)throw Error(s);checks.push(s)};for(const[q,t]of[[SystemIds.TYPES_PROPERTY,'Relation'],[p.factual,'Checkbox'],[p.source,'Relation'],[p.related,'Relation'],[p.support,'Relation']]as const){const d:any=await gql('query($id:UUID!){property(id:$id){dataTypeName}}',{variables:{id:q}});check(d.property?.dataTypeName===t,`Live ${t}: ${q}`)}
const parent=id('parent'),collision:any=await gql('query($id:UUID!,$name:String!){entity(id:$id){spaceIds}entitiesConnection(first:10,filter:{name:{isInsensitive:$name}}){nodes{id}pageInfo{hasNextPage}}}',{variables:{id:parent,name}});check(!collision.entity?.spaceIds?.length,'Allocated parent ID unused');check(!collision.entitiesConnection.pageInfo.hasNextPage&&!collision.entitiesConnection.nodes.length,'Complete all-space parent discovery has no candidate');
for(const c of [...support,...related]){const d:any=await gql('query($id:UUID!,$space:UUID!){entity(id:$id){types{id}values(first:30,filter:{spaceId:{is:$space}}){nodes{propertyId boolean}pageInfo{hasNextPage}}}}',{variables:{id:c,space:target.spaceId}});check(d.entity?.types.some((x:any)=>x.id===p.claim)&&!d.entity.values.pageInfo.hasNextPage&&d.entity.values.nodes.some((v:any)=>v.propertyId===p.factual&&v.boolean===true),`Factual evidence available: ${c}`)}
const edge=(k:string,f:string,t:string,to:string)=>ops.push(...Ops.relations.create({id:id(`edge/${k}`),entityId:id(`relation/${k}`),fromEntity:f,type:t,toEntity:to,position:r[`position/${k}`]??(r[`position/${k}`]=Position.generate())}).ops);
ops.push(...Ops.entities.update({id:parent,name,description,values:[{property:p.factual,type:'boolean',value:false}]}).ops);edge('type',parent,SystemIds.TYPES_PROPERTY,p.claim);edge('source',parent,p.source,article);for(const c of [...support,...related]){edge(`related/${c}`,parent,p.related,c);edge(`related-reverse/${c}`,c,p.related,parent)}for(const c of support)edge(`support/${c}`,parent,p.support,c);
const bytes=JSON.stringify(ops,(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('hex')}:typeof v==='bigint'?{$bigint:v.toString()}:v,2)+'\n',sha256=createHash('sha256').update(bytes).digest('hex'),batch={name:'Add in-school tutoring policy debate claim',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/${prefix}-ops.json`,sha256,journalPath:`${root}/${prefix}-publication.json`,validationPath:`${root}/${prefix}-validation.json`,entities:{parent,support,related},operationCount:ops.length};writeFileSync(rp,JSON.stringify(r,null,2)+'\n');writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/${prefix}-batch.json`,JSON.stringify(batch,null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),opsHash:sha256,checks,rationale:'The parent is nonfactual. The 2020 pooled effect and in-school subgroup pattern provide the direct argument; the 2024 journal estimate is a version-related estimate and is Related only, not an opposing study.'},null,2)+'\n');console.log(JSON.stringify(batch,null,2));
