import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash, randomUUID } from 'node:crypto';
import { Ops, Position, SystemIds, type Op } from '@geoprotocol/geo-sdk';
import { geoGraphqlRequest as gql } from '../src/geo-api-client';
import { EDUCATION_PUBLICATION as target } from '../src/education-bounty';
const root='data/education',prefix='tennessee-vpk';if(existsSync(`${root}/${prefix}-publication.json`))throw Error('Preserve submitted payload.');
const rp=`${root}/${prefix}-registry.json`,r:Record<string,string>=existsSync(rp)?JSON.parse(readFileSync(rp,'utf8')):{},id=(k:string)=>r[k]??(r[k]=randomUUID().replaceAll('-',''));
const p={article:'a2a5ed0cacef46b1835de457956ce915',initiative:'d272f19cef87485fb83e26fb68957395',claim:'96f859efa1ca4b229372c86ad58b694b',factual:'da4a6c1f9d4446f9832ff3b49a4400ef',doi:'7cb59354e30c48119e99ff62fcf61646',url:'412ff593e9154012a43d4c27ec5c68b6',source:'49c5d5e1679a4dbdbfd33f618f227c94',related:'dfa6aebe1ca94bf29faccc4cc7afb24c',topics:'806d52bc27e94c9193c057978b093351',topic:'0df9fad9098d4b11bacb9af0f7a79182'};
const articleName='Effects of the Tennessee Prekindergarten Program on children’s achievement and behavior through third grade',initiativeName='Tennessee Voluntary Pre-K Program',url='https://cdn.vanderbilt.edu/vu-my/wp-content/uploads/sites/1147/2018/11/14112745/LipseyFarranDurkin_2018ECRQ.pdf',doi='10.1016/j.ecresq.2018.03.005';
const rows=[
 ['design','The Tennessee Voluntary Pre-K evaluation randomly assigned 2,990 low-income applicants to receive admission offers or remain on a waiting list.','State education records followed the full randomized sample from pre-K through third grade; an additional consented subsample had 1,076 children. This is a waiting-list offer comparison in Tennessee, not a result for every public pre-K model.'],
 ['achievement','In the Tennessee Voluntary Pre-K trial, children offered pre-K did not perform as well as controls on third-grade state achievement tests.','The paper reports early test advantages at the end of pre-K, then control-group catch-up in kindergarten and later grades. This outcome does not establish effects on unmeasured later-life outcomes or every achievement instrument.'],
 ['behavior-records','In the Tennessee Voluntary Pre-K trial, teacher behavior ratings showed no overall group advantage, while later school records included more rule violations and persistent special-education designations for pre-K participants.','The article reports heterogeneous results, including some favorable effects for male and Black children on selected ratings and attendance. These school-record patterns do not identify the mechanism or generalize automatically beyond the evaluated program.'],
] as const;const checks:string[]=[],ops:Op[]=[];const check=(v:unknown,s:string)=>{if(!v)throw Error(s);checks.push(s)};
for(const[q,t]of[[SystemIds.TYPES_PROPERTY,'Relation'],[p.factual,'Checkbox'],[p.doi,'Text'],[p.url,'Text'],[p.source,'Relation'],[p.related,'Relation'],[p.topics,'Relation']]as const){const d:any=await gql('query($id:UUID!){property(id:$id){dataTypeName}}',{variables:{id:q}});check(d.property?.dataTypeName===t,`Live ${t}: ${q}`)}
for(const[key,name]of [['article',articleName],['initiative',initiativeName],...rows.map(x=>[`claim/${x[0]}`,x[1]])]as const){const entity=id(key),d:any=await gql('query($id:UUID!,$name:String!){entity(id:$id){spaceIds}entitiesConnection(first:10,filter:{name:{isInsensitive:$name}}){nodes{id}pageInfo{hasNextPage}}}',{variables:{id:entity,name}});check(!d.entity?.spaceIds?.length,`Allocated ID unused: ${key}`);check(!d.entitiesConnection.pageInfo.hasNextPage&&!d.entitiesConnection.nodes.length,`Complete all-space identity discovery: ${key}`)}
const article=id('article'),initiative=id('initiative');const edge=(k:string,f:string,t:string,to:string)=>ops.push(...Ops.relations.create({id:id(`edge/${k}`),entityId:id(`relation/${k}`),fromEntity:f,type:t,toEntity:to,position:r[`position/${k}`]??(r[`position/${k}`]=Position.generate())}).ops);
ops.push(...Ops.entities.update({id:article,name:articleName,description:'A 2018 open-access report of Tennessee’s statewide randomized voluntary pre-K evaluation through third grade.',values:[{property:p.doi,type:'text',value:doi},{property:p.url,type:'text',value:url}]}).ops);edge('article/type',article,SystemIds.TYPES_PROPERTY,p.article);ops.push(...Ops.entities.update({id:initiative,name:initiativeName,description:'Tennessee’s state-funded voluntary pre-K program for eligible children. The linked randomized evaluation concerns oversubscribed sites and its study-period comparison conditions.',values:[{property:p.url,type:'text',value:url}]}).ops);edge('initiative/type',initiative,SystemIds.TYPES_PROPERTY,p.initiative);edge('initiative/source',initiative,p.source,article);edge('initiative/article',initiative,p.related,article);edge('initiative/topic',initiative,p.topics,p.topic);
for(const row of rows){const claim=id(`claim/${row[0]}`);ops.push(...Ops.entities.update({id:claim,name:row[1],description:row[2],values:[{property:p.factual,type:'boolean',value:true}]}).ops);edge(`${row[0]}/type`,claim,SystemIds.TYPES_PROPERTY,p.claim);edge(`${row[0]}/source`,claim,p.source,article);edge(`${row[0]}/initiative`,claim,p.related,initiative);edge(`${row[0]}/topic`,claim,p.topics,p.topic)}
const bytes=JSON.stringify(ops,(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('hex')}:typeof v==='bigint'?{$bigint:v.toString()}:v,2)+'\n',sha256=createHash('sha256').update(bytes).digest('hex'),batch={name:'Add Tennessee voluntary pre-K randomized third-grade evidence',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/${prefix}-ops.json`,sha256,journalPath:`${root}/${prefix}-publication.json`,validationPath:`${root}/${prefix}-validation.json`,entities:{article,initiative,claims:Object.fromEntries(rows.map(row=>[row[0],id(`claim/${row[0]}`)]))},operationCount:ops.length};writeFileSync(rp,JSON.stringify(r,null,2)+'\n');writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/${prefix}-batch.json`,JSON.stringify(batch,null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),opsHash:sha256,checks,source:'Lipsey, Farran & Durkin (2018), Early Childhood Research Quarterly 45:155–176, DOI 10.1016/j.ecresq.2018.03.005; Vanderbilt open-access PDF.',scope:'Initial source-backed trial design and third-grade findings. It preserves early gains, later achievement reversal, heterogeneous behavior/record outcomes, and local-program limits.'},null,2)+'\n');console.log(JSON.stringify(batch,null,2));
