import {existsSync,readFileSync,writeFileSync} from 'node:fs';
import {createHash,randomUUID} from 'node:crypto';
import {Ops,Position,SystemIds,type Op} from '@geoprotocol/geo-sdk';
import {geoGraphqlRequest as gql} from '../src/geo-api-client';
import {EDUCATION_PUBLICATION as target} from '../src/education-bounty';
const root='data/education',registryPath=`${root}/double-dose-algebra-registry.json`,registry:Record<string,string>=existsSync(registryPath)?JSON.parse(readFileSync(registryPath,'utf8')):{};
const id=(key:string)=>registry[key]??(registry[key]=randomUUID().replaceAll('-',''));
const p={article:'a2a5ed0cacef46b1835de457956ce915',initiative:'d272f19cef87485fb83e26fb68957395',claim:'96f859efa1ca4b229372c86ad58b694b',factual:'da4a6c1f9d4446f9832ff3b49a4400ef',url:'412ff593e9154012a43d4c27ec5c68b6',doi:'7cb59354e30c48119e99ff62fcf61646',source:'49c5d5e1679a4dbdbfd33f618f227c94',related:'dfa6aebe1ca94bf29faccc4cc7afb24c',location:'95d770021faf4f7cb7deb21a7d48cda0'};
const checks:string[]=[],ops:Op[]=[],edges:any[]=[];const check=(ok:unknown,label:string)=>{if(!ok)throw Error(label);checks.push(label)};
const rel=(key:string,from:string,type:string,to:string,toSpace?:string)=>{const position=registry[`position/${key}`]??(registry[`position/${key}`]=Position.generate());ops.push(...Ops.relations.create({id:id(`edge/${key}`),entityId:id(`edge-entity/${key}`),fromEntity:from,type,toEntity:to,position,...(toSpace?{toSpace}:{})}).ops);edges.push({from,type,to,toSpace});};
const articleName='Intensive Math Instruction and Educational Attainment: Long-Run Impacts of Double-Dose Algebra',initiativeName='Chicago double-dose algebra';
for(const [filename,label] of [[`${root}/discovery/intensive-math-instruction-and-educational-attainment-long-run-impacts-of-double-dose-algebra.json`,'Article'],[`${root}/discovery/chicago-double-dose-algebra.json`,'Initiative'],[`${root}/discovery/contains-double-dose-algebra.json`,'semantic family']]){const d=JSON.parse(readFileSync(filename,'utf8'));check(d.complete&&(label==='semantic family'?d.nodes.length===0:d.nodes.length===0),`Complete all-space ${label} discovery found no candidate`);}
for(const [property,type] of [[SystemIds.TYPES_PROPERTY,'Relation'],[p.source,'Relation'],[p.related,'Relation'],[p.location,'Relation'],[p.factual,'Checkbox'],[p.url,'Text'],[p.doi,'Text']]){const d:any=await gql('query($id:UUID!){property(id:$id){dataTypeName}}',{variables:{id:property}});check(d.property?.dataTypeName===type,`Live property type ${property}`);}
const chicago='e82f3bfc991a4578aa8b7a503640b95e';const chicagoCheck:any=await gql('query($id:UUID!){entity(id:$id){name relations(first:30){nodes{typeId toEntityId}pageInfo{hasNextPage}}}}',{variables:{id:chicago}});check(chicagoCheck.entity?.name==='Chicago'&&!chicagoCheck.entity.relations.pageInfo.hasNextPage&&chicagoCheck.entity.relations.nodes.some((r:any)=>r.typeId==='47b55f87c5ca4b2db1ac32296fd0c650'&&r.toEntityId==='e22d027da3254158ba7cdd4b8e24c44c'),'Reuse verified Chicago, Illinois Location');
const article=id('article'),initiative=id('initiative'),findings=[
 {key:'policy-design',name:'Chicago’s double-dose algebra policy assigned ninth graders below the national-median eighth-grade math score to two periods of algebra coursework.',description:'The policy doubled math instructional time and also changed peer composition and pedagogy. Its regression-discontinuity evidence applies near the assignment threshold, not to every student or every implementation.',factual:true},
 {key:'attainment',name:'The double-dose algebra study reports positive impacts on credits, test scores, high-school graduation and college enrollment.',description:'The published study’s regression-discontinuity analysis reports these outcomes for the targeted Chicago policy. The abstract does not provide one common effect size, so this record does not invent a scalar estimate.',factual:true},
 {key:'reading-skill',name:'The double-dose algebra study found its largest reported impacts among students with below-average reading skills.',description:'This is a source-reported heterogeneity finding, not proof that reading skill alone caused the difference or that the result applies outside the threshold-based Chicago policy.',factual:true}
];
for(const entityId of [article,initiative,...findings.map(x=>id(`claim/${x.key}`))]){const d:any=await gql('query($id:UUID!){entity(id:$id){spaceIds}}',{variables:{id:entityId}});check(!d.entity?.spaceIds?.length,`Persistent ID is unoccupied: ${entityId}`);}
ops.push(...Ops.entities.update({id:article,name:articleName,description:'Cortes, Goodman and Nomi’s study of Chicago double-dose algebra and longer-run educational attainment.',values:[{property:p.doi,type:'text',value:'10.3368/jhr.50.1.108'},{property:p.url,type:'text',value:'https://www.nber.org/papers/w20211'}]}).ops);rel('article/type',article,SystemIds.TYPES_PROPERTY,p.article);
ops.push(...Ops.entities.update({id:initiative,name:initiativeName,description:'A Chicago Public Schools ninth-grade policy that paired algebra with an additional support period for students below a prior-math-score threshold. Its effects depend on assignment, instructional time and classroom organization.',values:[{property:p.url,type:'text',value:'https://www.nber.org/papers/w20211'}]}).ops);rel('initiative/type',initiative,SystemIds.TYPES_PROPERTY,p.initiative);rel('initiative/source',initiative,p.source,article);rel('initiative/article',initiative,p.related,article);rel('initiative/location',initiative,p.location,chicago,'84a679ce188f061ac9a92380bac2bab5');
for(const row of findings){const claim=id(`claim/${row.key}`);ops.push(...Ops.entities.update({id:claim,name:row.name,description:row.description,values:[{property:p.factual,type:'boolean',value:row.factual}]}).ops);rel(`claim/${row.key}/type`,claim,SystemIds.TYPES_PROPERTY,p.claim);rel(`claim/${row.key}/source`,claim,p.source,article);rel(`claim/${row.key}/initiative`,claim,p.related,initiative);rel(`claim/${row.key}/location`,claim,p.location,chicago,'84a679ce188f061ac9a92380bac2bab5');}
const bytes=JSON.stringify(ops,(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('hex')}:typeof v==='bigint'?{$bigint:v.toString()}:v,2)+'\n',sha256=createHash('sha256').update(bytes).digest('hex');
const batch={name:'Add Chicago double-dose algebra evidence',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/double-dose-algebra-ops.json`,sha256,journalPath:`${root}/double-dose-algebra-publication.json`,validationPath:`${root}/double-dose-algebra-validation.json`,entities:{article,initiative,findings:Object.fromEntries(findings.map(x=>[x.key,id(`claim/${x.key}`)]))},operationCount:ops.length};
writeFileSync(registryPath,JSON.stringify(registry,null,2)+'\n');writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/double-dose-algebra-batch.json`,JSON.stringify(batch,null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),opsHash:sha256,checks,edges,source:{title:articleName,version:'Journal of Human Resources 50(1), 2015; source URL NBER working-paper page w20211',design:'Regression discontinuity at national-median eighth-grade math score',scope:'Targeted Chicago ninth graders near the assignment threshold; source reports implementation-dependent effects.'}},null,2)+'\n');console.log(JSON.stringify(batch,null,2));
