import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash, randomUUID } from 'node:crypto';
import { Ops, Position, SystemIds, type Op } from '@geoprotocol/geo-sdk';
import { geoGraphqlRequest as gql } from '../src/geo-api-client';
import { EDUCATION_PUBLICATION as target } from '../src/education-bounty';
const root='data/education',prefix='teacher-coaching-meta-analysis-debate';
if(existsSync(`${root}/${prefix}-publication.json`))throw Error('Preserve submitted debate payload.');
const rp=`${root}/${prefix}-registry.json`,r:Record<string,string>=existsSync(rp)?JSON.parse(readFileSync(rp,'utf8')):{},id=(k:string)=>r[k]??(r[k]=randomUUID().replaceAll('-',''));
const p={claim:'96f859efa1ca4b229372c86ad58b694b',factual:'da4a6c1f9d4446f9832ff3b49a4400ef',source:'49c5d5e1679a4dbdbfd33f618f227c94',related:'dfa6aebe1ca94bf29faccc4cc7afb24c',support:'1dc6a843458848198e7a6e672268f811',oppose:'4e6ec5d14292498a84e5f607ca1a08ce'};
const article='6a85813ac8734141b55affa06793661c',study='e181f6b918e548b79304a674743753fd',name='Districts should invest in sustained teacher coaching.',description='This policy position weighs the meta-analysis’s positive pooled instruction and achievement estimates against non-significant pooled estimates in several smaller or broader subgroups. The linked rows overlap across studies and do not prove that a particular coaching feature causes improvement.',support=['ac70981427fb402994c2a7526febea9f','5416e25c785a4daf967b7d4e02dcc9ef','caaf065aee054ae385f184dbf6043028'],oppose=['4d20a987683a4686af61d1b9710475d2','1c6c7ea0742c4dc8849b983c8437296e','03cd942d5566419bb39a1608580c6f8a'],checks:string[]=[],ops:Op[]=[];
const check=(v:unknown,s:string)=>{if(!v)throw Error(s);checks.push(s)};
for(const [q,t] of [[SystemIds.TYPES_PROPERTY,'Relation'],[p.factual,'Checkbox'],[p.source,'Relation'],[p.related,'Relation'],[p.support,'Relation'],[p.oppose,'Relation']] as const){const d:any=await gql('query($id:UUID!){property(id:$id){dataTypeName}}',{variables:{id:q}});check(d.property?.dataTypeName===t,`Live ${t}: ${q}`)}
const parent=id('parent');const d:any=await gql('query($id:UUID!,$name:String!){entity(id:$id){spaceIds}entitiesConnection(first:10,filter:{name:{isInsensitive:$name}}){nodes{id}pageInfo{hasNextPage}}}',{variables:{id:parent,name}});check(!d.entity?.spaceIds?.length,'Allocated parent ID unused');check(!d.entitiesConnection.pageInfo.hasNextPage&&!d.entitiesConnection.nodes.length,'Complete all-space parent discovery has no candidate');
for(const c of [...support,...oppose]){const x:any=await gql('query($id:UUID!,$space:UUID!){entity(id:$id){types{id}values(first:30,filter:{spaceId:{is:$space}}){nodes{propertyId boolean}pageInfo{hasNextPage}}}}',{variables:{id:c,space:target.spaceId}});check(x.entity?.types.some((t:any)=>t.id===p.claim)&&!x.entity.values.pageInfo.hasNextPage&&x.entity.values.nodes.some((v:any)=>v.propertyId===p.factual&&v.boolean===true),`Factual evidence available: ${c}`)}
const edge=(k:string,f:string,t:string,to:string)=>ops.push(...Ops.relations.create({id:id(`edge/${k}`),entityId:id(`relation/${k}`),fromEntity:f,type:t,toEntity:to,position:r[`position/${k}`]??(r[`position/${k}`]=Position.generate())}).ops);
ops.push(...Ops.entities.update({id:parent,name,description,values:[{property:p.factual,type:'boolean',value:false}]}).ops);edge('type',parent,SystemIds.TYPES_PROPERTY,p.claim);edge('source',parent,p.source,article);edge('study',parent,p.related,study);for(const c of [...support,...oppose]){edge(`related/${c}`,parent,p.related,c);edge(`related-reverse/${c}`,c,p.related,parent)}for(const c of support)edge(`support/${c}`,parent,p.support,c);for(const c of oppose)edge(`oppose/${c}`,parent,p.oppose,c);
const bytes=JSON.stringify(ops,(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('hex')}:typeof v==='bigint'?{$bigint:v.toString()}:v,2)+'\n',sha256=createHash('sha256').update(bytes).digest('hex'),batch={name:'Add teacher-coaching investment debate claim',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/${prefix}-ops.json`,sha256,journalPath:`${root}/${prefix}-publication.json`,validationPath:`${root}/${prefix}-validation.json`,entities:{parent,article,study,support,oppose},operationCount:ops.length};writeFileSync(rp,JSON.stringify(r,null,2)+'\n');writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/${prefix}-batch.json`,JSON.stringify(batch,null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),opsHash:sha256,checks,rationale:'The policy proposition is deliberately nonfactual. Overall pooled instruction and achievement estimates support the proposition; smaller or broader subgroup estimates challenge generalization. Every linked row is an overlapping subgroup from the same meta-analysis, not independent evidence.'},null,2)+'\n');console.log(JSON.stringify(batch,null,2));
