import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { Ops, type Op } from '@geoprotocol/geo-sdk';
import { geoGraphqlRequest as gql } from '../src/geo-api-client';
import { EDUCATION_PUBLICATION as target } from '../src/education-bounty';
const root='data/education',prefix='mssi-population-design',population='7a1f6d017895206e84e1988c0c74621e',design='8e46e3eff9dea2b55d32a5ca7de61938';
if(existsSync(`${root}/${prefix}-publication.json`))throw new Error('Preserve submitted payload.');
const study:Record<string,string>=JSON.parse(readFileSync(`${root}/mssi-2023-registry.json`,'utf8')),checks:string[]=[];
for(const [property,type] of [[population,'Text'],[design,'Text']] as const){const d:any=await gql('query($id:UUID!){property(id:$id){dataTypeName}}',{variables:{id:property}});if(d.property?.dataTypeName!==type)throw new Error(`Live ${type} schema required: ${property}`);checks.push(`Live ${type}: ${property}`);}
const current:any=await gql('query($id:UUID!,$space:UUID!){entity(id:$id){values(first:20,filter:{spaceId:{is:$space}}){nodes{propertyId}pageInfo{hasNextPage}}}}',{variables:{id:study.initiative,space:target.spaceId}});if(!current.entity||current.entity.values.pageInfo.hasNextPage)throw new Error('Complete current Initiative values required.');if(current.entity.values.nodes.some((v:any)=>v.propertyId===population||v.propertyId===design))throw new Error('MSSI population/design already exists.');checks.push('No duplicate MSSI population/design values');
const ops:Op[]=Ops.entities.update({id:study.initiative,values:[{property:population,type:'text',value:'514 eligible Community College of Baltimore County students identifying as male students of color: 304 offered MSSI and 210 assigned to usual CCBC services.'},{property:design,type:'text',value:'Individual-level randomized controlled evaluation from 2019 through spring 2022, with first-semester full-sample outcomes, cohorts-1-to-3 later follow-up, implementation research, and a six-term intent-to-treat service-cost analysis.'}]}).ops;
const bytes=JSON.stringify(ops,(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('hex')}:typeof v==='bigint'?{$bigint:v.toString()}:v,2)+'\n',sha256=createHash('sha256').update(bytes).digest('hex'),batch={name:'Add MSSI structured population and design facets',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/${prefix}-ops.json`,sha256,journalPath:`${root}/${prefix}-publication.json`,validationPath:`${root}/${prefix}-validation.json`,entities:{initiative:study.initiative},operationCount:ops.length};writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/${prefix}-batch.json`,JSON.stringify(batch,null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),opsHash:sha256,checks,scope:'MSSI evaluation population and design, not a description of all CCBC students or current implementation.'},null,2)+'\n');console.log(JSON.stringify(batch,null,2));
