import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {randomUUID,createHash} from 'node:crypto';
import {Ops,SystemIds,Position,type Op} from '@geoprotocol/geo-sdk';
import {geoGraphqlRequest as gql} from '../src/geo-api-client';
import {EDUCATION_PUBLICATION as target} from '../src/education-bounty';
const root='data/education',prefix='head-start-collection',read=(n:string)=>JSON.parse(readFileSync(`${root}/${n}.json`,'utf8')),review=read('head-start-collection-review');
if(existsSync(`${root}/${prefix}-publication.json`))throw Error('Preserve submitted payload');
if(!review.complete||review.claims.length!==38||review.claims.some((c:any)=>c.memberships.length)||Date.now()-Date.parse(review.checkedAt)>3600000)throw Error('Refresh review');
const p={estimate:'e500e2585a964d2c9df4a47b199616c3',unit:'8405509cc7354655a348591349a5f025',pvalue:'ba5f8fe9d1cd9a6094338d2f37b74a5e',estimand:'ba643714da274c37a340a7f8396198dc',factual:'da4a6c1f9d4446f9832ff3b49a4400ef',source:'49c5d5e1679a4dbdbfd33f618f227c94',related:'dfa6aebe1ca94bf29faccc4cc7afb24c',dataset:'0c4babfb43893486af827341bbf32e09'};
const val=(c:any,k:string)=>c.values.nodes.find((v:any)=>v.propertyId===k),hasSource=(c:any,id:string)=>c.relations.nodes.some((r:any)=>r.typeId===p.source&&r.toEntityId===id),archiveClaim='b63ab84606664cbfae0bd503922beff9';
const claims=review.claims.filter((c:any)=>c.id!==archiveClaim),cognitive=read('head-start-third-grade-cognitive-registry');
const ids=(prefix:string)=>Object.entries(cognitive).filter(([k])=>k.startsWith(prefix)).map(([,v])=>v);
const cognitiveFour=ids('claim/four-'),cognitiveThree=ids('claim/three-');if(cognitiveFour.length!==5||cognitiveThree.length!==5)throw Error('Cognitive grouping changed');
const iot=claims.filter((c:any)=>val(c,p.estimand)?.text==='Treatment on the treated (IOT)'),numeric=claims.filter((c:any)=>val(c,p.estimate)?.decimal!==null&&val(c,p.estimate)?.decimal!==undefined),itt=numeric.filter((c:any)=>!iot.includes(c));
const summary=claims.filter((c:any)=>!numeric.includes(c));const groups=[{key:'initial',name:'Access and findings through first grade',rows:summary.filter((c:any)=>hasSource(c,'a0d0dfad77074f10a028bf89ccebb17f')),numeric:false},{key:'followup',name:'Third-grade interpretation',rows:summary.filter((c:any)=>hasSource(c,'c183f28d3bc34439b797138e50d5c1f3')),numeric:false},{key:'cognitive-four',name:'Third-grade cognition: age-four entry cohort (ITT)',rows:cognitiveFour.map(id=>claims.find((c:any)=>c.id===id)),numeric:true},{key:'cognitive-three',name:'Third-grade cognition: age-three entry cohort (ITT)',rows:cognitiveThree.map(id=>claims.find((c:any)=>c.id===id)),numeric:true},{key:'other-itt',name:'Third-grade behavior, relationships and promotion (ITT)',rows:itt.filter((c:any)=>!cognitiveFour.includes(c.id)&&!cognitiveThree.includes(c.id)),numeric:true},{key:'iot',name:'Third-grade participation-adjusted counterparts (IOT)',rows:iot,numeric:true}];
if(JSON.stringify(groups.map(g=>g.rows.length))!==JSON.stringify([4,4,5,5,9,10])||new Set(groups.flatMap(g=>g.rows.map((c:any)=>c.id))).size!==37)throw Error('Review partition changed');
const additions=itt.filter((c:any)=>!val(c,p.estimand));if(additions.length!==14||additions.some((c:any)=>!val(c,p.unit)?.text?.includes('ITT')&&!(c.id==='c33e113e99dc4f6883a47d67d0842c35'&&val(c,'84dacbddca6a44079edb5e11a4c66b40')?.text==='Exhibit 4.3, printed p. 81.')))throw Error('Unverified missing estimand');
for(const c of claims)if(!val(c,p.factual)?.boolean)throw Error('Nonfactual member');
for(const [property,type] of [[SystemIds.BLOCKS,'Relation'],[SystemIds.TYPES_PROPERTY,'Relation'],[SystemIds.COLLECTION_ITEM_RELATION_TYPE,'Relation'],[SystemIds.DATA_SOURCE_TYPE_RELATION_TYPE,'Relation'],[SystemIds.PROPERTIES,'Relation'],[SystemIds.VIEW_PROPERTY,'Relation'],[p.source,'Relation'],[p.related,'Relation'],[SystemIds.MARKDOWN_CONTENT,'Text'],[p.estimate,'Decimal'],[p.unit,'Text'],[p.pvalue,'Text'],[p.estimand,'Text']]){const d:any=await gql('query($id:UUID!){property(id:$id){dataTypeName}}',{variables:{id:property}});if(d.property?.dataTypeName!==type)throw Error('Schema mismatch');}
const datasetCandidates=review.candidates.filter((c:any)=>c.types.some((t:any)=>t.name==='Dataset'));if(datasetCandidates.length!==1||datasetCandidates[0].id!=='3e4404bac6e842b598e0b0a809a4928f')throw Error('Unreviewed Dataset candidate');
const rp=`${root}/${prefix}-registry.json`,r:Record<string,string>=existsSync(rp)?read(`${prefix}-registry`):{},id=(k:string)=>r[k]??(r[k]=randomUUID().replaceAll('-','')),dataset=id('dataset'),ops:Op[]=[];
function rel(k:string,from:string,type:string,to:string,position?:string){const entityId=id(`relation/${k}`);ops.push(...Ops.relations.create({id:id(`edge/${k}`),entityId,fromEntity:from,type,toEntity:to,position:r[`position/${k}`]??(r[`position/${k}`]=position??Position.generate())}).ops);return entityId;}
const name='Head Start: randomized-access impacts through third grade';ops.push(...Ops.entities.update({id:dataset,name,description:'Findings from the national randomized Head Start access study and its follow-up through third grade. Entry-age cohorts, reporters and ITT versus participation-adjusted estimates remain distinct.'}).ops);rel('type',dataset,SystemIds.TYPES_PROPERTY,p.dataset);for(const a of ['a0d0dfad77074f10a028bf89ccebb17f','c183f28d3bc34439b797138e50d5c1f3'])rel(`source/${a}`,dataset,p.source,a);rel('program',dataset,p.related,'d03b32bd416443e49b9aa376e744cb03');rel('archive',dataset,p.related,'3e4404bac6e842b598e0b0a809a4928f');
const notes=id('notes');ops.push(...Ops.entities.update({id:notes,name:'Interpreting the findings',values:[{property:SystemIds.MARKDOWN_CONTENT,type:'text',value:'The comparison is an offer of Head Start access versus available alternative care, not universal absence of services. The 2010 report follows children through first grade; the 2012 report extends follow-up through third grade. Numeric rows use native scores or fractions, not a common standardized scale. Read each unit and reporter before interpreting the direction. ITT describes assignment; IOT adjusts for participation and is available here only for selected outcomes. Linked ITT/IOT pairs are alternate estimands from the same study, not independent replications. Some reported results meet only a 10% significance threshold. These selected published findings are not a complete transcription of every exhibit; missing SEs and sample counts remain unknown.'}]}).ops);rel('notes/type',notes,SystemIds.TYPES_PROPERTY,SystemIds.TEXT_BLOCK);rel('notes/attach',dataset,SystemIds.BLOCKS,notes,'a0');
for(const [i,g] of groups.entries()){const b=id(`table/${g.key}`);ops.push(...Ops.entities.update({id:b,name:g.name}).ops);rel(`${g.key}/type`,b,SystemIds.TYPES_PROPERTY,SystemIds.DATA_BLOCK);rel(`${g.key}/source`,b,SystemIds.DATA_SOURCE_TYPE_RELATION_TYPE,SystemIds.COLLECTION_DATA_SOURCE);const a=rel(`${g.key}/attach`,dataset,SystemIds.BLOCKS,b,`a${i+1}`);rel(`${g.key}/view`,a,SystemIds.VIEW_PROPERTY,SystemIds.TABLE_VIEW);for(const [j,col] of (g.numeric?[p.unit,p.estimate,p.pvalue]:[SystemIds.DESCRIPTION_PROPERTY]).entries())rel(`${g.key}/column/${j}`,a,SystemIds.PROPERTIES,col,`a${j}`);let pos=Position.generate();for(const c of g.rows){rel(`${g.key}/member/${c.id}`,b,SystemIds.COLLECTION_ITEM_RELATION_TYPE,c.id,pos);pos=Position.generateBetween(pos,null);}}
for(const c of additions)ops.push(...Ops.entities.update({id:c.id,values:[{property:p.estimand,type:'text',value:'Intention to treat (ITT)'}]}).ops);
// These category outcomes are probability differences in fraction units, not values already scaled to percentage points.
const unitCorrections=[{id:'c33e113e99dc4f6883a47d67d0842c35',unit:'Regression-adjusted teacher-reported probability difference (fraction scale), ITT, for the normal emotional-symptoms category at third grade; 4-year-old cohort; lower is less favorable.'},{id:'406a5d2ea1f44b128f3610c8fbd872e1',unit:'Regression-adjusted teacher-reported probability difference (fraction scale), treatment on the treated (IOT), for the normal emotional-symptoms category at third grade; 4-year-old cohort; lower is less favorable.'}];
for(const c of unitCorrections)ops.push(...Ops.entities.update({id:c.id,values:[{property:p.unit,type:'text',value:c.unit}]}).ops);
const members:any[]=[];let after:string|null=null;const seen=new Set<string>();do{const d:any=await gql('query($space:UUID!,$after:Cursor){entity(id:"2279edef1bbe479c872caeb72ee90022"){relations(first:10,after:$after,filter:{spaceId:{is:$space},typeId:{is:"a99f9ce12ffa4dac8c61f6310d46064a"}}){nodes{position toEntity{name}}pageInfo{hasNextPage endCursor}}}}',{variables:{space:target.spaceId,after}});const p=d.entity.relations;members.push(...p.nodes);if(!p.pageInfo.hasNextPage)break;if(!p.pageInfo.endCursor||seen.has(p.pageInfo.endCursor))throw Error('Catalog pagination');after=p.pageInfo.endCursor;seen.add(after!);}while(true);members.sort((a,b)=>a.position<b.position?-1:1);const at=members.findIndex(m=>m.toEntity.name.localeCompare(name,'en',{sensitivity:'base'})>0),prior=at<0?members.at(-1):members[at-1],next=at<0?null:members[at];rel('catalog/member','2279edef1bbe479c872caeb72ee90022',SystemIds.COLLECTION_ITEM_RELATION_TYPE,dataset,Position.generateBetween(prior?.position??null,next?.position??null));
for(const e of [dataset,notes,...groups.map(g=>id(`table/${g.key}`))]){const d:any=await gql('query($id:UUID!){entity(id:$id){spaceIds}}',{variables:{id:e}});if(d.entity?.spaceIds?.length)throw Error('Allocated ID occupied');}
const bytes=JSON.stringify(ops,(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('hex')}:v,2)+'\n',sha256=createHash('sha256').update(bytes).digest('hex'),batch={name:'Organize existing Head Start impact findings and complete ITT labels',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/${prefix}-ops.json`,sha256,journalPath:`${root}/${prefix}-publication.json`,validationPath:`${root}/${prefix}-validation.json`,datasetId:dataset,groups:groups.map(g=>({key:g.key,blockId:id(`table/${g.key}`),memberIds:g.rows.map((c:any)=>c.id)})),estimandAdditions:additions.map((c:any)=>c.id),excludedArchiveClaim:archiveClaim,operationCount:ops.length};
writeFileSync(rp,JSON.stringify(r,null,2)+'\n');writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/${prefix}-batch.json`,JSON.stringify({...batch,unitCorrections},null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),opsHash:sha256,checks:['37 existing factual impact Claims grouped; archive-access Claim excluded','Existing archive Dataset represents microdata access, not these report findings','All-space Head Start candidates and incoming memberships reviewed','14 ITT metadata additions corroborated by existing units and reviewed source exhibits','Two normal-category unit labels clarified as fraction-scale probability differences','No existing numbers, descriptions, sources or paired links overwritten','Native units, p-values, report/cohort/estimand partitions explicit']},null,2)+'\n');console.log(JSON.stringify({dataset,groups:groups.map(g=>g.rows.length),estimandAdditions:additions.length,operations:ops.length}));
