import { createHash, randomUUID } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { Ops, Position, SystemIds, type Op } from '@geoprotocol/geo-sdk';
import { geoGraphqlRequest as gql } from '../src/geo-api-client';
import { EDUCATION_PUBLICATION as target } from '../src/education-bounty';
const root='data/education',prefix='head-start-third-grade-paired-expansion';if(existsSync(`${root}/${prefix}-publication.json`))throw Error('Preserve submitted payload.');
type Row={key:string;outcome:string;ittName:string;ittDescription:string;itt:string;ittP:string;ittUnit:string;ittLocator:string;iotName:string;iotDescription:string;iot:string;iotP:string;iotUnit:string;iotLocator:string};const input=JSON.parse(readFileSync(`${root}/${prefix}.json`,'utf8')) as {source:string;scope:string;rows:Row[]};
const rp=`${root}/${prefix}-registry.json`,r:Record<string,string>=existsSync(rp)?JSON.parse(readFileSync(rp,'utf8')):{},id=(k:string)=>r[k]??(r[k]=randomUUID().replaceAll('-',''));const p={claim:'96f859efa1ca4b229372c86ad58b694b',factual:'da4a6c1f9d4446f9832ff3b49a4400ef',source:'49c5d5e1679a4dbdbfd33f618f227c94',related:'dfa6aebe1ca94bf29faccc4cc7afb24c',estimate:'e500e2585a964d2c9df4a47b199616c3',unit:'8405509cc7354655a348591349a5f025',locator:'84dacbddca6a44079edb5e11a4c66b40',pvalue:'ba5f8fe9d1cd9a6094338d2f37b74a5e',estimand:'ba643714da274c37a340a7f8396198dc'};
const article='c183f28d3bc34439b797138e50d5c1f3',initiative=JSON.parse(readFileSync(`${root}/head-start-registry.json`,'utf8')).initiative,checks:string[]=[],ops:Op[]=[];const dec=(s:string)=>{const[a,b='']=s.split('.'),n=a.startsWith('-'),digits=`${n?a.slice(1):a}${b}`;return{property:p.estimate,type:'decimal' as const,exponent:-b.length,mantissa:{type:'i64' as const,value:BigInt(`${n?'-':''}${digits}`)}}};
for(const[q,t]of [[SystemIds.TYPES_PROPERTY,'Relation'],[p.factual,'Checkbox'],[p.source,'Relation'],[p.related,'Relation'],[p.estimate,'Decimal'],[p.unit,'Text'],[p.locator,'Text'],[p.pvalue,'Text'],[p.estimand,'Text']]as const){const x:any=await gql('query($id:UUID!){property(id:$id){dataTypeName}}',{variables:{id:q}});if(x.property?.dataTypeName!==t)throw Error(`Schema mismatch ${q}`);checks.push(`Live ${t}: ${q}`)}
for(const row of input.rows)for(const[k,name]of [['itt',row.ittName],['iot',row.iotName]]as const){const claim=id(`claim/${row.key}/${k}`),x:any=await gql('query($id:UUID!,$name:String!){entity(id:$id){spaceIds}entitiesConnection(first:10,filter:{name:{isInsensitive:$name}}){nodes{id}pageInfo{hasNextPage}}}',{variables:{id:claim,name}});if(x.entity?.spaceIds?.length||x.entitiesConnection.nodes.length||x.entitiesConnection.pageInfo.hasNextPage)throw Error(`Identity collision or incomplete discovery ${row.key}/${k}`);checks.push(`Complete all-space identity discovery: ${row.key}/${k}`)}
const live:any=await gql('query($id:UUID!){entity(id:$id){name types{id}}}',{variables:{id:article}});if(live.entity?.name!=='Third Grade Follow-up to the Head Start Impact Study: Final Report'||!live.entity.types.some((x:any)=>x.id==='a2a5ed0cacef46b1835de457956ce915'))throw Error('Head Start Article unavailable.');
const edge=(k:string,f:string,t:string,to:string)=>ops.push(...Ops.relations.create({id:id(`edge/${k}`),entityId:id(`relation/${k}`),fromEntity:f,type:t,toEntity:to,position:r[`position/${k}`]??(r[`position/${k}`]=Position.generate())}).ops);const create=(key:string,name:string,description:string,value:string,pvalue:string,unit:string,locator:string,estimand:string)=>{const claim=id(`claim/${key}`);ops.push(...Ops.entities.update({id:claim,name,description,values:[{property:p.factual,type:'boolean',value:true},dec(value),{property:p.unit,type:'text',value:unit},{property:p.estimand,type:'text',value:estimand},{property:p.locator,type:'text',value:locator},{property:p.pvalue,type:'text',value:pvalue}]}).ops);edge(`${key}/type`,claim,SystemIds.TYPES_PROPERTY,p.claim);edge(`${key}/source`,claim,p.source,article);edge(`${key}/initiative`,claim,p.related,initiative);return claim};
for(const row of input.rows){const itt=create(`${row.key}/itt`,row.ittName,row.ittDescription,row.itt,row.ittP,row.ittUnit,row.ittLocator,'Intention to treat (ITT)'),iot=create(`${row.key}/iot`,row.iotName,row.iotDescription,row.iot,row.iotP,row.iotUnit,row.iotLocator,'Treatment on the treated (IOT)');edge(`${row.key}/pair`,itt,p.related,iot);edge(`${row.key}/pair-reverse`,iot,p.related,itt)}
const bytes=JSON.stringify(ops,(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('hex')}:typeof v==='bigint'?{$bigint:v.toString()}:v,2)+'\n',sha256=createHash('sha256').update(bytes).digest('hex'),batch={name:'Add paired Head Start third-grade ITT and IOT findings',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/${prefix}-ops.json`,sha256,journalPath:`${root}/${prefix}-publication.json`,validationPath:`${root}/${prefix}-validation.json`,entities:{article,initiative,claims:Object.fromEntries(input.rows.flatMap(row=>[['itt',id(`claim/${row.key}/itt`)],['iot',id(`claim/${row.key}/iot`)]].map(([k,v])=>[`${row.key}/${k}`,v])))},operationCount:ops.length};writeFileSync(rp,JSON.stringify(r,null,2)+'\n');writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/${prefix}-batch.json`,JSON.stringify(batch,null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),opsHash:sha256,checks,source:input.source,scope:input.scope},null,2)+'\n');console.log(JSON.stringify(batch,null,2));
