import {existsSync,readFileSync,writeFileSync} from 'node:fs';
import {createHash,randomUUID} from 'node:crypto';
import {Ops,Position,SystemIds,type Op} from '@geoprotocol/geo-sdk';
import {geoGraphqlRequest as gql} from '../src/geo-api-client';
import {EDUCATION_PUBLICATION as target} from '../src/education-bounty';

const root='data/education', registryPath=`${root}/head-start-registry.json`;
const registry:Record<string,string>=existsSync(registryPath)?JSON.parse(readFileSync(registryPath,'utf8')):{};
const id=(key:string)=>registry[key]??(registry[key]=randomUUID().replaceAll('-',''));
const props={claim:'96f859efa1ca4b229372c86ad58b694b',initiative:'d272f19cef87485fb83e26fb68957395',article:'a2a5ed0cacef46b1835de457956ce915',factual:'da4a6c1f9d4446f9832ff3b49a4400ef',source:'49c5d5e1679a4dbdbfd33f618f227c94',related:'dfa6aebe1ca94bf29faccc4cc7afb24c',supports:'1dc6a843458848198e7a6e672268f811',opposes:'4e6ec5d14292498a84e5f607ca1a08ce',topics:'806d52bc27e94c9193c057978b093351',url:'412ff593e9154012a43d4c27ec5c68b6'};
const ops:Op[]=[],checks:string[]=[],edges:any[]=[];
const rel=(key:string,from:string,type:string,to:string)=>{
 const position=registry[`position/${key}`]??(registry[`position/${key}`]=Position.generate());
 ops.push(...Ops.relations.create({id:id(`edge/${key}`),entityId:id(`edge-entity/${key}`),fromEntity:from,type,toEntity:to,position}).ops);edges.push({from,type,to});
};
const check=(ok:unknown,label:string)=>{if(!ok)throw Error(label);checks.push(label);};
const exact=JSON.parse(readFileSync(`${root}/discovery/head-start-impact-study-final-report.json`,'utf8'));
const exactProgram=JSON.parse(readFileSync(`${root}/discovery/head-start.json`,'utf8'));
check(exact.complete&&exact.nodes.length===0,'Complete all-space exact Article-name discovery found no candidate');
check(exactProgram.complete&&exactProgram.nodes.length===0,'Complete all-space exact Initiative-name discovery found no candidate');
for(const [property,type] of [[SystemIds.TYPES_PROPERTY,'Relation'],[props.source,'Relation'],[props.related,'Relation'],[props.supports,'Relation'],[props.opposes,'Relation'],[props.topics,'Relation'],[props.factual,'Checkbox']]){
 const d:any=await gql('query($id:UUID!){property(id:$id){dataTypeName}}',{variables:{id:property}});check(d.property?.dataTypeName===type,`Live property type ${property}`);
}
const article=id('article'),initiative=id('initiative'),debate=id('claim/expansion-debate');
const findings=[
 {key:'access-center-care',name:'In the Head Start Impact Study, children offered Head Start were twice as likely as controls to use a center-based program in spring 2003.',description:'This randomized-study finding concerns the early care arrangement produced by an offer of Head Start, not a comparison with no alternative services. The report includes Head Start, preschool and child care in its center-based category.',role:'supports'},
 {key:'early-outcomes',name:'The Head Start Impact Study found favorable cognitive and health impacts after one program year, with more significant findings for the 3-year-old cohort.',description:'The final report describes end-of-program-year impacts for the randomized access comparison. It does not justify treating every measured outcome, later follow-up, or implementation setting as favorable.',role:'supports'},
 {key:'first-grade',name:'By the end of first grade, the Head Start Impact Study found few statistically significant differences for the sample as a whole.',description:'The report follows children from program entry through first grade and reports this result for the randomized groups as a whole. It does not establish that every subgroup, unmeasured outcome, or later-life outcome was zero.',role:'opposes'},
 {key:'comparison-care',name:'The Head Start Impact Study compared Head Start access with a mix of alternative care arrangements, not with a universal no-service condition.',description:'About 17% of the 3-year-old control group and 14% of the 4-year-old control group entered Head Start during the first year; the report therefore distinguishes intent-to-treat access estimates from estimates adjusted for no-shows and crossovers.',role:'related'}
];
for(const e of [article,initiative,debate,...findings.map(x=>id(`claim/${x.key}`))]){
 const d:any=await gql('query($id:UUID!){entity(id:$id){spaceIds}}',{variables:{id:e}});check(!d.entity?.spaceIds?.length,`Persistent ID is unoccupied: ${e}`);
}
ops.push(...Ops.entities.update({id:article,name:'Head Start Impact Study: Final Report',description:'A federal randomized evaluation of Head Start access, following children through the end of first grade.',values:[{property:props.url,type:'text',value:'https://acf.gov/opre/report/head-start-impact-study-final-report'}]}).ops);rel('article/type',article,SystemIds.TYPES_PROPERTY,props.article);
ops.push(...Ops.entities.update({id:initiative,name:'Head Start',description:'A US federal early-childhood program serving children from low-income families. The linked study evaluates access against the care arrangements available to its control group.',values:[{property:props.url,type:'text',value:'https://acf.gov/opre/report/head-start-impact-study-final-report'}]}).ops);rel('initiative/type',initiative,SystemIds.TYPES_PROPERTY,props.initiative);rel('initiative/source',initiative,props.source,article);rel('initiative/article',initiative,props.related,article);
ops.push(...Ops.entities.update({id:debate,name:'Does the Head Start Impact Study support expanding Head Start?',description:'This policy question is open for debate. Linked factual Claims separate early outcomes and care access from the study’s limited sample-wide first-grade differences.',values:[{property:props.factual,type:'boolean',value:false}]}).ops);rel('debate/type',debate,SystemIds.TYPES_PROPERTY,props.claim);rel('debate/source',debate,props.source,article);rel('debate/initiative',debate,props.related,initiative);rel('debate/topic',debate,props.topics,'0df9fad9098d4b11bacb9af0f7a79182');
for(const row of findings){const claim=id(`claim/${row.key}`);ops.push(...Ops.entities.update({id:claim,name:row.name,description:row.description,values:[{property:props.factual,type:'boolean',value:true}]}).ops);rel(`claim/${row.key}/type`,claim,SystemIds.TYPES_PROPERTY,props.claim);rel(`claim/${row.key}/source`,claim,props.source,article);rel(`claim/${row.key}/initiative`,claim,props.related,initiative);rel(`claim/${row.key}/topic`,claim,props.topics,'0df9fad9098d4b11bacb9af0f7a79182');if(row.role==='supports')rel(`claim/${row.key}/supports`,claim,props.supports,debate);if(row.role==='opposes')rel(`claim/${row.key}/opposes`,claim,props.opposes,debate);if(row.role==='related')rel(`claim/${row.key}/debate`,claim,props.related,debate);}
const bytes=JSON.stringify(ops,(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('hex')}:typeof v==='bigint'?{$bigint:v.toString()}:v,2)+'\n',sha256=createHash('sha256').update(bytes).digest('hex');
const batch={name:'Add Head Start Impact Study evidence and expansion debate',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/head-start-ops.json`,sha256,journalPath:`${root}/head-start-publication.json`,validationPath:`${root}/head-start-validation.json`,entities:{article,initiative,debate,findings:Object.fromEntries(findings.map(x=>[x.key,id(`claim/${x.key}`)]))},operationCount:ops.length};
writeFileSync(registryPath,JSON.stringify(registry,null,2)+'\n');writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/head-start-batch.json`,JSON.stringify(batch,null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),opsHash:sha256,checks,edges,source:{title:'Head Start Impact Study: Final Report',publisher:'Administration for Children and Families',year:2010,url:'https://acf.gov/opre/report/head-start-impact-study-final-report',sample:'4,667 children across 23 states; follow-up through first grade',limitations:'Access was compared with available alternative care; no-shows and crossovers require separate ITT and treatment-on-treated interpretation.'}},null,2)+'\n');console.log(JSON.stringify(batch,null,2));
