import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { geoGraphqlRequest as gql } from '../src/geo-api-client';

const root = 'data/education'; const prefix = 'ethnic-studies-collection';
if (existsSync(`${root}/${prefix}-batch.json`)) throw new Error('Preserve existing prepared batch');
const sourceId = '7cf51d06726242b88157ca3ea1f5b228'; const initiativeId = 'd597ffb8910b46158a2eb2c20ad4e48b'; const catalogId = '2279edef1bbe479c872caeb72ee90022';
const decimal = 'e500e2585a964d2c9df4a47b199616c3'; const integer = '210e9b352b454d6eb7a32906d24d3c8d'; const context = '8405509cc7354655a348591349a5f025'; const locator = '84dacbddca6a44079edb5e11a4c66b40';
const rows = [['385e7cb36c144d04b09508c0d49876a2', 'GPA', '1.4'], ['115917ad7cba4ee38e591b93a5c1426d', 'credits earned', '23'], ['8197239bfd0f417ca57263877d8c2021', 'attendance', '0.21']];
const live = await Promise.all(rows.map(async ([id]) => { const d: any = await gql('query($id:UUID!){entity(id:$id){name description values(first:50){nodes{propertyId text}}}}', { variables: { id } }); if (!d.entity) throw new Error(`Missing Claim ${id}`); return d.entity; }));
const plan = { version: 1, key: prefix, spaceId: 'dac259bad48a11adf97fe36857d85206', bounty: 'debce2de46094f299ee8e89fe244a9dc', catalogId, name: 'San Francisco ethnic-studies RDD findings', description: 'Local-IV estimates from the San Francisco ethnic-studies curriculum evaluation.', notes: 'Rows reuse three Claims from the RDD study near the eighth-grade GPA 2.0 cutoff. Keep this pilot threshold design separate from the later districtwide expansion study.', sourceIds: [sourceId], relatedIds: [initiativeId], groups: [{ key: 'findings', name: 'Ethnic-studies local-IV findings', columns: [{ id: decimal, dataType: 'Decimal' }, { id: integer, dataType: 'Integer' }, { id: context, dataType: 'Text' }], members: rows.map(([id]) => id) }] };
const facts = rows.map(([id, label, estimate], i) => { const values = live[i].values.nodes; const get = (property: string) => values.find((v: any) => v.propertyId === property)?.text; return { id, sourceId, locator: get(locator), classification: 'observed', context: 'Local-IV estimates from the San Francisco ethnic-studies RDD near the eighth-grade GPA 2.0 cutoff; the three outcomes are from one pilot study.', name: live[i].name, description: live[i].description, values: [{ propertyId: decimal, field: 'decimal', value: estimate }, { propertyId: integer, field: 'integer', value: '1404' }, { propertyId: context, field: 'text', value: get(context) }] }; });
const bytes = (value: unknown) => JSON.stringify(value, null, 2) + '\n'; const hash = (value: string | Uint8Array) => createHash('sha256').update(Buffer.from(value)).digest('hex'); const planBytes = bytes(plan); const factsBytes = bytes(facts); const discoveryBytes = readFileSync(`${root}/${prefix}-discovery.json`); const notesBytes = readFileSync('docs/ethnic-studies-study-notes.md');
const review = { version: 1, checkedAt: new Date().toISOString(), reviewer: 'publisher preparation review', planHash: hash(planBytes), factsHash: hash(factsBytes), sources: [{ path: 'docs/ethnic-studies-study-notes.md', sha256: hash(notesBytes), sourceId, version: 'Dee and Penner (2017), local-IV RDD study' }], discovery: { path: `${root}/${prefix}-discovery.json`, sha256: hash(discoveryBytes) }, decisions: { source: { status: 'accepted', rationale: 'Article identity, DOI and RDD source are documented.' }, identity: { status: 'accepted', rationale: 'Complete all-space discovery found only the expected Article and zero incoming memberships.' }, content: { status: 'accepted', rationale: 'Facts reuse live Claims and their exact source locators, values and contexts; later expansion rows remain separate.' } } };
writeFileSync(`${root}/${prefix}-plan.json`, planBytes); writeFileSync(`${root}/${prefix}-facts.json`, factsBytes); writeFileSync(`${root}/${prefix}-review.json`, bytes(review)); console.log(JSON.stringify({ claims: rows.length, plan: `${root}/${prefix}-plan.json`, facts: `${root}/${prefix}-facts.json`, review: `${root}/${prefix}-review.json` }, null, 2));
