import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {createHash,randomUUID} from 'node:crypto';
import {Ops,Position,SystemIds,type Op} from '@geoprotocol/geo-sdk';
import {geoGraphqlRequest as gql} from '../src/geo-api-client';
import {EDUCATION_PUBLICATION as target} from '../src/education-bounty';
const root='data/education',expansion=process.argv.includes('--expansion'),prefix=`saga-year2-${expansion?'expansion':'pilot'}`;
const read=(n:string)=>JSON.parse(readFileSync(`${root}/${n}.json`,'utf8')),hash=(v:string|Buffer)=>createHash('sha256').update(v).digest('hex');
if(existsSync(`${root}/${prefix}-publication.json`))throw new Error('Preserve submitted payload');
const model=read('saga-year2-model'),source=read('saga-year2-transcription'),extraction=read('saga-year2-extraction'),saga=read('saga-registry'),schema=read('saga-pooled-model');
const registry:Record<string,string>=existsSync(`${root}/saga-year2-registry.json`)?read('saga-year2-registry'):{};
const id=(key:string)=>{if(!registry[key]){registry[key]=randomUUID().replaceAll('-','');writeFileSync(`${root}/saga-year2-registry.json`,JSON.stringify(registry,null,2)+'\n');}return registry[key]!;};
const ops:Op[]=[],checks:string[]=[],created:any[]=[],identities:any[]=[],copies:any[]=[];
const check=(pass:unknown,label:string)=>{if(!pass)throw new Error(label);checks.push(label);};
const text=(property:string,value:string)=>({property,type:'text' as const,value});
const decimal=(property:string,value:string)=>({property,type:'decimal' as const,exponent:-(value.split('.')[1]?.length??0),mantissa:{type:'i64' as const,value:BigInt(value.replace('.',''))}});
function rel(key:string,from:string,type:string,to:string,position?:string){const entityId=id(`relation-entity/${key}`);ops.push(...Ops.relations.create({id:id(`relation/${key}`),entityId,fromEntity:from,type,toEntity:to,...(position?{position}:{})}).ops);return entityId;}
async function create(key:string,name:string,type:string,description?:string,values:any[]=[]){
 const data=await gql<any>('query($name:String!){entitiesConnection(first:10,filter:{name:{isInsensitive:$name}}){nodes{id name spaceIds}pageInfo{hasNextPage}}}',{variables:{name}});identities.push({name,...data.entitiesConnection});check(!data.entitiesConnection.pageInfo.hasNextPage&&!data.entitiesConnection.nodes.length,`Exact all-space identity ${key}`);
 check(!description||description.length<=350,`Concise description ${key}`);const entity=id(key),probe=await gql<any>('query($id:UUID!){entity(id:$id){name types{id}}}',{variables:{id:entity}});check(!probe.entity||(!probe.entity.name&&!probe.entity.types.length),`Unused stable ID ${key}`);
 ops.push(...Ops.entities.update({id:entity,name,...(description?{description}:{}),values}).ops);rel(`${key}/type`,entity,SystemIds.TYPES_PROPERTY,type);created.push({key,id:entity,name,type});
}
check(hash(readFileSync(source.sourcePdf))===extraction.sourceSha256&&hash(readFileSync(`${root}/saga-year2-transcription.json`))===extraction.transcriptionSha256,'Verified source unchanged');
check(extraction.records.length===15&&extraction.checks.reduce((n:number,c:any)=>n+c.numericCellsChecked,0)===53,'Complete Table 6 source');
check(read('statistic-property-discovery').queries.every((q:any)=>q.complete),'Complete existing bound-property discovery');
if(expansion){check(read('saga-year2-pilot-index-verification').passed&&read('saga-year2-pilot-browser-verification').passed,'New bound property pilot indexed and rendered');}
const pilotKey='s1/t6/B/cps-math/persistentBound',records=extraction.records.filter((r:any)=>expansion?r.key!==pilotKey:r.key===pilotKey);
const broad:any[]=[];let after:string|null=null;const cursors=new Set<string>();
do{const data:any=await gql<any>('query($after:Cursor){entitiesConnection(first:20,after:$after,filter:{name:{includesInsensitive:"Saga"}}){nodes{id name description spaceIds}pageInfo{hasNextPage endCursor}}}',{variables:{after}});const p=data.entitiesConnection;broad.push(...p.nodes);if(p.pageInfo.hasNextPage){check(!!p.pageInfo.endCursor&&!cursors.has(p.pageInfo.endCursor),'Discovery cursor advances');cursors.add(p.pageInfo.endCursor);after=p.pageInfo.endCursor;}else after=null;}while(after);
const known=new Set<string>(expansion?[...read('saga-year2-pilot-validation').created.map((e:any)=>e.id),read('saga-year2-pilot-publication').proposalId]:[]);
const suspects=broad.filter(n=>!known.has(n.id)&&/bound|per.year|first.stage|participation effect|year two|year 2/i.test(n.name??''));
writeFileSync(`${root}/${prefix}-broad-discovery.json`,JSON.stringify({checkedAt:new Date().toISOString(),complete:true,nodes:broad,suspects},null,2)+'\n');check(!suspects.length,`Review Table 6 candidates ${JSON.stringify(suspects)}`);
const properties=new Map<string,string>([[saga['property/estimate'],'Decimal'],[saga['property/se'],'Decimal'],[saga['property/study'],'Integer'],[schema.sampleProperty,'Integer'],[schema.factualProperty,'Checkbox'],...[SystemIds.NAME_PROPERTY,SystemIds.DESCRIPTION_PROPERTY,SystemIds.MARKDOWN_CONTENT,schema.outcomeProperty,saga['property/unit'],saga['property/estimand'],saga['property/locator'],saga['property/followup']].map(p=>[p,'Text'] as [string,string]),...[SystemIds.TYPES_PROPERTY,SystemIds.DATA_TYPE,SystemIds.BLOCKS,SystemIds.DATA_SOURCE_TYPE_RELATION_TYPE,SystemIds.COLLECTION_ITEM_RELATION_TYPE,SystemIds.VIEW_PROPERTY,SystemIds.PROPERTIES,schema.sourceProperty,schema.relatedProperty,saga['property/entries']].map(p=>[p,'Relation'] as [string,string])]);
if(expansion)properties.set(id('property/bound'),'Decimal');
for(const [p,t] of properties){const data=await gql<any>('query($id:UUID!){property(id:$id){dataTypeName}}',{variables:{id:p}});check(data.property?.dataTypeName===t,`Live datatype ${p}`);}
for(const type of [schema.claimType,SystemIds.PROPERTY,SystemIds.DATA_BLOCK,SystemIds.TEXT_BLOCK]){const data=await gql<any>('query($id:UUID!){entity(id:$id){types{id}}}',{variables:{id:type}});check(data.entity?.types.some((t:any)=>t.id===SystemIds.SCHEMA_TYPE),`Existing type ${type}`);}
if(!expansion){await create('property/bound',model.proposedBoundProperty.name,SystemIds.PROPERTY,model.proposedBoundProperty.description);rel('property/bound/datatype',id('property/bound'),SystemIds.DATA_TYPE,SystemIds.DECIMAL);}
for(const [i,g] of model.groups.entries()){
 if(expansion?i===2:i!==2)continue;
 const key=`table/${i}`;await create(key,`Saga year-two analysis: ${g.kind}`,SystemIds.DATA_BLOCK);
 rel(`${key}/source`,id(key),SystemIds.DATA_SOURCE_TYPE_RELATION_TYPE,SystemIds.COLLECTION_DATA_SOURCE);
 const attachment=rel(`${key}/attachment`,model.datasetId,SystemIds.BLOCKS,id(key),`e${i+1}`);rel(`${key}/view`,attachment,SystemIds.VIEW_PROPERTY,SystemIds.TABLE_VIEW);
 let last:string|null=null;for(const [j,p] of [schema.outcomeProperty,saga['property/estimand'],i>=2?id('property/bound'):saga['property/estimate'],saga['property/se'],schema.sampleProperty,saga['property/unit'],saga['property/locator']].entries()){const position=Position.generateBetween(last,null);last=position;rel(`${key}/column/${j}`,attachment,SystemIds.PROPERTIES,p as string,position);}
}
for(const [ordinal,r] of records.entries()){
 const i=model.groups.findIndex((g:any)=>g.kind===r.kind),g=model.groups[i],key=`statistic/${r.key}`;check(i>=0,'Reviewed statistic kind');
 let name=i===0?`Saga's Chicago study 1 estimated that offering tutoring increased participation by ${r.value} years.`:i===1?`Saga's Chicago study 1 estimated a year-two ${r.measure} effect of ${r.value} ${r.unit} per year of tutoring.`:`Saga's Chicago study 1 reported a year-two bound of ${r.value} ${r.unit} for ${r.measure}, assuming ${i===2?'only first-year benefits persist':'only two-year participation contributes'}.`;
 if(i===0&&r.unit==='proportion difference')name=`Saga's Chicago study 1 estimated that offering tutoring increased ${r.measureKey==='one-plus'?'participation for at least one year':'participation for two years'} by ${(Number(r.value)*100).toFixed(1)} percentage points.`;
 if(r.measureKey==='math-failure')name=i===1?`Saga's Chicago study 1 estimated ${(Math.abs(Number(r.value))*100).toFixed(1)} percentage points fewer math courses failed per year of tutoring, measured in year two.`:`Saga's Chicago study 1 reported a ${(Math.abs(Number(r.value))*100).toFixed(1)}-percentage-point bound on reducing math-course failure, assuming ${i===2?'only first-year benefits persist':'only two-year participation contributes'}.`;
 const first=`Table 6, p. 753 reports ${r.value} (SE ${r.standardError}; N=${r.n}${r.reportedFdrQ?`; FDR q=${r.reportedFdrQ}`:''}).`;
 const second=i===0?'This measures how the randomized offer changed participation, not an academic outcome.':i===1?'This is a weighted per-year effect measured in year two, not a separately randomized dose comparison.':i===2?'This bound assumes nonnegative benefits and zero incremental second-year benefit; it is not a point effect or confidence limit.':'This bound assumes nonnegative benefits and no persistence for first-year-only participants; it is not a point effect or confidence limit.';
 const description=`${first} ${second}`;copies.push({key,name,description,kind:r.kind});
 await create(key,name,schema.claimType,description,[text(schema.outcomeProperty,r.measure),decimal(i>=2?id('property/bound'):saga['property/estimate'],r.value),decimal(saga['property/se'],r.standardError),{property:saga['property/study'],type:'integer',value:1n},{property:schema.sampleProperty,type:'integer',value:BigInt(r.n)},{property:schema.factualProperty,type:'boolean',value:true},text(saga['property/unit'],r.unit),text(saga['property/estimand'],g.estimand),text(saga['property/followup'],r.followup),text(saga['property/locator'],`Table 6, panel ${r.panel}; printed p. 753 (PDF p. 16)`) ]);
 rel(`${key}/source`,id(key),schema.sourceProperty,model.articleId);rel(`${key}/study`,id(key),schema.relatedProperty,model.studyId);rel(`${key}/entry`,model.datasetId,saga['property/entries'],id(key));rel(`${key}/item`,id(`table/${i}`),SystemIds.COLLECTION_ITEM_RELATION_TYPE,id(key),`a${String(ordinal).padStart(3,'0')}`);
}
if(!expansion){
 const notes='## What Table 6 identifies\n\nStudy 1 randomized the original tutoring offer, not each additional year of participation separately. First-stage estimates describe participation responses to that offer. The academic model estimates a weighted effect per year, observed in the second postrandomization school year.\n\n## Bounds and assumptions\n\nThe authors bound persistent first-year and two-year-participation benefits by assuming both benefits are nonnegative and setting the other component to zero. These are identification bounds, not confidence limits or separate point effects. A negative course-failure bound preserves the reported beneficial reduction direction; it is not an ordinary upper numerical endpoint. Each reported standard error describes its estimator; the FDR q-values can differ across specifications.\n\n## Comparison limits\n\nDo not combine participation first stages, per-year mixtures and bounds as interchangeable academic effects. The graph stores bounds in a distinct numeric property. All records refer to the same Study 1, and add no independent experiment.\n\n## Source\n\n[Final AER article](https://doi.org/10.1257/aer.20210434), Table 6 on printed page 753, with identification discussion on pages 751–752.';
 await create('notes','Saga year-two identification and bound assumptions',SystemIds.TEXT_BLOCK,undefined,[text(SystemIds.MARKDOWN_CONTENT,notes)]);rel('notes/attachment',model.datasetId,SystemIds.BLOCKS,id('notes'),'e0');
}
const bytes=JSON.stringify(ops,(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('hex')}:typeof v==='bigint'?{$bigint:String(v)}:v,2)+'\n',sha256=hash(bytes),encoded=JSON.parse(bytes);
check(encoded.every((o:any)=>['updateEntity','createRelation'].includes(o.type)&&!o.unset?.length),'No deletions');
for(const e of created)check(encoded.some((o:any)=>o.type==='createRelation'&&o.from.$bytes===e.id&&o.relationType.$bytes===SystemIds.TYPES_PROPERTY),'Every new entity typed');
for(const r of records.filter((r:any)=>r.kind.includes('bound'))){const sets=encoded.filter((o:any)=>o.type==='updateEntity'&&o.id.$bytes===id(`statistic/${r.key}`)).flatMap((o:any)=>o.set);check(!sets.some((s:any)=>[saga['property/estimate'],'60e8b11660d04c94b1e1ebe4321bedcf','2b6e1e8fa3324dc08e9b9051f3dee669'].includes(s.property.$bytes)),'Bounds have no effect or CI endpoint values');}
const batch={name:expansion?'Complete Saga year-two participation effects and bounds':'Add a source-reported Saga persistence bound',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/${prefix}-ops.json`,sha256,operationCount:ops.length,journalPath:`${root}/${prefix}-publication.json`,validationPath:`${root}/${prefix}-validation.json`};
writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/${prefix}-batch.json`,JSON.stringify(batch,null,2)+'\n');writeFileSync(`${root}/${prefix}-copy-review.json`,JSON.stringify(copies,null,2)+'\n');writeFileSync(`${root}/${prefix}-identity.json`,JSON.stringify(identities,null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),opsHash:sha256,checks,created},null,2)+'\n');console.log(JSON.stringify({operations:ops.length,records:copies.length,checks:checks.length,sha256}));
