import {readFileSync,writeFileSync} from 'node:fs';
import {geoGraphqlRequest as gql} from '../src/geo-api-client';
const root='data/education',space='dac259bad48a11adf97fe36857d85206',read=(n:string)=>JSON.parse(readFileSync(`${root}/${n}.json`,'utf8'));
if(!read('original-program-aliases-index-verification').passed)throw Error('Verify route batch first');
const review=read('original-program-alias-review'),ledger=read('original-field-reconciliation'),crosswalk=read('source-to-geo-crosswalk');
const report:any={checkedAt:new Date().toISOString(),programs:[],source:null};
const p={name:'a126ca530c8e48d5b88882c734c38935',slug:'b0305ef28312c519d954bc0efe22f013',url:'412ff593e9154012a43d4c27ec5c68b6',authors:'91a9e2f6e51a48f7997661de8561b690',sources:'49c5d5e1679a4dbdbfd33f618f227c94'};
async function state(id:string){const d:any=await gql('query($id:UUID!,$space:UUID!){entity(id:$id){values(first:30,filter:{spaceId:{is:$space}}){nodes{propertyId text}pageInfo{hasNextPage}}relations(first:40,filter:{spaceId:{is:$space}}){nodes{id typeId toEntityId position}pageInfo{hasNextPage}}}}',{variables:{id,space}});if(!d.entity||d.entity.values.pageInfo.hasNextPage||d.entity.relations.pageInfo.hasNextPage)throw Error('Incomplete verification');return {id,...d.entity};}
function map(key:string,field:string,id:string,propertyId:string|null,reason:string,extra:any={}){const row=ledger.rows.find((r:any)=>r.migrationKey===key);const f=row.fields.find((f:any)=>f.sourceField===field);f.status='existing-and-readable';f.verifiedGeoMappings=[{entityId:id,spaceId:space,propertyId,identityOnly:propertyId===null,evidence:'original-program-aliases-current-verification.json',checkedAt:report.checkedAt,...extra}];f.reviewReason=reason;row.candidateGeoIds=[id];}
for(const accepted of review.accepted){const row=ledger.rows.find((r:any)=>r.migrationKey===`initiatives:${accepted.originalId}`);const live=await state(accepted.entityId);const slug=row.fields.find((f:any)=>f.sourceField==='slug').sourceValue;
 if(!live.values.nodes.some((v:any)=>v.propertyId===p.name&&v.text===accepted.expectedName)||!live.values.nodes.some((v:any)=>v.propertyId===p.slug&&v.text===slug))throw Error('Route/name mismatch');
 report.programs.push(live);for(const [field,property] of [['id',null],['name',p.name],['slug',p.slug]] as const)map(row.migrationKey,field,accepted.entityId,property,accepted.reason);
 const c=crosswalk.rows.find((r:any)=>r.migrationKey===row.migrationKey);c.candidateGeoIds=[accepted.entityId];c.candidateSpaces=[space];c.decision='reuse-existing';c.decisionRationale=accepted.reason;c.lastCheckedAt=report.checkedAt;
}
const source=await state(review.sourceAlias.entityId);report.source=source;
if(!source.values.nodes.some((v:any)=>v.propertyId===p.url&&v.text===review.sourceAlias.doi))throw Error('Source DOI mismatch');
const authorRegistry=read('original-bibliography-authors-registry').ids,expectedAuthors=['Matthew A. Kraft','David Blazar','Dylan Hogan'].map(n=>authorRegistry[`author/${n}`]);
const actual=source.relations.nodes.filter((r:any)=>r.typeId===p.authors).sort((a:any,b:any)=>a.position.localeCompare(b.position)).map((r:any)=>r.toEntityId);if(JSON.stringify(actual)!==JSON.stringify(expectedAuthors))throw Error('Authors mismatch');
for(const [field,property] of [['id',null],['title',p.name],['url',p.url],['authors',p.authors]] as const)map('sources:src-023',field,source.id,property,review.sourceAlias.reason,field==='authors'?{targetEntityIds:expectedAuthors}:{});
const c=crosswalk.rows.find((r:any)=>r.migrationKey==='sources:src-023');c.candidateGeoIds=[source.id];c.candidateSpaces=[space];c.decision='reuse-existing';c.decisionRationale=review.sourceAlias.reason;c.lastCheckedAt=report.checkedAt;
const program=report.programs.find((r:any)=>r.id==='e181f6b918e548b79304a674743753fd');if(!program.relations.nodes.some((r:any)=>r.typeId===p.sources&&r.toEntityId===source.id))throw Error('Program source edge missing');
map('initiatives:22','sourceIds',program.id,p.sources,'Both original sources resolve to the same verified 2018 paper. One Sources edge covers both aliases without duplicate evidence.',{targetEntityIds:[source.id],originalSourceKeys:['src-023','src-088']});
const method=ledger.rows.find((r:any)=>r.migrationKey==='sources:src-023').fields.find((f:any)=>f.sourceField==='method');if(method.status==='needs-content-review')method.reviewReason='Original RCT label is not the publication method: this paper is a meta-analysis of causal studies. Review/link the appropriate synthesis method instead of labeling the paper a single RCT.';
for(const held of review.held){const key=`initiatives:${held.originalId}`,row=ledger.rows.find((r:any)=>r.migrationKey===key),c=crosswalk.rows.find((r:any)=>r.migrationKey===key);row.candidateGeoIds=[...new Set([...row.candidateGeoIds,held.candidateId])];c.candidateGeoIds=[...new Set([...c.candidateGeoIds,held.candidateId])];c.decision='needs-content-review';c.decisionRationale=held.reason;c.lastCheckedAt=report.checkedAt;}
report.passed=true;writeFileSync(`${root}/original-program-aliases-current-verification.json`,JSON.stringify(report,null,2)+'\n');ledger.checkedAt=report.checkedAt;writeFileSync(`${root}/original-field-reconciliation.json`,JSON.stringify(ledger,null,2)+'\n');writeFileSync(`${root}/source-to-geo-crosswalk.json`,JSON.stringify(crosswalk,null,2)+'\n');console.log(JSON.stringify({passed:true,reconciledFields:14,verifiedTotal:ledger.rows.flatMap((r:any)=>r.fields).filter((f:any)=>f.status==='existing-and-readable').length}));
