import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {randomUUID,createHash} from 'node:crypto';
import {Ops,SystemIds,Position,type Op} from '@geoprotocol/geo-sdk';
import {geoGraphqlRequest as gql} from '../src/geo-api-client';
import {EDUCATION_PUBLICATION as target} from '../src/education-bounty';
const root='data/education',prefix='coaching-collection',read=(n:string)=>JSON.parse(readFileSync(`${root}/${n}.json`,'utf8')),source=read('teacher-coaching-meta-analysis-registry'),discovery=read('coaching-collection-discovery');
if(existsSync(`${root}/${prefix}-publication.json`))throw Error('Preserve submitted payload');
if(discovery.memberships.length!==9||discovery.memberships.some((m:any)=>m.nodes.length||m.pageInfo.hasNextPage)||discovery.searches.some((s:any)=>!s.complete||s.nodes.some((n:any)=>!['Claim','Article','Initiative','Proposal'].includes(n.types[0]?.name)))||Date.now()-Date.parse(discovery.checkedAt)>3600000)throw Error('Refresh/review discovery');
const groups=[{key:'instruction',name:'Instructional practice',rows:[['all-instruction',.488,.056],['content-instruction',.512,.061],['general-instruction',.466,.109]]},{key:'achievement',name:'Student achievement',rows:[['all-achievement',.178,.037],['reading-achievement',.163,.032],['math-achievement',.044,.042],['science-achievement',.352,.242],['content-achievement',.197,.041],['general-achievement',.068,.056]]}];
const p={estimate:'e500e2585a964d2c9df4a47b199616c3',se:'cc28953bd89e406096c9627021f4713d',factual:'da4a6c1f9d4446f9832ff3b49a4400ef',sources:'49c5d5e1679a4dbdbfd33f618f227c94',related:'dfa6aebe1ca94bf29faccc4cc7afb24c',dataset:'0c4babfb43893486af827341bbf32e09',url:'412ff593e9154012a43d4c27ec5c68b6'};
const before:any[]=[];for(const row of groups.flatMap(g=>g.rows)){const id=source[`claim/${row[0]}`],d:any=await gql('query($id:UUID!,$space:UUID!){entity(id:$id){values(first:20,filter:{spaceId:{is:$space}}){nodes{propertyId text decimal integer boolean}pageInfo{hasNextPage}}relations(first:30,filter:{spaceId:{is:$space}}){nodes{id entityId typeId toEntityId position}pageInfo{hasNextPage}}}}',{variables:{id,space:target.spaceId}});if(!d.entity||d.entity.values.pageInfo.hasNextPage||d.entity.relations.pageInfo.hasNextPage)throw Error('Incomplete reused Claim');const v=d.entity.values.nodes;if(!v.some((x:any)=>x.propertyId===p.factual&&x.boolean===true)||!v.some((x:any)=>x.propertyId===p.estimate&&Number(x.decimal)===row[1])||!v.some((x:any)=>x.propertyId===p.se&&Number(x.decimal)===row[2])||!d.entity.relations.nodes.some((e:any)=>e.typeId===p.sources&&e.toEntityId===source.article))throw Error('Source-reviewed Claim changed');before.push({id,...d.entity});}
for(const [property,type] of [[SystemIds.BLOCKS,'Relation'],[SystemIds.TYPES_PROPERTY,'Relation'],[SystemIds.COLLECTION_ITEM_RELATION_TYPE,'Relation'],[SystemIds.DATA_SOURCE_TYPE_RELATION_TYPE,'Relation'],[SystemIds.PROPERTIES,'Relation'],[SystemIds.VIEW_PROPERTY,'Relation'],[p.sources,'Relation'],[p.related,'Relation'],[SystemIds.MARKDOWN_CONTENT,'Text'],[p.estimate,'Decimal'],[p.se,'Decimal']]){const d:any=await gql('query($id:UUID!){property(id:$id){dataTypeName}}',{variables:{id:property}});if(d.property?.dataTypeName!==type)throw Error('Schema mismatch');}
const catalog='2279edef1bbe479c872caeb72ee90022',members:any[]=[];let after:string|null=null;const seen=new Set<string>();do{const d:any=await gql('query($id:UUID!,$space:UUID!,$after:Cursor){entity(id:$id){relations(first:10,after:$after,filter:{spaceId:{is:$space},typeId:{is:"a99f9ce12ffa4dac8c61f6310d46064a"}}){nodes{toEntityId position toEntity{name}}pageInfo{hasNextPage endCursor}}}}',{variables:{id:catalog,space:target.spaceId,after}});const c=d.entity.relations;members.push(...c.nodes);if(!c.pageInfo.hasNextPage)break;if(!c.pageInfo.endCursor||seen.has(c.pageInfo.endCursor))throw Error('Incomplete catalog');after=c.pageInfo.endCursor;seen.add(after!);}while(true);
const name='Teacher coaching: pooled instruction and achievement effects (Kraft et al., 2018)';members.sort((a,b)=>a.position<b.position?-1:1);const next=members.findIndex(m=>m.toEntity.name.localeCompare(name,'en',{sensitivity:'base'})>0);const prior=next<0?members.at(-1):members[next-1];const following=next<0?null:members[next];
const rp=`${root}/${prefix}-registry.json`,r:Record<string,string>=existsSync(rp)?read(`${prefix}-registry`):{},id=(k:string)=>r[k]??(r[k]=randomUUID().replaceAll('-','')),dataset=id('dataset'),notes=id('notes'),ops:Op[]=[];
function rel(k:string,from:string,type:string,to:string,position?:string){const entityId=id(`relation/${k}`);ops.push(...Ops.relations.create({id:id(`edge/${k}`),entityId,fromEntity:from,type,toEntity:to,position:r[`position/${k}`]??(r[`position/${k}`]=position??Position.generate())}).ops);return entityId;}
ops.push(...Ops.entities.update({id:dataset,name,description:'Pooled teacher-coaching effects on instructional practice and student achievement from a synthesis of causal studies. Subject and coaching-model subgroups overlap with the overall estimates.',values:[{property:p.url,type:'text',value:'https://doi.org/10.3102/0034654318759268'}]}).ops);rel('dataset/type',dataset,SystemIds.TYPES_PROPERTY,p.dataset);rel('dataset/source',dataset,p.sources,source.article);rel('dataset/program',dataset,p.related,source.initiative);
ops.push(...Ops.entities.update({id:notes,name:'Reading the estimates',values:[{property:SystemIds.MARKDOWN_CONTENT,type:'text',value:'Effects are in standard-deviation units with robust standard errors. The review includes 60 causal studies; the instruction and achievement pools contain 43 and 31 studies respectively, with overlap. Subject and coaching-model rows are subgroup summaries, not independent replications. A nonsignificant estimate is not evidence of no effect. Open each finding for its study count, effect-size count, source locator and reported significance; do not average these rows together.'}]}).ops);rel('notes/type',notes,SystemIds.TYPES_PROPERTY,SystemIds.TEXT_BLOCK);rel('notes/attach',dataset,SystemIds.BLOCKS,notes,'a0');
for(const [index,g] of groups.entries()){const block=id(`table/${g.key}`);ops.push(...Ops.entities.update({id:block,name:g.name}).ops);rel(`${g.key}/type`,block,SystemIds.TYPES_PROPERTY,SystemIds.DATA_BLOCK);rel(`${g.key}/source`,block,SystemIds.DATA_SOURCE_TYPE_RELATION_TYPE,SystemIds.COLLECTION_DATA_SOURCE);const attach=rel(`${g.key}/attach`,dataset,SystemIds.BLOCKS,block,`a${index+1}`);rel(`${g.key}/view`,attach,SystemIds.VIEW_PROPERTY,SystemIds.TABLE_VIEW);for(const [i,column] of [p.estimate,p.se].entries())rel(`${g.key}/column/${i}`,attach,SystemIds.PROPERTIES,column,`a${i}`);let position=Position.generate();for(const row of g.rows){rel(`${g.key}/member/${row[0]}`,block,SystemIds.COLLECTION_ITEM_RELATION_TYPE,source[`claim/${row[0]}`],position);position=Position.generateBetween(position,null);}}
rel('catalog/member',catalog,SystemIds.COLLECTION_ITEM_RELATION_TYPE,dataset,Position.generateBetween(prior?.position??null,following?.position??null));
for(const e of [dataset,notes,...groups.map(g=>id(`table/${g.key}`))]){const d:any=await gql('query($id:UUID!){entity(id:$id){spaceIds}}',{variables:{id:e}});if(d.entity?.spaceIds?.length)throw Error('New ID occupied');}
const bytes=JSON.stringify(ops,(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('hex')}:v,2)+'\n',sha256=createHash('sha256').update(bytes).digest('hex'),batch={name:'Group nine existing teacher-coaching findings into cataloged result tables',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/${prefix}-ops.json`,sha256,journalPath:`${root}/${prefix}-publication.json`,validationPath:`${root}/${prefix}-validation.json`,datasetId:dataset,groups:groups.map(g=>({key:g.key,blockId:id(`table/${g.key}`),memberIds:g.rows.map(row=>source[`claim/${row[0]}`])})),operationCount:ops.length};
writeFileSync(rp,JSON.stringify(r,null,2)+'\n');writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/${prefix}-batch.json`,JSON.stringify(batch,null,2)+'\n');writeFileSync(`${root}/${prefix}-before.json`,JSON.stringify(before,null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),opsHash:sha256,checks:['All nine existing factual/source/numeric records match reviewed Table 2','All-space aliases and incoming memberships reviewed','Separate instruction and achievement tables with overlap guidance','No writes to existing Claim facts or relationships','One Dataset added to existing catalog in alphabetical position','New content typed; schemas verified']},null,2)+'\n');console.log(JSON.stringify({dataset,operations:ops.length,reusedClaims:9}));
