import {readFileSync,writeFileSync} from 'node:fs';
import {geoGraphqlRequest as gql} from '../src/geo-api-client';
import {EDUCATION_PUBLICATION as target} from '../src/education-bounty';
const root='data/education',query=readFileSync(`${root}/dashboard-comparison-query.graphql`,'utf8'),related='dfa6aebe1ca94bf29faccc4cc7afb24c',factual='da4a6c1f9d4446f9832ff3b49a4400ef',estimate='e500e2585a964d2c9df4a47b199616c3',unit='8405509cc7354655a348591349a5f025',standardError='cc28953bd89e406096c9627021f4713d',sampleSize='210e9b352b454d6eb7a32906d24d3c8d',locator='84dacbddca6a44079edb5e11a4c66b40',pValue='ba5f8fe9d1cd9a6094338d2f37b74a5e',cost='6ba2ce00db064687b108aa8449672886',year='97e14050fc49467bb3aaf4d7eccbbb69',currency='6e7371ca96cb44348f16932f77f55e75',denominator='3a558d71454745a992c035040f648729',benefitCostRatio='45ce8dc80a74432e9a2483cd1c8e86e1',internalRateOfReturn='879d207046024b44be6e3d64c32c60da';
const families=[
 {name:'Head Start',registry:'head-start-registry.json',initiative:'initiative',expected:['claim/first-grade','claim/third-grade/preschool-and-elementary','claim/third-grade/language-literacy-third-grade'],additionalRegistry:'head-start-third-grade-cognitive-registry.json',additionalExpected:['claim/four-reading','claim/four-ppvt','claim/four-letter-word','claim/four-applied-problems','claim/four-calculation','claim/three-reading','claim/three-ppvt','claim/three-letter-word','claim/three-applied-problems','claim/three-calculation'],thirdRegistry:'head-start-third-grade-social-emotional-registry.json',thirdExpected:['claim/four-parent-aggression','claim/four-teacher-emotional','claim/four-child-peer','claim/three-parent-social-skills'],fourthRegistry:'head-start-third-grade-health-summary-registry.json',fourthExpected:['claim'],fifthRegistry:'head-start-third-grade-iot-registry.json',fifthExpected:['claim/four-reading','claim/four-parent-aggression','claim/four-teacher-emotional','claim/four-child-peer','claim/three-parent-social-skills'],sixthRegistry:'head-start-third-grade-paired-expansion-registry.json',sixthExpected:['claim/four-total-problem/itt','claim/four-total-problem/iot','claim/four-teacher-closeness/itt','claim/four-teacher-closeness/iot','claim/four-teacher-positive-relationship/itt','claim/four-teacher-positive-relationship/iot','claim/four-parent-time/itt','claim/four-parent-time/iot'],seventhRegistry:'head-start-third-grade-promotion-pair-registry.json',seventhExpected:['claim/three-promotion/itt','claim/three-promotion/iot']},
 {name:'Double-dose algebra',registry:'double-dose-algebra-registry.json',initiative:'initiative',expected:['claim/policy-design','claim/attainment','claim/reading-skill']},
 {name:'EWIMS',registry:'ewims-registry.json',initiative:'initiative',expected:['claim/chronic-absence','claim/course-failure','claim/credits']},
 {name:'Career Academies',registry:'career-academies-registry.json',initiative:'initiative',expected:['claim/earnings','claim/education','claim/young-men']},
 {name:'CUNY ASAP',registry:'cuny-asap-source-registry.json',initiative:'initiative',sourceId:'536b5cd10a65417ea4e1d52b3322dcad',expected:[]},
 {name:'CUNY ASAP three-year randomized outcomes',registry:'cuny-asap-three-year-registry.json',initiative:'initiative',targetId:'3f6f2b82f8b94d3c85a5198a40e34199',sourceId:'84231ad5631249a99f56e89dc540e3d6',expected:['claim/design','claim/degree','claim/credits','claim/four-year-enrollment']},
 {name:'ASAP Ohio eight-year randomized outcomes',registry:'asap-ohio-eight-year-registry.json',initiative:'initiative',sourceId:'2dbe6ce279734000bf3d2ef69f71764c',expected:['claim/design','claim/degree','claim/bachelors','claim/earnings']},
 {name:'WorkAdvance pooled randomized outcomes',registry:'workadvance-2020-registry.json',initiative:'initiative/program',sourceId:'2278407dc1df480e8a297cd9beb44a4a',expected:['claim/design','claim/pooled-earnings','claim/pooled-high']},
 {name:'WorkAdvance Per Scholas outcomes and net gains',registry:'workadvance-2020-registry.json',initiative:'initiative/per-scholas',sourceId:'2278407dc1df480e8a297cd9beb44a4a',expected:['claim/per-scholas/earnings','claim/per-scholas/high','claim/per-scholas/net-participant','claim/per-scholas/net-government-budget','claim/per-scholas/net-society']},
 {name:'WorkAdvance St. Nicks outcomes and net gains',registry:'workadvance-2020-registry.json',initiative:'initiative/st-nicks',sourceId:'2278407dc1df480e8a297cd9beb44a4a',expected:['claim/st-nicks/earnings','claim/st-nicks/high','claim/st-nicks/net-participant','claim/st-nicks/net-government-budget','claim/st-nicks/net-society']},
 {name:'WorkAdvance Madison outcomes and net gains',registry:'workadvance-2020-registry.json',initiative:'initiative/madison',sourceId:'2278407dc1df480e8a297cd9beb44a4a',expected:['claim/madison/earnings','claim/madison/high','claim/madison/net-participant','claim/madison/net-government-budget','claim/madison/net-society']},
 {name:'WorkAdvance Towards Employment outcomes and net gains',registry:'workadvance-2020-registry.json',initiative:'initiative/towards-employment',sourceId:'2278407dc1df480e8a297cd9beb44a4a',expected:['claim/towards-employment/earnings','claim/towards-employment/high','claim/towards-employment/net-participant','claim/towards-employment/net-government-budget','claim/towards-employment/net-society']},
 {name:'DCMP five-year randomized cost and outcomes',registry:'dcmp-2023-registry.json',initiative:'initiative',sourceId:'20203925d22447479e7a0b97ca4862e0',expected:['claim/design','claim/net-cost','claim/components','claim/credential-or-enrollment','claim/credits','claim/cost-per-attainment','claim/cost-per-credit']},
 {name:'PACE Center for Girls randomized outcomes and cost',registry:'pace-2019-registry.json',initiative:'initiative',sourceId:'c8303039db3946ea8c71e717ec00c9e1',expected:['claim/design','claim/net-cost','claim/days-present','claim/on-track','claim/credit-success','claim/suspension','claim/charge']},
 {name:'MSSI randomized outcomes and real-dollar cost',registry:'mssi-2023-registry.json',initiative:'initiative',sourceId:'4eb6ce035ec046b59e29ac3a49cac986',expected:['claim/design','claim/cost','claim/acdv-enrollment','claim/acdv-pass','claim/credits','claim/later-grades']},
 {name:'Texas Summer Bridge randomized outcomes and resource cost',registry:'texas-summer-bridge-registry.json',initiative:'initiative',sourceId:'9a01e3c8d25145ada294e929bdb75870',expected:['claim/design','claim/cost','claim/math-attempt','claim/math-pass','claim/writing-pass','claim/registration']},
 {name:'Viking ROADS randomized academic outcomes',registry:'viking-roads-2025-registry.json',initiative:'initiative',sourceId:'581c4b9bd2ec40d69cbcf68b973d8803',expected:['claim/design','claim/enrollment-s3','claim/credits-s3','claim/degree-s6','claim/credits60-s6']},
 {name:'Kingsborough Opening Doors six-year randomized outcomes and costs',registry:'opening-doors-kingsborough-2012-registry.json',initiative:'initiative',sourceId:'e6329e1831db4ceea35b483e5fc50cc1',expected:['claim/design','claim/degree','claim/net-cost','claim/cost-per-degree']},
 {name:'NYC Small Schools of Choice longitudinal outcomes',registry:'nyc-small-schools-registry.json',initiative:'initiative',sourceId:'3a02b7c1d1ea4d8b8f29489610fd62c4',expected:['claim/design','claim/graduation','claim/postsecondary-enrollment','claim/degree-six-years','claim/employment-null']},
 {name:'NYC Small Schools of Choice cost accounting',registry:'nyc-small-schools-registry.json',initiative:'initiative',sourceId:'4f1726ca9f934e30b72c18a41f82846a',expected:['claim/net-expenditure','claim/cost-per-graduate']},
 {name:'Early College High Schools Year-10 lottery outcomes',registry:'early-college-registry.json',initiative:'initiative',sourceId:'038f546c2508401eb3890f0fc6954b53',expected:['claim/design','claim/any-college','claim/any-degree','claim/associate-certificate','claim/bachelors','claim/four-year-enrollment']},
 {name:'Early College High Schools source-reported cost-benefit model',registry:'early-college-registry.json',initiative:'initiative',sourceId:'0b285e99daa5436f8d02e608fea4fb2b',expected:['claim/modeled-benefits','claim/modeled-cost','claim/modeled-npv','claim/modeled-bcr','claim/conservative-bcr']},
 {name:'Year Up PACE seven-year randomized earnings',registry:'year-up-outcomes-registry.json',initiative:'initiative',sourceId:'ce3170d43bfc4a98ba1594ebc591e6d7',expected:['claim/design','claim/quarter-23-24-earnings','claim/year-1-earnings','claim/year-7-earnings','claim/years-1-7-earnings','claim/high-earnings-threshold','claim/employment-null']},
 {name:'Abecedarian age-30 outcomes',registry:'abecedarian-age30-outcomes-registry.json',initiative:'study',targetId:'66657d9776214aec9cf816b8d50b644a',sourceId:'a72a792642aa46b497587313102bfe39',expected:['claim/education-years','claim/bachelors-degree','claim/income-to-needs','claim/full-employment'],additionalRegistry:'abecedarian-age30-expanded-registry.json',additionalExpected:['claim/hs-credential','claim/public-aid','claim/first-parity','claim/criminal-conviction']},
 {name:'National Guard Youth ChalleNGe',registry:'youth-challenge-registry.json',initiative:'initiative',expected:['claim/diploma-ged','claim/employment','claim/earnings'],excluded:['youth-challenge-debate-registry.json:parent']}
 ,{name:'Tennessee voluntary pre-K',registry:'tennessee-vpk-registry.json',initiative:'initiative',expected:['claim/design','claim/achievement','claim/behavior-records']}
 ,{name:'Boston universal pre-K',registry:'boston-prek-registry.json',initiative:'initiative',expected:['claim/college','claim/graduation','claim/sat','claim/mcas-math','claim/mcas-ela','claim/incarceration']}
 ,{name:'Enhanced Reading Opportunities',registry:'enhanced-reading-registry.json',initiative:'initiative',expected:['claim/reading','claim/gpa','claim/credits','claim/fadeout']}
 ,{name:'San Francisco ethnic studies',registry:'sf-ethnic-studies-registry.json',initiative:'initiative',sourceId:'7cf51d06726242b88157ca3ea1f5b228',expected:['claim/attendance','claim/gpa','claim/credits']}
 ,{name:'San Francisco ethnic studies longer-run',registry:'sf-ethnic-studies-longterm-registry.json',initiative:'initiative',targetId:'d597ffb8910b46158a2eb2c20ad4e48b',sourceId:'90f5100c5ccc420d8b73609ade09542a',expected:['claim/graduation','claim/attendance-year4','claim/credits-year4']}
 ,{name:'San Francisco ethnic studies districtwide expansion',registry:'sf-ethnic-studies-scale-registry.json',initiative:'initiative',sourceId:'4c5094291f7340f7b3ba8adca9a25b5c',expected:['claim/overall-gpa','claim/course-failure','claim/math-gpa','claim/science-gpa','claim/black-gpa'],additionalRegistry:'sf-ethnic-studies-scale-subgroups-registry.json',additionalExpected:['claim/black-failure','claim/latine-gpa','claim/latine-failure','claim/male-gpa','claim/male-failure']}
 ,{name:'Project QUEST',registry:'project-quest-registry.json',initiative:'initiative',sourceId:'83427dac98de4da496573df368a07561',expected:['claim/design','claim/earnings-year9','claim/operating-cost'],additionalRegistry:'project-quest-earnings-series-registry.json',additionalExpected:['claim/year-1','claim/year-2','claim/year-3','claim/year-4','claim/year-5','claim/year-6','claim/year-7','claim/year-8']}
 ,{name:'Comprehensive teacher induction randomized outcomes',registry:'teacher-induction-rct-registry.json',initiative:'initiative',sourceId:'fae731c205e34a5580d8cef78a5aa074',expected:['claim/reading','claim/math','claim/retention']}
 ,{name:'Community Eligibility Provision household-resource outcomes',registry:'community-eligibility-provision-registry.json',initiative:'initiative',sourceId:'de88c706c7644e9a8681c221d5c2536e',expected:['claim/any-food-spending','claim/full-exposure-food-spending','claim/food-insecurity']}
 ,{name:'Teacher Incentive Fund pay-for-performance outcomes',registry:'teacher-incentive-fund-registry.json',initiative:'initiative',sourceId:'1fcce9b53fa640279448239bba337eef',expected:['claim/year1-math','claim/year1-reading','claim/year2-math','claim/year2-reading','claim/year3-math','claim/year3-reading','claim/year4-math','claim/year4-reading']}
 ,{name:'Teacher coaching meta-analysis',registry:'teacher-coaching-meta-analysis-registry.json',initiative:'initiative',sourceId:'6a85813ac8734141b55affa06793661c',expected:['claim/all-instruction','claim/all-achievement','claim/reading-achievement','claim/math-achievement','claim/science-achievement','claim/content-instruction','claim/content-achievement','claim/general-instruction','claim/general-achievement']}
 ,{name:'National Charter School Study III',registry:'ncss3-registry.json',initiative:'initiative',sourceId:'e250e966938549269ac74b1935fa380d',expected:['claim/overall-reading','claim/overall-math','claim/cmo-reading','claim/cmo-math','claim/standalone-reading','claim/jurisdiction-reading-spread','claim/jurisdiction-math-spread']}
 ,{name:'TFA and Teaching Fellows secondary-math randomized evaluation',registry:'tfa-teaching-fellows-registry.json',initiative:'initiative',sourceId:'43083998d74b4f5bbf49ac3f3354e74e',expected:['claim/tfa-overall','claim/teaching-fellows-overall','claim/teaching-fellows-similar-experience','claim/tfa-traditional-route','claim/tfa-less-selective-route','claim/teaching-fellows-traditional-route','claim/teaching-fellows-less-selective-route']}
];
const report:any={checkedAt:new Date().toISOString(),spaceId:target.spaceId,queryPath:`${root}/dashboard-comparison-query.graphql`,scope:'Destination-scoped multi-intervention comparison rows. It returns factual and evaluative Claims, so consumers must use the factual flag before treating a row as evidence. Units remain incompatible and do not authorize a ranking. When one Study has multiple evidence families, the source Article is a required second filter.',cases:[]};
for(const family of families){
  const r=JSON.parse(readFileSync(`${root}/${family.registry}`,'utf8'));const expected=family.expected.map((k:string)=>r[k]),targetId=family.targetId??r[family.initiative];if(family.additionalRegistry)expected.push(...family.additionalExpected.map((k:string)=>JSON.parse(readFileSync(`${root}/${family.additionalRegistry}`,'utf8'))[k]));if(family.thirdRegistry)expected.push(...family.thirdExpected.map((k:string)=>JSON.parse(readFileSync(`${root}/${family.thirdRegistry}`,'utf8'))[k]));if(family.fourthRegistry)expected.push(...family.fourthExpected.map((k:string)=>JSON.parse(readFileSync(`${root}/${family.fourthRegistry}`,'utf8'))[k]));if(family.fifthRegistry)expected.push(...family.fifthExpected.map((k:string)=>JSON.parse(readFileSync(`${root}/${family.fifthRegistry}`,'utf8'))[k]));if(family.sixthRegistry)expected.push(...family.sixthExpected.map((k:string)=>JSON.parse(readFileSync(`${root}/${family.sixthRegistry}`,'utf8'))[k]));if(family.seventhRegistry)expected.push(...family.seventhExpected.map((k:string)=>JSON.parse(readFileSync(`${root}/${family.seventhRegistry}`,'utf8'))[k]));
 if(family.name==='CUNY ASAP'){
   const costRegistry=JSON.parse(readFileSync(`${root}/cuny-asap-cost-registry.json`,'utf8'));
   const outcomesRegistry=JSON.parse(readFileSync(`${root}/cuny-asap-outcomes-registry.json`,'utf8'));
   expected.push(costRegistry['net-cost'],outcomesRegistry['claim/associate-degree-eight-year'],outcomesRegistry['claim/cost-per-associate-degree-eight-year']);
 }
 expected.sort();let after:string|null=null,nodes:any[]=[];
 do{const d:any=await gql(query,{variables:{spaceId:target.spaceId,after,filter:{relations:{some:{spaceId:{is:target.spaceId},typeId:{is:related},toEntityId:{is:targetId}}}}}});nodes.push(...d.entitiesConnection.nodes);after=d.entitiesConnection.pageInfo.hasNextPage?d.entitiesConnection.pageInfo.endCursor:null;}while(after);
 const studyFactualNodes=nodes.filter((n:any)=>n.values.nodes.some((v:any)=>v.propertyId===factual&&v.boolean===true));
 const factualNodes=family.sourceId?studyFactualNodes.filter((n:any)=>n.relations.nodes.some((x:any)=>x.typeId==='49c5d5e1679a4dbdbfd33f618f227c94'&&x.toEntityId===family.sourceId)):studyFactualNodes,ids=factualNodes.map((n:any)=>n.id).sort(),checks=[expected.every((id:string)=>ids.includes(id))];
 for(const n of factualNodes){checks.push(!n.values.pageInfo.hasNextPage,!n.relations.pageInfo.hasNextPage,n.relations.nodes.some((x:any)=>x.typeId===related&&x.toEntityId===targetId));if(family.sourceId)checks.push(n.relations.nodes.some((x:any)=>x.typeId==='49c5d5e1679a4dbdbfd33f618f227c94'&&x.toEntityId===family.sourceId));const value=n.values.nodes.find((x:any)=>x.propertyId===estimate),u=n.values.nodes.find((x:any)=>x.propertyId===unit);if(value)checks.push(!!u?.text);}
 if(family.name==='National Guard Youth ChalleNGe'){const costId=JSON.parse(readFileSync(`${root}/youth-challenge-cost-registry.json`,'utf8')).cost,roiId=JSON.parse(readFileSync(`${root}/youth-challenge-roi-registry.json`,'utf8')).claim,irrId=JSON.parse(readFileSync(`${root}/youth-challenge-irr-registry.json`,'utf8')).claim,components=JSON.parse(readFileSync(`${root}/youth-challenge-components-registry.json`,'utf8')),componentValues:{[key:string]:number}={'opportunity-cost':2058,'cost-tax-deadweight':1745,'lifetime-earnings':43514,'education-cost':-4860,'welfare-admin':249,'crime':662,'service':423,'benefit-tax-deadweight':997};const row=factualNodes.find((n:any)=>n.id===costId),roi=factualNodes.find((n:any)=>n.id===roiId),irr=factualNodes.find((n:any)=>n.id===irrId);checks.push(!!row,row?.values.nodes.some((v:any)=>v.propertyId===cost&&Number(v.decimal)===11633),row?.values.nodes.some((v:any)=>v.propertyId===year&&Number(v.integer)===2010),row?.values.nodes.some((v:any)=>v.propertyId===currency&&v.text==='USD'),row?.values.nodes.some((v:any)=>v.propertyId===denominator&&v.text?.includes('per admitted cadet')));checks.push(!!roi,roi?.values.nodes.some((v:any)=>v.propertyId===benefitCostRatio&&Number(v.decimal)===2.66),roi?.description.includes('3% social discount rate'),roi?.description.includes('15% tax-deadweight assumption'));checks.push(!!irr,irr?.values.nodes.some((v:any)=>v.propertyId===internalRateOfReturn&&Number(v.decimal)===0.064),irr?.description.includes('modeled lifetime societal return'));for(const[key,value]of Object.entries(componentValues)){const component=factualNodes.find((n:any)=>n.id===components[`claim/${key}`]);checks.push(!!component,component?.values.nodes.some((v:any)=>v.propertyId===cost&&Number(v.decimal)===value),component?.values.nodes.some((v:any)=>v.propertyId===year&&Number(v.integer)===2010),component?.values.nodes.some((v:any)=>v.propertyId===currency&&v.text==='USD'));}}
 if(family.name==='Boston universal pre-K'){const rows:{[key:string]:[number,number,number]}={college:[.083,.03,4175],graduation:[.06,.03,3883],sat:[.085,.034,2559],'mcas-math':[.029,.056,3615],'mcas-ela':[.005,.057,3569],incarceration:[-.008,.005,3335]};for(const[key,[effect,se,n]]of Object.entries(rows)){const row=factualNodes.find((node:any)=>node.id===r[`claim/${key}`]);checks.push(!!row,row?.values.nodes.some((v:any)=>v.propertyId===estimate&&Number(v.decimal)===effect),row?.values.nodes.some((v:any)=>v.propertyId===standardError&&Number(v.decimal)===se),row?.values.nodes.some((v:any)=>v.propertyId===sampleSize&&Number(v.integer)===n),row?.values.nodes.some((v:any)=>v.propertyId===locator&&!!v.text),row?.values.nodes.some((v:any)=>v.propertyId===unit&&!!v.text));}}
 if(family.name==='Enhanced Reading Opportunities'){const rows:{[key:string]:string}={reading:'P = 0.002',gpa:'P = 0.002',credits:'P = 0.017',fadeout:'P = 0.061'};for(const[key,p]of Object.entries(rows)){const row=factualNodes.find((node:any)=>node.id===r[`claim/${key}`]);checks.push(!!row,row?.values.nodes.some((v:any)=>v.propertyId===pValue&&v.text===p),!row?.values.nodes.some((v:any)=>v.propertyId===standardError));}}
 if(family.name==='Teacher Incentive Fund pay-for-performance outcomes'){const rows:{[key:string]:[number,number,string]}={'year1-math':[.02,40535,'P = .33'],'year1-reading':[.03,40256,'P = .04'],'year2-math':[.04,40454,'P = .07'],'year2-reading':[.03,40122,'P = .02'],'year3-math':[.06,39770,'P = .02'],'year3-reading':[.04,39538,'P = .02'],'year4-math':[.04,38939,'P = .13'],'year4-reading':[.04,38929,'P = .08']};for(const[key,[effect,n,p]]of Object.entries(rows)){const row=factualNodes.find((node:any)=>node.id===r[`claim/${key}`]);checks.push(!!row,row?.values.nodes.some((v:any)=>v.propertyId===estimate&&Number(v.decimal)===effect),row?.values.nodes.some((v:any)=>v.propertyId===sampleSize&&Number(v.integer)===n),row?.values.nodes.some((v:any)=>v.propertyId===pValue&&v.text===p),row?.values.nodes.some((v:any)=>v.propertyId===locator&&!!v.text),row?.values.nodes.some((v:any)=>v.propertyId===unit&&!!v.text),!row?.values.nodes.some((v:any)=>v.propertyId===standardError));}}
 if(family.name==='Teacher coaching meta-analysis'){const rows:{[key:string]:[number,number,number]}={'all-instruction':[.488,.056,43],'all-achievement':[.178,.037,31],'reading-achievement':[.163,.032,26],'math-achievement':[.044,.042,5],'science-achievement':[.352,.242,3],'content-instruction':[.512,.061,27],'content-achievement':[.197,.041,26],'general-instruction':[.466,.109,16],'general-achievement':[.068,.056,5]};for(const[key,[effect,se,n]]of Object.entries(rows)){const row=factualNodes.find((node:any)=>node.id===r[`claim/${key}`]);checks.push(!!row,row?.values.nodes.some((v:any)=>v.propertyId===estimate&&Number(v.decimal)===effect),row?.values.nodes.some((v:any)=>v.propertyId===standardError&&Number(v.decimal)===se),row?.values.nodes.some((v:any)=>v.propertyId===sampleSize&&Number(v.integer)===n),row?.values.nodes.some((v:any)=>v.propertyId===locator&&!!v.text),row?.values.nodes.some((v:any)=>v.propertyId===unit&&!!v.text));}}
 if(family.name==='National Charter School Study III'){const rows:{[key:string]:number}={'overall-reading':16,'overall-math':6,'cmo-reading':27,'cmo-math':23,'standalone-reading':10,'jurisdiction-reading-spread':109,'jurisdiction-math-spread':120};for(const[key,effect]of Object.entries(rows)){const row=factualNodes.find((node:any)=>node.id===r[`claim/${key}`]);checks.push(!!row,row?.values.nodes.some((v:any)=>v.propertyId===estimate&&Number(v.decimal)===effect),row?.values.nodes.some((v:any)=>v.propertyId===sampleSize&&Number(v.integer)===31),row?.values.nodes.some((v:any)=>v.propertyId===locator&&!!v.text),row?.values.nodes.some((v:any)=>v.propertyId===unit&&!!v.text),!row?.values.nodes.some((v:any)=>v.propertyId===standardError||v.propertyId===pValue));}}
 if(family.name==='San Francisco ethnic studies'){const rows:{[key:string]:number}={attendance:.21,gpa:1.4,credits:23};for(const[key,effect]of Object.entries(rows)){const row=factualNodes.find((node:any)=>node.id===r[`claim/${key}`]);checks.push(!!row,row?.values.nodes.some((v:any)=>v.propertyId===estimate&&Number(v.decimal)===effect),row?.values.nodes.some((v:any)=>v.propertyId===sampleSize&&Number(v.integer)===1404),row?.values.nodes.some((v:any)=>v.propertyId===locator&&!!v.text),row?.values.nodes.some((v:any)=>v.propertyId===unit&&!!v.text));}}
 if(family.name==='San Francisco ethnic studies longer-run'){const rows:{[key:string]:[number,number,number]}={graduation:[.157,.073,1405],'attendance-year4':[7.158,1.799,1304],'credits-year4':[15.29,7.724,1304]};for(const[key,[effect,se,n]]of Object.entries(rows)){const row=factualNodes.find((node:any)=>node.id===r[`claim/${key}`]);checks.push(!!row,row?.values.nodes.some((v:any)=>v.propertyId===estimate&&Number(v.decimal)===effect),row?.values.nodes.some((v:any)=>v.propertyId===standardError&&Number(v.decimal)===se),row?.values.nodes.some((v:any)=>v.propertyId===sampleSize&&Number(v.integer)===n),row?.values.nodes.some((v:any)=>v.propertyId===locator&&!!v.text),row?.values.nodes.some((v:any)=>v.propertyId===unit&&!!v.text));}}
 if(family.name==='San Francisco ethnic studies districtwide expansion'){const rows:{[key:string]:[number,number,number]}={'overall-gpa':[.174,.04,24210],'course-failure':[-.056,.016,24210],'math-gpa':[.266,.049,24246],'science-gpa':[.199,.049,24246],'black-gpa':[.228,.042,1335],'black-failure':[-.104,.021,1335],'latine-gpa':[.248,.046,4904],'latine-failure':[-.117,.023,4904],'male-gpa':[.192,.044,12345],'male-failure':[-.068,.017,12345]};const subgroup:any=family.additionalRegistry?JSON.parse(readFileSync(`${root}/${family.additionalRegistry}`,'utf8')):{};for(const[key,[effect,se,n]]of Object.entries(rows)){const row=factualNodes.find((node:any)=>node.id===(r[`claim/${key}`]??subgroup[`claim/${key}`]));checks.push(!!row,row?.values.nodes.some((v:any)=>v.propertyId===estimate&&Number(v.decimal)===effect),row?.values.nodes.some((v:any)=>v.propertyId===standardError&&Number(v.decimal)===se),row?.values.nodes.some((v:any)=>v.propertyId===sampleSize&&Number(v.integer)===n),row?.values.nodes.some((v:any)=>v.propertyId===locator&&!!v.text),row?.values.nodes.some((v:any)=>v.propertyId===unit&&!!v.text));}}
 if(family.name==='Project QUEST'){const earnings=factualNodes.find((n:any)=>n.id===r['claim/earnings-year9']),operating=factualNodes.find((n:any)=>n.id===r['claim/operating-cost']),series:any=family.additionalRegistry?JSON.parse(readFileSync(`${root}/${family.additionalRegistry}`,'utf8')):{},annual:{[key:string]:number}={'year-1':-1801,'year-2':-2369,'year-3':1881,'year-4':3925,'year-5':3980,'year-6':4691,'year-7':2176,'year-8':2952};checks.push(!!earnings,earnings?.values.nodes.some((v:any)=>v.propertyId===estimate&&Number(v.decimal)===5239),earnings?.values.nodes.some((v:any)=>v.propertyId===sampleSize&&Number(v.integer)===410),earnings?.values.nodes.some((v:any)=>v.propertyId===unit&&v.text?.includes('current dollars')));for(const[key,value]of Object.entries(annual)){const row=factualNodes.find((n:any)=>n.id===series[`claim/${key}`]);checks.push(!!row,row?.values.nodes.some((v:any)=>v.propertyId===estimate&&Number(v.decimal)===value),row?.values.nodes.some((v:any)=>v.propertyId===sampleSize&&Number(v.integer)===410),row?.values.nodes.some((v:any)=>v.propertyId===unit&&v.text?.includes('current dollars')),row?.values.nodes.some((v:any)=>v.propertyId===locator&&!!v.text));}checks.push(!!operating,operating?.values.nodes.some((v:any)=>v.propertyId===cost&&Number(v.decimal)===10501),operating?.values.nodes.some((v:any)=>v.propertyId===currency&&v.text==='USD'),operating?.values.nodes.some((v:any)=>v.propertyId===denominator&&v.text?.includes('Operating cost per Project QUEST participant')),operating?.description.includes('not a net cost'));}
 if(family.name==='CUNY ASAP three-year randomized outcomes'){const rows:{[key:string]:[number,number|null,string]}={degree:[.183,null,'< .001'],credits:[8.67,1.95,'< .001'],'four-year-enrollment':[.078,null,'= .0040']};for(const[key,[effect,se,p]]of Object.entries(rows)){const row=factualNodes.find((node:any)=>node.id===r[`claim/${key}`]);checks.push(!!row,row?.values.nodes.some((v:any)=>v.propertyId===estimate&&Number(v.decimal)===effect),row?.values.nodes.some((v:any)=>v.propertyId===sampleSize&&Number(v.integer)===896),row?.values.nodes.some((v:any)=>v.propertyId===pValue&&v.text===p),row?.values.nodes.some((v:any)=>v.propertyId===locator&&!!v.text),row?.values.nodes.some((v:any)=>v.propertyId===unit&&!!v.text));if(se!==null)checks.push(row?.values.nodes.some((v:any)=>v.propertyId===standardError&&Number(v.decimal)===se));}}
 if(family.name==='ASAP Ohio eight-year randomized outcomes'){const degree=factualNodes.find((node:any)=>node.id===r['claim/degree']),bachelors=factualNodes.find((node:any)=>node.id===r['claim/bachelors']),earnings=factualNodes.find((node:any)=>node.id===r['claim/earnings']);for(const[row,effect]of [[degree,.15],[bachelors,.062]] as const){checks.push(!!row,row?.values.nodes.some((v:any)=>v.propertyId===estimate&&Number(v.decimal)===effect),row?.values.nodes.some((v:any)=>v.propertyId===sampleSize&&Number(v.integer)===1501),row?.values.nodes.some((v:any)=>v.propertyId===locator&&!!v.text),row?.values.nodes.some((v:any)=>v.propertyId===unit&&!!v.text));}checks.push(!!earnings,earnings?.values.nodes.some((v:any)=>v.propertyId===estimate&&Number(v.decimal)===3337),earnings?.values.nodes.some((v:any)=>v.propertyId===sampleSize&&Number(v.integer)===1482),earnings?.values.nodes.some((v:any)=>v.propertyId===unit&&v.text?.includes('price year not stated')),earnings?.description.includes('Ohio unemployment-insurance'))}
 if(family.name==='WorkAdvance pooled randomized outcomes'){const earnings=factualNodes.find((node:any)=>node.id===r['claim/pooled-earnings']),high=factualNodes.find((node:any)=>node.id===r['claim/pooled-high']);for(const[row,effect,p]of [[earnings,2716,'= .003'],[high,6.4,'= .001']] as const)checks.push(!!row,row?.values.nodes.some((v:any)=>v.propertyId===estimate&&Number(v.decimal)===effect),row?.values.nodes.some((v:any)=>v.propertyId===sampleSize&&Number(v.integer)===2564),row?.values.nodes.some((v:any)=>v.propertyId===pValue&&v.text===p),row?.values.nodes.some((v:any)=>v.propertyId===unit&&!!v.text),row?.values.nodes.some((v:any)=>v.propertyId===locator&&!!v.text));}
 if(family.name.startsWith('WorkAdvance ')&&family.name.endsWith('outcomes and net gains')){const key=family.name.includes('Per Scholas')?'per-scholas':family.name.includes('St. Nicks')?'st-nicks':family.name.includes('Madison')?'madison':'towards-employment',expectedRows:{[key:string]:[number,number,number]}={'per-scholas':[6281,6.3,31387],'st-nicks':[2849,9.3,13742],'madison':[787,5.8,13114],'towards-employment':[1404,5.1,5820]},[earnings,high,society]=[factualNodes.find((node:any)=>node.id===r[`claim/${key}/earnings`]),factualNodes.find((node:any)=>node.id===r[`claim/${key}/high`]),factualNodes.find((node:any)=>node.id===r[`claim/${key}/net-society`])],[earningsValue,highValue,societyValue]=expectedRows[key];checks.push(!!earnings,earnings?.values.nodes.some((v:any)=>v.propertyId===estimate&&Number(v.decimal)===earningsValue),earnings?.values.nodes.some((v:any)=>v.propertyId===sampleSize&&!!v.integer),!!high,high?.values.nodes.some((v:any)=>v.propertyId===estimate&&Number(v.decimal)===highValue),!!society,society?.values.nodes.some((v:any)=>v.propertyId===estimate&&Number(v.decimal)===societyValue),society?.values.nodes.some((v:any)=>v.propertyId===year&&Number(v.integer)===2018),society?.values.nodes.some((v:any)=>v.propertyId===currency&&v.text==='USD'),society?.description.includes('not a benefit-cost ratio'));}
 if(family.name==='DCMP five-year randomized cost and outcomes'){const net=factualNodes.find((node:any)=>node.id===r['claim/net-cost']),attainment=factualNodes.find((node:any)=>node.id===r['claim/credential-or-enrollment']),credits=factualNodes.find((node:any)=>node.id===r['claim/credits']),costAttainment=factualNodes.find((node:any)=>node.id===r['claim/cost-per-attainment']);checks.push(!!net,net?.values.nodes.some((v:any)=>v.propertyId===cost&&Number(v.decimal)===790),net?.values.nodes.some((v:any)=>v.propertyId===year&&Number(v.integer)===2022),net?.values.nodes.some((v:any)=>v.propertyId===currency&&v.text==='USD'),net?.values.nodes.some((v:any)=>v.propertyId===denominator&&v.text?.includes('Per program-group member')));for(const[row,value]of [[attainment,2.5],[credits,.4]] as const)checks.push(!!row,row?.values.nodes.some((v:any)=>v.propertyId===estimate&&Number(v.decimal)===value),row?.values.nodes.some((v:any)=>v.propertyId===sampleSize&&Number(v.integer)===1411),row?.description.includes('not statistically significant'));checks.push(!!costAttainment,costAttainment?.values.nodes.some((v:any)=>v.propertyId===cost&&Number(v.decimal)===-3450),costAttainment?.description.includes('not a confirmed savings'));}
 if(family.name==='CUNY ASAP'){
   const outcomesRegistry=JSON.parse(readFileSync(`${root}/cuny-asap-outcomes-registry.json`,'utf8'));
   const degree=factualNodes.find((n:any)=>n.id===outcomesRegistry['claim/associate-degree-eight-year']);
   const costDegree=factualNodes.find((n:any)=>n.id===outcomesRegistry['claim/cost-per-associate-degree-eight-year']);
   checks.push(!!degree,degree?.values.nodes.some((v:any)=>v.propertyId===estimate&&Number(v.decimal)===12));
   checks.push(!!costDegree,costDegree?.values.nodes.some((v:any)=>v.propertyId===cost&&Number(v.decimal)===9162),costDegree?.values.nodes.some((v:any)=>v.propertyId===year&&Number(v.integer)===2019),costDegree?.values.nodes.some((v:any)=>v.propertyId===currency&&v.text==='USD'),costDegree?.values.nodes.some((v:any)=>v.propertyId===denominator&&v.text?.includes('per associate degree')));
 }
 const excluded=(family.excluded??[]).map((entry:string)=>{const [file,key]=entry.split(':');return JSON.parse(readFileSync(`${root}/${file}`,'utf8'))[key];});checks.push(excluded.every((id:string)=>!ids.includes(id)));
 report.cases.push({name:family.name,expectedIds:expected,actualIds:ids,nonFactualExcluded:excluded,sourceFilteredOut:family.sourceId?studyFactualNodes.filter((n:any)=>!factualNodes.includes(n)).map((n:any)=>n.id):[],units:factualNodes.map((n:any)=>n.values.nodes.find((x:any)=>x.propertyId===unit)?.text??null),failedCheckIndexes:checks.map((x,i)=>x?null:i).filter((x):x is number=>x!==null),passed:checks.every(Boolean)});
}
report.passed=report.cases.every((x:any)=>x.passed);writeFileSync(`${root}/dashboard-comparison-query-verification.json`,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({passed:report.passed,cases:report.cases.map((x:any)=>({name:x.name,rows:x.actualIds.length,units:x.units}))},null,2));if(!report.passed)process.exitCode=1;






