import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash, randomUUID } from 'node:crypto';
import { Ops, Position, SystemIds, type Op } from '@geoprotocol/geo-sdk';
import { geoGraphqlRequest as gql } from '../src/geo-api-client';
import { EDUCATION_PUBLICATION as target } from '../src/education-bounty';
const root='data/education',prefix='community-eligibility-provision-debate';
if(existsSync(`${root}/${prefix}-publication.json`))throw Error('Preserve submitted debate payload.');
const rp=`${root}/${prefix}-registry.json`,r:Record<string,string>=existsSync(rp)?JSON.parse(readFileSync(rp,'utf8')):{},id=(k:string)=>r[k]??(r[k]=randomUUID().replaceAll('-',''));
const p={claim:'96f859efa1ca4b229372c86ad58b694b',factual:'da4a6c1f9d4446f9832ff3b49a4400ef',source:'49c5d5e1679a4dbdbfd33f618f227c94',related:'dfa6aebe1ca94bf29faccc4cc7afb24c',support:'1dc6a843458848198e7a6e672268f811',oppose:'4e6ec5d14292498a84e5f607ca1a08ce'};
const article='de88c706c7644e9a8681c221d5c2536e',study='327eef80a0dd423f846fbd50def5bf87',name='Eligible schools should expand universal free meals through the Community Eligibility Provision.',description='This policy position weighs the study’s household food-purchase and food-security findings against the limits of its quasi-experimental exposure design. The linked evidence does not establish academic effects or that every school is eligible or can implement CEP on the same terms.',support=['9b60b79a061f4931a20aa6147d1bed1e','e2319933570f466ab02023b00c288464'],relatedOnly=['88e3660656e74b14bb0c209134b69a41'],checks:string[]=[],ops:Op[]=[];
const check=(v:unknown,s:string)=>{if(!v)throw Error(s);checks.push(s)};
for(const [q,t] of [[SystemIds.TYPES_PROPERTY,'Relation'],[p.factual,'Checkbox'],[p.source,'Relation'],[p.related,'Relation'],[p.support,'Relation']]  as const){const d:any=await gql('query($id:UUID!){property(id:$id){dataTypeName}}',{variables:{id:q}});check(d.property?.dataTypeName===t,`Live ${t}: ${q}`)}
const parent=id('parent');const d:any=await gql('query($id:UUID!,$name:String!){entity(id:$id){spaceIds}entitiesConnection(first:10,filter:{name:{isInsensitive:$name}}){nodes{id}pageInfo{hasNextPage}}}',{variables:{id:parent,name}});check(!d.entity?.spaceIds?.length,'Allocated parent ID unused');check(!d.entitiesConnection.pageInfo.hasNextPage&&!d.entitiesConnection.nodes.length,'Complete all-space parent discovery has no candidate');
for(const c of [...support,...relatedOnly]){const x:any=await gql('query($id:UUID!,$space:UUID!){entity(id:$id){types{id}values(first:30,filter:{spaceId:{is:$space}}){nodes{propertyId boolean}pageInfo{hasNextPage}}}}',{variables:{id:c,space:target.spaceId}});check(x.entity?.types.some((t:any)=>t.id===p.claim)&&!x.entity.values.pageInfo.hasNextPage&&x.entity.values.nodes.some((v:any)=>v.propertyId===p.factual&&v.boolean===true),`Factual evidence available: ${c}`)}
const edge=(k:string,f:string,t:string,to:string)=>ops.push(...Ops.relations.create({id:id(`edge/${k}`),entityId:id(`relation/${k}`),fromEntity:f,type:t,toEntity:to,position:r[`position/${k}`]??(r[`position/${k}`]=Position.generate())}).ops);
ops.push(...Ops.entities.update({id:parent,name,description,values:[{property:p.factual,type:'boolean',value:false}]}).ops);edge('type',parent,SystemIds.TYPES_PROPERTY,p.claim);edge('source',parent,p.source,article);edge('study',parent,p.related,study);for(const c of [...support,...relatedOnly]){edge(`related/${c}`,parent,p.related,c);edge(`related-reverse/${c}`,c,p.related,parent)}for(const c of support)edge(`support/${c}`,parent,p.support,c);
const bytes=JSON.stringify(ops,(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('hex')}:typeof v==='bigint'?{$bigint:v.toString()}:v,2)+'\n',sha256=createHash('sha256').update(bytes).digest('hex'),batch={name:'Add Community Eligibility Provision expansion debate claim',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/${prefix}-ops.json`,sha256,journalPath:`${root}/${prefix}-publication.json`,validationPath:`${root}/${prefix}-validation.json`,entities:{parent,article,study,support,relatedOnly},operationCount:ops.length};writeFileSync(rp,JSON.stringify(r,null,2)+'\n');writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/${prefix}-batch.json`,JSON.stringify(batch,null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),opsHash:sha256,checks,rationale:'The policy proposition is deliberately nonfactual. Household spending and food-security findings support it; the alternate exposure specification is related-only so one study is not represented as conflicting evidence.'},null,2)+'\n');console.log(JSON.stringify(batch,null,2));
