import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash, randomUUID } from 'node:crypto';
import { Ops, Position, SystemIds, type Op } from '@geoprotocol/geo-sdk';
import { geoGraphqlRequest as gql } from '../src/geo-api-client';
import { EDUCATION_PUBLICATION as target } from '../src/education-bounty';

const root='data/education',prefix='boston-prek';
if(existsSync(`${root}/${prefix}-publication.json`))throw Error('Preserve submitted payload.');
const rp=`${root}/${prefix}-registry.json`,r:Record<string,string>=existsSync(rp)?JSON.parse(readFileSync(rp,'utf8')):{},id=(k:string)=>r[k]??(r[k]=randomUUID().replaceAll('-',''));
const p={article:'a2a5ed0cacef46b1835de457956ce915',initiative:'d272f19cef87485fb83e26fb68957395',claim:'96f859efa1ca4b229372c86ad58b694b',factual:'da4a6c1f9d4446f9832ff3b49a4400ef',doi:'7cb59354e30c48119e99ff62fcf61646',url:'412ff593e9154012a43d4c27ec5c68b6',source:'49c5d5e1679a4dbdbfd33f618f227c94',related:'dfa6aebe1ca94bf29faccc4cc7afb24c',topics:'806d52bc27e94c9193c057978b093351',topic:'0df9fad9098d4b11bacb9af0f7a79182',estimate:'e500e2585a964d2c9df4a47b199616c3',se:'cc28953bd89e406096c9627021f4713d',unit:'8405509cc7354655a348591349a5f025',entries:'210e9b352b454d6eb7a32906d24d3c8d',locator:'84dacbddca6a44079edb5e11a4c66b40'};
const articleName='The Long-Term Effects of Universal Preschool in Boston',initiativeName='Boston universal pre-K',url='https://www.nber.org/system/files/working_papers/w28756/w28756.pdf',doi='10.1093/qje/qjac036';
const rows=[
 ['college','Boston preschool attendance increased on-time college enrollment by 8.3 percentage points (46.0% control mean).','The 2SLS estimate is 0.083 (SE 0.030; p<.01; N=4,175), using a preschool-offer lottery as the instrument. It measures enrollment within six months of projected high-school graduation, not degree completion.','0.083','0.030',4175,'Percentage-point effect of Boston preschool attendance on on-time any-college enrollment; 2SLS/CACE estimate.','Table 3; Any college, on-time; p. 386.'],
 ['graduation','Boston preschool attendance increased ever high-school graduation by 6.0 percentage points (63.6% control mean).','The 2SLS estimate is 0.060 (SE 0.030; p<.05; N=3,883), instrumenting attendance with the preschool offer. The administrative outcome is graduation from a Massachusetts public high school, not college graduation.','0.060','0.030',3883,'Percentage-point effect of Boston preschool attendance on ever high-school graduation; 2SLS/CACE estimate.','Table 4; Ever graduated high school; p. 388.'],
 ['sat','Boston preschool attendance increased SAT test-taking by 8.5 percentage points (68.5% control mean).','The 2SLS estimate is 0.085 (SE 0.034; p<.05; N=2,559), among the paper’s tenth-grade-MCAS analysis sample. Taking the SAT is a preparation/participation outcome, not a score increase.','0.085','0.034',2559,'Percentage-point effect of Boston preschool attendance on taking the SAT; 2SLS/CACE estimate.','Table 5; Took SAT; p. 390.'],
 ['mcas-math','Boston preschool attendance had no detectable effect on stacked MCAS math scores (estimate 0.029 SD).','The 2SLS estimate is 0.029 SD (SE 0.056; N=3,615) across observed grades 3–8 and 10. This imprecise null estimate is not evidence of zero effect and does not contradict the paper’s non-test outcomes.','0.029','0.056',3615,'Standard-deviation effect of Boston preschool attendance on stacked MCAS math scores; 2SLS/CACE estimate.','Table 6; Math scores, all grades stacked; p. 392.'],
 ['mcas-ela','Boston preschool attendance had no detectable effect on stacked MCAS English-language-arts scores (estimate 0.005 SD).','The 2SLS estimate is 0.005 SD (SE 0.057; N=3,569) across observed grades 3–8 and 10. It is a standardized-test result and does not determine the study’s later educational-attainment outcomes.','0.005','0.057',3569,'Standard-deviation effect of Boston preschool attendance on stacked MCAS English-language-arts scores; 2SLS/CACE estimate.','Table 6; ELA scores, all grades stacked; p. 392.'],
 ['incarceration','Boston preschool attendance reduced recorded juvenile incarceration by 0.8 percentage points (0.7% control mean).','The 2SLS estimate is −0.008 (SE 0.005; p<.10; N=3,335) for an ever-recorded incarceration or Department of Youth Services placement. The paper treats this as a relatively imprecise disciplinary outcome, not a mechanism or general crime estimate.','-0.008','0.005',3335,'Percentage-point effect of Boston preschool attendance on recorded juvenile incarceration; 2SLS/CACE estimate.','Table 7; Juvenile incarceration; p. 394.'],
] as const;
const checks:string[]=[],ops:Op[]=[];const check=(v:unknown,s:string)=>{if(!v)throw Error(s);checks.push(s)};const decimal=(property:string,value:string)=>{const[whole,fraction='']=value.split('.'),negative=whole.startsWith('-'),digits=`${negative?whole.slice(1):whole}${fraction}`;return{property,type:'decimal' as const,exponent:-fraction.length,mantissa:{type:'i64' as const,value:BigInt(`${negative?'-':''}${digits}`)}}};
for(const [q,t] of [[SystemIds.TYPES_PROPERTY,'Relation'],[p.factual,'Checkbox'],[p.doi,'Text'],[p.url,'Text'],[p.source,'Relation'],[p.related,'Relation'],[p.topics,'Relation'],[p.estimate,'Decimal'],[p.se,'Decimal'],[p.unit,'Text'],[p.entries,'Integer'],[p.locator,'Text']] as const){const d:any=await gql('query($id:UUID!){property(id:$id){dataTypeName}}',{variables:{id:q}});check(d.property?.dataTypeName===t,`Live ${t}: ${q}`)}
for(const[key,name]of[['article',articleName],['initiative',initiativeName],...rows.map(x=>[`claim/${x[0]}`,x[1]])]as const){const entity=id(key),d:any=await gql('query($id:UUID!,$name:String!){entity(id:$id){spaceIds}entitiesConnection(first:10,filter:{name:{isInsensitive:$name}}){nodes{id}pageInfo{hasNextPage}}}',{variables:{id:entity,name}});check(!d.entity?.spaceIds?.length,`Allocated ID unused: ${key}`);check(!d.entitiesConnection.pageInfo.hasNextPage&&!d.entitiesConnection.nodes.length,`Complete all-space identity discovery: ${key}`)}
const article=id('article'),initiative=id('initiative'),edge=(k:string,f:string,t:string,to:string)=>ops.push(...Ops.relations.create({id:id(`edge/${k}`),entityId:id(`relation/${k}`),fromEntity:f,type:t,toEntity:to,position:r[`position/${k}`]??(r[`position/${k}`]=Position.generate())}).ops);
ops.push(...Ops.entities.update({id:article,name:articleName,description:'A lottery-based study of Boston public preschool’s educational, test-score, and disciplinary outcomes through young adulthood.',values:[{property:p.doi,type:'text',value:doi},{property:p.url,type:'text',value:url}]}).ops);edge('article/type',article,SystemIds.TYPES_PROPERTY,p.article);ops.push(...Ops.entities.update({id:initiative,name:initiativeName,description:'Boston Public Schools preschool for four-year-olds. This evidence concerns oversubscribed admissions lotteries in historical applicant cohorts, rather than all contemporary preschool delivery.',values:[{property:p.url,type:'text',value:url}]}).ops);edge('initiative/type',initiative,SystemIds.TYPES_PROPERTY,p.initiative);edge('initiative/source',initiative,p.source,article);edge('initiative/article',initiative,p.related,article);edge('initiative/topic',initiative,p.topics,p.topic);
for(const row of rows){const claim=id(`claim/${row[0]}`);ops.push(...Ops.entities.update({id:claim,name:row[1],description:row[2],values:[{property:p.factual,type:'boolean',value:true},decimal(p.estimate,row[3]),decimal(p.se,row[4]),{property:p.entries,type:'integer',value:BigInt(row[5])},{property:p.unit,type:'text',value:row[6]},{property:p.locator,type:'text',value:row[7]}]}).ops);edge(`${row[0]}/type`,claim,SystemIds.TYPES_PROPERTY,p.claim);edge(`${row[0]}/source`,claim,p.source,article);edge(`${row[0]}/initiative`,claim,p.related,initiative);edge(`${row[0]}/topic`,claim,p.topics,p.topic)}
const bytes=JSON.stringify(ops,(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('hex')}:typeof v==='bigint'?{$bigint:v.toString()}:v,2)+'\n',sha256=createHash('sha256').update(bytes).digest('hex'),batch={name:'Add Boston universal preschool lottery evidence',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/${prefix}-ops.json`,sha256,journalPath:`${root}/${prefix}-publication.json`,validationPath:`${root}/${prefix}-validation.json`,entities:{article,initiative,claims:Object.fromEntries(rows.map(row=>[row[0],id(`claim/${row[0]}`)]))},operationCount:ops.length};writeFileSync(rp,JSON.stringify(r,null,2)+'\n');writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/${prefix}-batch.json`,JSON.stringify(batch,null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),opsHash:sha256,checks,source:'Gray-Lobe, Pathak & Walters (2023), Quarterly Journal of Economics 138(1):363–411, DOI 10.1093/qje/qjac036; primary NBER working-paper PDF w28756.',transcription:'Table 3–7 2SLS estimates, standard errors, non-offered means, N, and source locators extracted from the primary PDF. Values are reported CACE estimates, not locally calculated group differences.',scope:'Initial six-outcome Boston lottery package. It preserves outcome-specific horizons, standard errors, standardized-score versus percentage-point units, and test-score null-estimate limits.'},null,2)+'\n');console.log(JSON.stringify(batch,null,2));
