import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash, randomUUID } from 'node:crypto';
import { Ops, Position, SystemIds, type Op } from '@geoprotocol/geo-sdk';
import { geoGraphqlRequest as gql } from '../src/geo-api-client';
import { EDUCATION_PUBLICATION as target } from '../src/education-bounty';

const root='data/education',prefix='tennessee-vpk-debate';
if(existsSync(`${root}/${prefix}-publication.json`))throw Error('Preserve submitted debate payload.');
const rp=`${root}/${prefix}-registry.json`,r:Record<string,string>=existsSync(rp)?JSON.parse(readFileSync(rp,'utf8')):{},id=(k:string)=>r[k]??(r[k]=randomUUID().replaceAll('-',''));
const p={claim:'96f859efa1ca4b229372c86ad58b694b',factual:'da4a6c1f9d4446f9832ff3b49a4400ef',source:'49c5d5e1679a4dbdbfd33f618f227c94',related:'dfa6aebe1ca94bf29faccc4cc7afb24c',support:'1dc6a843458848198e7a6e672268f811'};
const article='732cfa110f25499ba22a3f8025c9f903',initiative='4384e208b2964c6c9432823574a5a1e2',name='Tennessee should reconsider expanding its voluntary pre-K model on the basis of short-term readiness gains alone.',description='This policy proposition weighs the trial’s early pre-K test gains against its later third-grade achievement finding and mixed school-record outcomes. One Tennessee evaluation does not settle the value of every public pre-K model, delivery approach, or policy objective.',support=['3356d0eba4e54eeeab1db7a8d9691077','3b87b7c104cb44a6b82e8db91c163dc9'],related=['4fbfa11f56634a2a9206e79db9dc1d6a'],checks:string[]=[],ops:Op[]=[];
const check=(v:unknown,s:string)=>{if(!v)throw Error(s);checks.push(s)};
for(const [q,t] of [[SystemIds.TYPES_PROPERTY,'Relation'],[p.factual,'Checkbox'],[p.source,'Relation'],[p.related,'Relation'],[p.support,'Relation']] as const){const d:any=await gql('query($id:UUID!){property(id:$id){dataTypeName}}',{variables:{id:q}});check(d.property?.dataTypeName===t,`Live ${t}: ${q}`)}
const parent=id('parent'),d:any=await gql('query($id:UUID!,$name:String!){entity(id:$id){spaceIds}entitiesConnection(first:10,filter:{name:{isInsensitive:$name}}){nodes{id}pageInfo{hasNextPage}}}',{variables:{id:parent,name}});check(!d.entity?.spaceIds?.length,'Allocated parent ID unused');check(!d.entitiesConnection.pageInfo.hasNextPage&&!d.entitiesConnection.nodes.length,'Complete all-space parent discovery has no candidate');
for(const c of [...support,...related]){const x:any=await gql('query($id:UUID!,$space:UUID!){entity(id:$id){types{id}values(first:30,filter:{spaceId:{is:$space}}){nodes{propertyId boolean}pageInfo{hasNextPage}}}}',{variables:{id:c,space:target.spaceId}});check(x.entity?.types.some((t:any)=>t.id===p.claim)&&!x.entity.values.pageInfo.hasNextPage&&x.entity.values.nodes.some((v:any)=>v.propertyId===p.factual&&v.boolean===true),`Factual evidence available: ${c}`)}
const edge=(k:string,f:string,t:string,to:string)=>ops.push(...Ops.relations.create({id:id(`edge/${k}`),entityId:id(`relation/${k}`),fromEntity:f,type:t,toEntity:to,position:r[`position/${k}`]??(r[`position/${k}`]=Position.generate())}).ops);
ops.push(...Ops.entities.update({id:parent,name,description,values:[{property:p.factual,type:'boolean',value:false}]}).ops);edge('type',parent,SystemIds.TYPES_PROPERTY,p.claim);edge('source',parent,p.source,article);edge('initiative',parent,p.related,initiative);for(const c of [...support,...related]){edge(`related/${c}`,parent,p.related,c);edge(`related-reverse/${c}`,c,p.related,parent)}for(const c of support)edge(`support/${c}`,parent,p.support,c);
const bytes=JSON.stringify(ops,(_k,v)=>v instanceof Uint8Array?{$bytes:Buffer.from(v).toString('hex')}:typeof v==='bigint'?{$bigint:v.toString()}:v,2)+'\n',sha256=createHash('sha256').update(bytes).digest('hex'),batch={name:'Add Tennessee voluntary pre-K policy debate claim',spaceId:target.spaceId,bounty:target.bountyId,opsPath:`${root}/${prefix}-ops.json`,sha256,journalPath:`${root}/${prefix}-publication.json`,validationPath:`${root}/${prefix}-validation.json`,entities:{parent,article,initiative,support,related},operationCount:ops.length};
writeFileSync(rp,JSON.stringify(r,null,2)+'\n');writeFileSync(batch.opsPath,bytes);writeFileSync(`${root}/${prefix}-batch.json`,JSON.stringify(batch,null,2)+'\n');writeFileSync(batch.validationPath,JSON.stringify({ready:true,checkedAt:new Date().toISOString(),opsHash:sha256,checks,rationale:'A nonfactual, debatable policy proposition. The later achievement and behavior/record findings are Supporting arguments; the randomized design is Related context, not an argument. The wording preserves the paper’s early gains and program-specific limits.'},null,2)+'\n');console.log(JSON.stringify(batch,null,2));
